#Auto generated by Edalize

TOP_MODULE        := kmac_reduced_tb
VC_FILE           := lowrisc_dv_verilator_kmac_reduced_tb_0.vc
VERILATOR_OPTIONS := -DDISABLE_PRIM_CDC_RAND_DELAY --trace --trace-fst --trace-structs --trace-params --trace-max-array 1024 -CFLAGS "-std=c++17 -Wall -DVM_TRACE_FMT_FST -DTOPLEVEL_NAME=kmac_reduced_tb -g -O0" -LDFLAGS "-pthread -lutil -lelf" -Wall -Wno-fatal
MAKE_OPTIONS      := 
