# NVDLA Yosys Filelist
# For synthesis - excludes simulation-only and non-synthesizable files

# Include directories
-I../../outdir/nv_small/vmod/include
-I../../outdir/nv_small/vmod/vlibs
-I../../outdir/nv_small/vmod/nvdla/bdma
-I../../outdir/nv_small/vmod/nvdla/cacc
-I../../outdir/nv_small/vmod/nvdla/car
-I../../outdir/nv_small/vmod/nvdla/cbuf
-I../../outdir/nv_small/vmod/nvdla/cdma
-I../../outdir/nv_small/vmod/nvdla/cdp
-I../../outdir/nv_small/vmod/nvdla/cmac
-I../../outdir/nv_small/vmod/nvdla/csc
-I../../outdir/nv_small/vmod/nvdla/glb
-I../../outdir/nv_small/vmod/nvdla/nocif
-I../../outdir/nv_small/vmod/nvdla/pdp
-I../../outdir/nv_small/vmod/nvdla/retiming
-I../../outdir/nv_small/vmod/nvdla/rubik
-I../../outdir/nv_small/vmod/nvdla/sdp
-I../../outdir/nv_small/vmod/nvdla/top
-I../../outdir/nv_small/vmod/nvdla/csb_master
-I../../outdir/nv_small/vmod/nvdla/cfgrom
-I../../outdir/nv_small/vmod/nvdla/apb2csb
-I../../outdir/nv_small/vmod/rams/synth
-I.

# Defines for synthesis
-DSYNTHESIS
-DNO_PLI
-DNO_PLI_OR_EMU
-DDESIGNWARE_NOEXIST

# Synthesizable replacement for non-synthesizable DW components
../../vmod/vlibs/NV_DW_lsd.v

../../outdir/nv_small/vmod/vlibs/AN2D4PO4.v
../../outdir/nv_small/vmod/vlibs/CKLNQD12PO4.v
../../outdir/nv_small/vmod/vlibs/CKLNQD12.v
../../outdir/nv_small/vmod/vlibs/HLS_cdp_icvt.v
../../outdir/nv_small/vmod/vlibs/HLS_cdp_ocvt.v
../../outdir/nv_small/vmod/vlibs/HLS_fp16_to_fp17.v
../../outdir/nv_small/vmod/vlibs/HLS_fp16_to_fp32.v
../../outdir/nv_small/vmod/vlibs/HLS_fp17_add.v
../../outdir/nv_small/vmod/vlibs/HLS_fp17_mul.v
../../outdir/nv_small/vmod/vlibs/HLS_fp17_sub.v
../../outdir/nv_small/vmod/vlibs/HLS_fp17_to_fp16.v
../../outdir/nv_small/vmod/vlibs/HLS_fp17_to_fp32.v
../../outdir/nv_small/vmod/vlibs/HLS_fp32_add.v
../../outdir/nv_small/vmod/vlibs/HLS_fp32_mul.v
../../outdir/nv_small/vmod/vlibs/HLS_fp32_sub.v
../../outdir/nv_small/vmod/vlibs/HLS_fp32_to_fp16.v
../../outdir/nv_small/vmod/vlibs/HLS_fp32_to_fp17.v
../../outdir/nv_small/vmod/vlibs/HLS_uint16_to_fp17.v
../../outdir/nv_small/vmod/vlibs/LNQD1PO4.v
../../outdir/nv_small/vmod/vlibs/MUX2D4.v
../../outdir/nv_small/vmod/vlibs/MUX2HDD2.v
../../outdir/nv_small/vmod/vlibs/NV_BLKBOX_BUFFER.v
../../outdir/nv_small/vmod/vlibs/NV_BLKBOX_SINK.v
../../outdir/nv_small/vmod/vlibs/NV_BLKBOX_SRC0.v
../../outdir/nv_small/vmod/vlibs/NV_BLKBOX_SRC0_X.v
../../outdir/nv_small/vmod/vlibs/NV_CLK_gate_power.v
../../outdir/nv_small/vmod/vlibs/NV_NVDLA_CDP_HLS_icvt.v
../../outdir/nv_small/vmod/vlibs/NV_NVDLA_CDP_HLS_ocvt.v
../../outdir/nv_small/vmod/vlibs/NV_NVDLA_HLS_saturate.v
../../outdir/nv_small/vmod/vlibs/NV_NVDLA_HLS_shiftleftsu.v
../../outdir/nv_small/vmod/vlibs/NV_NVDLA_HLS_shiftrightsatsu.v
../../outdir/nv_small/vmod/vlibs/NV_NVDLA_HLS_shiftrightss.v
../../outdir/nv_small/vmod/vlibs/NV_NVDLA_HLS_shiftrightsu.v
../../outdir/nv_small/vmod/vlibs/NV_NVDLA_HLS_shiftrightusz.v
../../outdir/nv_small/vmod/vlibs/oneHotClk_async_read_clock.v
../../outdir/nv_small/vmod/vlibs/oneHotClk_async_write_clock.v
../../outdir/nv_small/vmod/vlibs/OR2D1.v
../../outdir/nv_small/vmod/vlibs/PGAOPV_AN2D2PO4.v
../../outdir/nv_small/vmod/vlibs/PGAOPV_DFCNQD2PO4.v
../../outdir/nv_small/vmod/vlibs/PGAOPV_INVD2PO4.v
../../outdir/nv_small/vmod/vlibs/p_SDFCNQD1PO4.v
../../outdir/nv_small/vmod/vlibs/p_SSYNC2DO_C_PP.v
../../outdir/nv_small/vmod/vlibs/p_SSYNC3DO_C_PPP.v
../../outdir/nv_small/vmod/vlibs/p_SSYNC3DO_S_PPP.v
../../outdir/nv_small/vmod/vlibs/p_SSYNC3DO.v
../../outdir/nv_small/vmod/vlibs/p_STRICTSYNC3DOTM_C_PPP.v
../../outdir/nv_small/vmod/vlibs/ScanShareSel_JTAG_reg_ext_cg.v
../../outdir/nv_small/vmod/vlibs/SDFCNQD1.v
../../outdir/nv_small/vmod/vlibs/SDFQD1.v
../../outdir/nv_small/vmod/vlibs/SDFSNQD1.v
../../outdir/nv_small/vmod/vlibs/sync2d_c_pp.v
../../outdir/nv_small/vmod/vlibs/sync3d_c_ppp.v
../../outdir/nv_small/vmod/vlibs/sync3d_s_ppp.v
../../outdir/nv_small/vmod/vlibs/sync3d.v
../../outdir/nv_small/vmod/vlibs/sync_reset.v

# RAM blackbox declarations - RAMs will be replaced with actual SRAM IP later
# This file declares all nv_ram_* modules as blackboxes for synthesis
./nvdla_ram_blackbox.v

../../outdir/nv_small/vmod/nvdla/apb2csb/NV_NVDLA_apb2csb.v
../../outdir/nv_small/vmod/nvdla/bdma/NV_NVDLA_BDMA_cq.v
../../outdir/nv_small/vmod/nvdla/bdma/NV_NVDLA_BDMA_csb.v
../../outdir/nv_small/vmod/nvdla/bdma/NV_NVDLA_BDMA_gate.v
../../outdir/nv_small/vmod/nvdla/bdma/NV_NVDLA_BDMA_load.v
../../outdir/nv_small/vmod/nvdla/bdma/NV_NVDLA_BDMA_reg.v
../../outdir/nv_small/vmod/nvdla/bdma/NV_NVDLA_BDMA_store.v
../../outdir/nv_small/vmod/nvdla/bdma/NV_NVDLA_bdma.v
../../outdir/nv_small/vmod/nvdla/cacc/NV_NVDLA_CACC_assembly_buffer.v
../../outdir/nv_small/vmod/nvdla/cacc/NV_NVDLA_CACC_assembly_ctrl.v
../../outdir/nv_small/vmod/nvdla/cacc/NV_NVDLA_CACC_CALC_int8.v
../../outdir/nv_small/vmod/nvdla/cacc/NV_NVDLA_CACC_calculator.v
../../outdir/nv_small/vmod/nvdla/cacc/NV_NVDLA_CACC_delivery_buffer.v
../../outdir/nv_small/vmod/nvdla/cacc/NV_NVDLA_CACC_delivery_ctrl.v
../../outdir/nv_small/vmod/nvdla/cacc/NV_NVDLA_CACC_dual_reg.v
../../outdir/nv_small/vmod/nvdla/cacc/NV_NVDLA_CACC_regfile.v
../../outdir/nv_small/vmod/nvdla/cacc/NV_NVDLA_CACC_single_reg.v
../../outdir/nv_small/vmod/nvdla/cacc/NV_NVDLA_CACC_slcg.v
../../outdir/nv_small/vmod/nvdla/cacc/NV_NVDLA_cacc.v
../../outdir/nv_small/vmod/nvdla/car/NV_NVDLA_core_reset.v
../../outdir/nv_small/vmod/nvdla/car/NV_NVDLA_reset.v
../../outdir/nv_small/vmod/nvdla/car/NV_NVDLA_ssync3d_c.v
../../outdir/nv_small/vmod/nvdla/car/NV_NVDLA_ssync3d.v
../../outdir/nv_small/vmod/nvdla/car/NV_NVDLA_sync3d_c.v
../../outdir/nv_small/vmod/nvdla/car/NV_NVDLA_sync3d_s.v
../../outdir/nv_small/vmod/nvdla/car/NV_NVDLA_sync3d.v
../../outdir/nv_small/vmod/nvdla/cbuf/NV_NVDLA_cbuf.v
../../outdir/nv_small/vmod/nvdla/cdma/NV_NVDLA_CDMA_CVT_cell.v
../../outdir/nv_small/vmod/nvdla/cdma/NV_NVDLA_CDMA_cvt.v
../../outdir/nv_small/vmod/nvdla/cdma/NV_NVDLA_CDMA_DC_fifo.v
../../outdir/nv_small/vmod/nvdla/cdma/NV_NVDLA_CDMA_dc.v
../../outdir/nv_small/vmod/nvdla/cdma/NV_NVDLA_CDMA_dma_mux.v
../../outdir/nv_small/vmod/nvdla/cdma/NV_NVDLA_CDMA_dual_reg.v
../../outdir/nv_small/vmod/nvdla/cdma/NV_NVDLA_CDMA_IMG_ctrl.v
../../outdir/nv_small/vmod/nvdla/cdma/NV_NVDLA_CDMA_IMG_fifo.v
../../outdir/nv_small/vmod/nvdla/cdma/NV_NVDLA_CDMA_IMG_pack.v
../../outdir/nv_small/vmod/nvdla/cdma/NV_NVDLA_CDMA_IMG_sg2pack_fifo.v
../../outdir/nv_small/vmod/nvdla/cdma/NV_NVDLA_CDMA_IMG_sg.v
../../outdir/nv_small/vmod/nvdla/cdma/NV_NVDLA_CDMA_img.v
../../outdir/nv_small/vmod/nvdla/cdma/NV_NVDLA_CDMA_regfile.v
../../outdir/nv_small/vmod/nvdla/cdma/NV_NVDLA_CDMA_shared_buffer.v
../../outdir/nv_small/vmod/nvdla/cdma/NV_NVDLA_CDMA_single_reg.v
../../outdir/nv_small/vmod/nvdla/cdma/NV_NVDLA_CDMA_slcg.v
../../outdir/nv_small/vmod/nvdla/cdma/NV_NVDLA_CDMA_status.v
../../outdir/nv_small/vmod/nvdla/cdma/NV_NVDLA_cdma.v
../../outdir/nv_small/vmod/nvdla/cdma/NV_NVDLA_CDMA_WG_fifo.v
../../outdir/nv_small/vmod/nvdla/cdma/NV_NVDLA_CDMA_wg.v
../../outdir/nv_small/vmod/nvdla/cdma/NV_NVDLA_CDMA_WT_fifo.v
../../outdir/nv_small/vmod/nvdla/cdma/NV_NVDLA_CDMA_WT_sp_arb.v
../../outdir/nv_small/vmod/nvdla/cdma/NV_NVDLA_CDMA_wt.v
../../outdir/nv_small/vmod/nvdla/cdma/NV_NVDLA_CDMA_WT_wgs_fifo.v
../../outdir/nv_small/vmod/nvdla/cdma/NV_NVDLA_CDMA_WT_wrr_arb.v
../../outdir/nv_small/vmod/nvdla/cdp/fp_format_cvt.v
../../outdir/nv_small/vmod/nvdla/cdp/fp_sum_block.v
../../outdir/nv_small/vmod/nvdla/cdp/int_sum_block_tp1.v
../../outdir/nv_small/vmod/nvdla/cdp/int_sum_block.v
../../outdir/nv_small/vmod/nvdla/cdp/NV_NVDLA_CDP_DP_bufferin_tp1.v
../../outdir/nv_small/vmod/nvdla/cdp/NV_NVDLA_CDP_DP_bufferin.v
../../outdir/nv_small/vmod/nvdla/cdp/NV_NVDLA_CDP_DP_cvtin.v
../../outdir/nv_small/vmod/nvdla/cdp/NV_NVDLA_CDP_DP_cvtout.v
../../outdir/nv_small/vmod/nvdla/cdp/NV_NVDLA_CDP_DP_INTP_unit.v
../../outdir/nv_small/vmod/nvdla/cdp/NV_NVDLA_CDP_DP_intp.v
../../outdir/nv_small/vmod/nvdla/cdp/NV_NVDLA_CDP_DP_LUT_CTRL_unit.v
../../outdir/nv_small/vmod/nvdla/cdp/NV_NVDLA_CDP_DP_LUT_ctrl.v
../../outdir/nv_small/vmod/nvdla/cdp/NV_NVDLA_CDP_DP_lut.v
../../outdir/nv_small/vmod/nvdla/cdp/NV_NVDLA_CDP_DP_MUL_unit.v
../../outdir/nv_small/vmod/nvdla/cdp/NV_NVDLA_CDP_DP_mul.v
../../outdir/nv_small/vmod/nvdla/cdp/NV_NVDLA_CDP_DP_nan.v
../../outdir/nv_small/vmod/nvdla/cdp/NV_NVDLA_CDP_DP_sum.v
../../outdir/nv_small/vmod/nvdla/cdp/NV_NVDLA_CDP_DP_syncfifo.v
../../outdir/nv_small/vmod/nvdla/cdp/NV_NVDLA_CDP_dp.v
../../outdir/nv_small/vmod/nvdla/cdp/NV_NVDLA_CDP_RDMA_cq.v
../../outdir/nv_small/vmod/nvdla/cdp/NV_NVDLA_CDP_RDMA_eg.v
../../outdir/nv_small/vmod/nvdla/cdp/NV_NVDLA_CDP_RDMA_ig.v
../../outdir/nv_small/vmod/nvdla/cdp/NV_NVDLA_CDP_RDMA_REG_dual.v
../../outdir/nv_small/vmod/nvdla/cdp/NV_NVDLA_CDP_RDMA_REG_single.v
../../outdir/nv_small/vmod/nvdla/cdp/NV_NVDLA_CDP_RDMA_reg.v
../../outdir/nv_small/vmod/nvdla/cdp/NV_NVDLA_CDP_rdma.v
../../outdir/nv_small/vmod/nvdla/cdp/NV_NVDLA_CDP_REG_dual.v
../../outdir/nv_small/vmod/nvdla/cdp/NV_NVDLA_CDP_REG_single.v
../../outdir/nv_small/vmod/nvdla/cdp/NV_NVDLA_CDP_reg.v
../../outdir/nv_small/vmod/nvdla/cdp/NV_NVDLA_CDP_slcg.v
../../outdir/nv_small/vmod/nvdla/cdp/NV_NVDLA_cdp.v
../../outdir/nv_small/vmod/nvdla/cdp/NV_NVDLA_CDP_wdma.v
../../outdir/nv_small/vmod/nvdla/cfgrom/NV_NVDLA_CFGROM_rom.v
../../outdir/nv_small/vmod/nvdla/cfgrom/NV_NVDLA_cfgrom.v
../../outdir/nv_small/vmod/nvdla/cmac/NV_NVDLA_CMAC_CORE_active.v
../../outdir/nv_small/vmod/nvdla/cmac/NV_NVDLA_CMAC_CORE_cfg.v
../../outdir/nv_small/vmod/nvdla/cmac/NV_NVDLA_CMAC_CORE_mac.v
../../outdir/nv_small/vmod/nvdla/cmac/NV_NVDLA_CMAC_CORE_rt_in.v
../../outdir/nv_small/vmod/nvdla/cmac/NV_NVDLA_CMAC_CORE_rt_out.v
../../outdir/nv_small/vmod/nvdla/cmac/NV_NVDLA_CMAC_CORE_slcg.v
../../outdir/nv_small/vmod/nvdla/cmac/NV_NVDLA_CMAC_core.v
../../outdir/nv_small/vmod/nvdla/cmac/NV_NVDLA_CMAC_REG_dual.v
../../outdir/nv_small/vmod/nvdla/cmac/NV_NVDLA_CMAC_REG_single.v
../../outdir/nv_small/vmod/nvdla/cmac/NV_NVDLA_CMAC_reg.v
../../outdir/nv_small/vmod/nvdla/cmac/NV_NVDLA_cmac.v
../../outdir/nv_small/vmod/nvdla/csb_master/NV_NVDLA_CSB_MASTER_csb2falcon_fifo.v
../../outdir/nv_small/vmod/nvdla/csb_master/NV_NVDLA_CSB_MASTER_falcon2csb_fifo.v
../../outdir/nv_small/vmod/nvdla/csb_master/NV_NVDLA_csb_master.v
../../outdir/nv_small/vmod/nvdla/csc/NV_NVDLA_CSC_dl.v
../../outdir/nv_small/vmod/nvdla/csc/NV_NVDLA_CSC_dual_reg.v
../../outdir/nv_small/vmod/nvdla/csc/NV_NVDLA_CSC_pra_cell.v
../../outdir/nv_small/vmod/nvdla/csc/NV_NVDLA_CSC_regfile.v
../../outdir/nv_small/vmod/nvdla/csc/NV_NVDLA_CSC_SG_dat_fifo.v
../../outdir/nv_small/vmod/nvdla/csc/NV_NVDLA_CSC_sg.v
../../outdir/nv_small/vmod/nvdla/csc/NV_NVDLA_CSC_SG_wt_fifo.v
../../outdir/nv_small/vmod/nvdla/csc/NV_NVDLA_CSC_single_reg.v
../../outdir/nv_small/vmod/nvdla/csc/NV_NVDLA_CSC_slcg.v
../../outdir/nv_small/vmod/nvdla/csc/NV_NVDLA_csc.v
../../outdir/nv_small/vmod/nvdla/csc/NV_NVDLA_CSC_WL_dec.v
../../outdir/nv_small/vmod/nvdla/csc/NV_NVDLA_CSC_wl.v
../../outdir/nv_small/vmod/nvdla/glb/NV_NVDLA_GLB_CSB_reg.v
../../outdir/nv_small/vmod/nvdla/glb/NV_NVDLA_GLB_csb.v
../../outdir/nv_small/vmod/nvdla/glb/NV_NVDLA_GLB_fc.v
../../outdir/nv_small/vmod/nvdla/glb/NV_NVDLA_GLB_ic.v
../../outdir/nv_small/vmod/nvdla/glb/NV_NVDLA_glb.v
../../outdir/nv_small/vmod/nvdla/nocif/NV_NVDLA_DMAIF_rdreq.v
../../outdir/nv_small/vmod/nvdla/nocif/NV_NVDLA_DMAIF_rdrsp.v
../../outdir/nv_small/vmod/nvdla/nocif/NV_NVDLA_DMAIF_wr.v
../../outdir/nv_small/vmod/nvdla/nocif/NV_NVDLA_MCIF_CSB_reg.v
../../outdir/nv_small/vmod/nvdla/nocif/NV_NVDLA_MCIF_csb.v
../../outdir/nv_small/vmod/nvdla/nocif/NV_NVDLA_NOCIF_DRAM_READ_cq.v
../../outdir/nv_small/vmod/nvdla/nocif/NV_NVDLA_NOCIF_DRAM_READ_eg.v
../../outdir/nv_small/vmod/nvdla/nocif/NV_NVDLA_NOCIF_DRAM_READ_IG_arb.v
../../outdir/nv_small/vmod/nvdla/nocif/NV_NVDLA_NOCIF_DRAM_READ_IG_bpt.v
../../outdir/nv_small/vmod/nvdla/nocif/NV_NVDLA_NOCIF_DRAM_READ_IG_cvt.v
../../outdir/nv_small/vmod/nvdla/nocif/NV_NVDLA_NOCIF_DRAM_READ_IG_spt.v
../../outdir/nv_small/vmod/nvdla/nocif/NV_NVDLA_NOCIF_DRAM_READ_ig.v
../../outdir/nv_small/vmod/nvdla/nocif/NV_NVDLA_NOCIF_DRAM_read.v
../../outdir/nv_small/vmod/nvdla/nocif/NV_NVDLA_NOCIF_dram.v
../../outdir/nv_small/vmod/nvdla/nocif/NV_NVDLA_NOCIF_DRAM_WRITE_cq.v
../../outdir/nv_small/vmod/nvdla/nocif/NV_NVDLA_NOCIF_DRAM_WRITE_eg.v
../../outdir/nv_small/vmod/nvdla/nocif/NV_NVDLA_NOCIF_DRAM_WRITE_IG_arb.v
../../outdir/nv_small/vmod/nvdla/nocif/NV_NVDLA_NOCIF_DRAM_WRITE_IG_bpt.v
../../outdir/nv_small/vmod/nvdla/nocif/NV_NVDLA_NOCIF_DRAM_WRITE_IG_cvt.v
../../outdir/nv_small/vmod/nvdla/nocif/NV_NVDLA_NOCIF_DRAM_WRITE_IG_spt.v
../../outdir/nv_small/vmod/nvdla/nocif/NV_NVDLA_NOCIF_DRAM_WRITE_ig.v
../../outdir/nv_small/vmod/nvdla/nocif/NV_NVDLA_NOCIF_DRAM_write.v
../../outdir/nv_small/vmod/nvdla/nocif/NV_NVDLA_nocif.v
../../outdir/nv_small/vmod/nvdla/nocif/NV_NVDLA_XXIF_libs.v
../../outdir/nv_small/vmod/nvdla/pdp/cal1d_fp16_pool_sum.v
../../outdir/nv_small/vmod/nvdla/pdp/fp16_4add.v
../../outdir/nv_small/vmod/nvdla/pdp/NV_NVDLA_PDP_CORE_cal1d.v
../../outdir/nv_small/vmod/nvdla/pdp/NV_NVDLA_PDP_CORE_cal2d.v
../../outdir/nv_small/vmod/nvdla/pdp/NV_NVDLA_PDP_CORE_preproc.v
../../outdir/nv_small/vmod/nvdla/pdp/NV_NVDLA_PDP_CORE_unit1d.v
../../outdir/nv_small/vmod/nvdla/pdp/NV_NVDLA_PDP_core.v
../../outdir/nv_small/vmod/nvdla/pdp/NV_NVDLA_PDP_nan.v
../../outdir/nv_small/vmod/nvdla/pdp/NV_NVDLA_PDP_RDMA_cq.v
../../outdir/nv_small/vmod/nvdla/pdp/NV_NVDLA_PDP_RDMA_eg.v
../../outdir/nv_small/vmod/nvdla/pdp/NV_NVDLA_PDP_RDMA_ig.v
../../outdir/nv_small/vmod/nvdla/pdp/NV_NVDLA_PDP_RDMA_REG_dual.v
../../outdir/nv_small/vmod/nvdla/pdp/NV_NVDLA_PDP_RDMA_REG_single.v
../../outdir/nv_small/vmod/nvdla/pdp/NV_NVDLA_PDP_RDMA_reg.v
../../outdir/nv_small/vmod/nvdla/pdp/NV_NVDLA_PDP_rdma.v
../../outdir/nv_small/vmod/nvdla/pdp/NV_NVDLA_PDP_REG_dual.v
../../outdir/nv_small/vmod/nvdla/pdp/NV_NVDLA_PDP_REG_single.v
../../outdir/nv_small/vmod/nvdla/pdp/NV_NVDLA_PDP_reg.v
../../outdir/nv_small/vmod/nvdla/pdp/NV_NVDLA_PDP_slcg.v
../../outdir/nv_small/vmod/nvdla/pdp/NV_NVDLA_pdp.v
../../outdir/nv_small/vmod/nvdla/pdp/NV_NVDLA_PDP_WDMA_cmd.v
../../outdir/nv_small/vmod/nvdla/pdp/NV_NVDLA_PDP_WDMA_dat.v
../../outdir/nv_small/vmod/nvdla/pdp/NV_NVDLA_PDP_wdma.v
../../outdir/nv_small/vmod/nvdla/retiming/NV_NVDLA_RT_cacc2glb.v
../../outdir/nv_small/vmod/nvdla/retiming/NV_NVDLA_RT_cmac_a2cacc.v
../../outdir/nv_small/vmod/nvdla/retiming/NV_NVDLA_RT_cmac_b2cacc.v
../../outdir/nv_small/vmod/nvdla/retiming/NV_NVDLA_RT_csb2cacc.v
../../outdir/nv_small/vmod/nvdla/retiming/NV_NVDLA_RT_csb2cmac.v
../../outdir/nv_small/vmod/nvdla/retiming/NV_NVDLA_RT_csc2cmac_a.v
../../outdir/nv_small/vmod/nvdla/retiming/NV_NVDLA_RT_csc2cmac_b.v
../../outdir/nv_small/vmod/nvdla/retiming/NV_NVDLA_RT_sdp2nocif.v
../../outdir/nv_small/vmod/nvdla/rubik/NV_NVDLA_RUBIK_dma.v
../../outdir/nv_small/vmod/nvdla/rubik/NV_NVDLA_RUBIK_dr2drc.v
../../outdir/nv_small/vmod/nvdla/rubik/NV_NVDLA_RUBIK_dual_reg.v
../../outdir/nv_small/vmod/nvdla/rubik/NV_NVDLA_RUBIK_fifo.v
../../outdir/nv_small/vmod/nvdla/rubik/NV_NVDLA_RUBIK_intr.v
../../outdir/nv_small/vmod/nvdla/rubik/NV_NVDLA_RUBIK_regfile.v
../../outdir/nv_small/vmod/nvdla/rubik/NV_NVDLA_RUBIK_rf_core.v
../../outdir/nv_small/vmod/nvdla/rubik/NV_NVDLA_RUBIK_rf_ctrl.v
../../outdir/nv_small/vmod/nvdla/rubik/NV_NVDLA_RUBIK_rf_rcmd.v
../../outdir/nv_small/vmod/nvdla/rubik/NV_NVDLA_RUBIK_rf_wcmd.v
../../outdir/nv_small/vmod/nvdla/rubik/NV_NVDLA_RUBIK_seq_gen.v
../../outdir/nv_small/vmod/nvdla/rubik/NV_NVDLA_RUBIK_single_reg.v
../../outdir/nv_small/vmod/nvdla/rubik/NV_NVDLA_RUBIK_slcg.v
../../outdir/nv_small/vmod/nvdla/rubik/NV_NVDLA_rubik.v
../../outdir/nv_small/vmod/nvdla/rubik/NV_NVDLA_RUBIK_wrdma_cmd.v
../../outdir/nv_small/vmod/nvdla/rubik/NV_NVDLA_RUBIK_wrdma_data.v
../../outdir/nv_small/vmod/nvdla/rubik/NV_NVDLA_RUBIK_wr_req.v
../../outdir/nv_small/vmod/nvdla/sdp/NV_NVDLA_SDP_BRDMA_cq.v
../../outdir/nv_small/vmod/nvdla/sdp/NV_NVDLA_SDP_BRDMA_gate.v
../../outdir/nv_small/vmod/nvdla/sdp/NV_NVDLA_SDP_BRDMA_lat_fifo.v
../../outdir/nv_small/vmod/nvdla/sdp/NV_NVDLA_SDP_brdma.v
../../outdir/nv_small/vmod/nvdla/sdp/NV_NVDLA_SDP_cmux.v
../../outdir/nv_small/vmod/nvdla/sdp/NV_NVDLA_SDP_CORE_gate.v
../../outdir/nv_small/vmod/nvdla/sdp/NV_NVDLA_SDP_CORE_pack.v
../../outdir/nv_small/vmod/nvdla/sdp/NV_NVDLA_SDP_CORE_unpack.v
../../outdir/nv_small/vmod/nvdla/sdp/NV_NVDLA_SDP_core.v
../../outdir/nv_small/vmod/nvdla/sdp/NV_NVDLA_SDP_CORE_Y_lut.v
../../outdir/nv_small/vmod/nvdla/sdp/NV_NVDLA_SDP_CORE_y.v
../../outdir/nv_small/vmod/nvdla/sdp/NV_NVDLA_SDP_ERDMA_cq.v
../../outdir/nv_small/vmod/nvdla/sdp/NV_NVDLA_SDP_ERDMA_gate.v
../../outdir/nv_small/vmod/nvdla/sdp/NV_NVDLA_SDP_ERDMA_lat_fifo.v
../../outdir/nv_small/vmod/nvdla/sdp/NV_NVDLA_SDP_erdma.v
../../outdir/nv_small/vmod/nvdla/sdp/NV_NVDLA_SDP_HLS_C_int.v
../../outdir/nv_small/vmod/nvdla/sdp/NV_NVDLA_SDP_HLS_c.v
../../outdir/nv_small/vmod/nvdla/sdp/NV_NVDLA_SDP_HLS_lut_expn.v
../../outdir/nv_small/vmod/nvdla/sdp/NV_NVDLA_SDP_HLS_lut_line.v
../../outdir/nv_small/vmod/nvdla/sdp/NV_NVDLA_SDP_HLS_prelu.v
../../outdir/nv_small/vmod/nvdla/sdp/NV_NVDLA_SDP_HLS_relu.v
../../outdir/nv_small/vmod/nvdla/sdp/NV_NVDLA_SDP_HLS_sync2data.v
../../outdir/nv_small/vmod/nvdla/sdp/NV_NVDLA_SDP_HLS_x1_int.v
../../outdir/nv_small/vmod/nvdla/sdp/NV_NVDLA_SDP_HLS_x2_int.v
../../outdir/nv_small/vmod/nvdla/sdp/NV_NVDLA_SDP_HLS_X_int_alu.v
../../outdir/nv_small/vmod/nvdla/sdp/NV_NVDLA_SDP_HLS_X_int_mul.v
../../outdir/nv_small/vmod/nvdla/sdp/NV_NVDLA_SDP_HLS_X_int_relu.v
../../outdir/nv_small/vmod/nvdla/sdp/NV_NVDLA_SDP_HLS_X_int_trt.v
../../outdir/nv_small/vmod/nvdla/sdp/NV_NVDLA_SDP_HLS_Y_cvt_top.v
../../outdir/nv_small/vmod/nvdla/sdp/NV_NVDLA_SDP_HLS_Y_idx_top.v
../../outdir/nv_small/vmod/nvdla/sdp/NV_NVDLA_SDP_HLS_Y_inp_top.v
../../outdir/nv_small/vmod/nvdla/sdp/NV_NVDLA_SDP_HLS_Y_int_alu.v
../../outdir/nv_small/vmod/nvdla/sdp/NV_NVDLA_SDP_HLS_Y_int_core.v
../../outdir/nv_small/vmod/nvdla/sdp/NV_NVDLA_SDP_HLS_Y_int_cvt.v
../../outdir/nv_small/vmod/nvdla/sdp/NV_NVDLA_SDP_HLS_Y_int_idx.v
../../outdir/nv_small/vmod/nvdla/sdp/NV_NVDLA_SDP_HLS_Y_int_inp.v
../../outdir/nv_small/vmod/nvdla/sdp/NV_NVDLA_SDP_HLS_Y_int_mul.v
../../outdir/nv_small/vmod/nvdla/sdp/NV_NVDLA_SDP_MRDMA_cq.v
../../outdir/nv_small/vmod/nvdla/sdp/NV_NVDLA_SDP_MRDMA_EG_cmd.v
../../outdir/nv_small/vmod/nvdla/sdp/NV_NVDLA_SDP_MRDMA_EG_din.v
../../outdir/nv_small/vmod/nvdla/sdp/NV_NVDLA_SDP_MRDMA_EG_dout.v
../../outdir/nv_small/vmod/nvdla/sdp/NV_NVDLA_SDP_MRDMA_eg.v
../../outdir/nv_small/vmod/nvdla/sdp/NV_NVDLA_SDP_MRDMA_gate.v
../../outdir/nv_small/vmod/nvdla/sdp/NV_NVDLA_SDP_MRDMA_ig.v
../../outdir/nv_small/vmod/nvdla/sdp/NV_NVDLA_SDP_mrdma.v
../../outdir/nv_small/vmod/nvdla/sdp/NV_NVDLA_SDP_NRDMA_cq.v
../../outdir/nv_small/vmod/nvdla/sdp/NV_NVDLA_SDP_NRDMA_gate.v
../../outdir/nv_small/vmod/nvdla/sdp/NV_NVDLA_SDP_NRDMA_lat_fifo.v
../../outdir/nv_small/vmod/nvdla/sdp/NV_NVDLA_SDP_nrdma.v
../../outdir/nv_small/vmod/nvdla/sdp/NV_NVDLA_SDP_RDMA_dmaif.v
../../outdir/nv_small/vmod/nvdla/sdp/NV_NVDLA_SDP_RDMA_EG_ro.v
../../outdir/nv_small/vmod/nvdla/sdp/NV_NVDLA_SDP_RDMA_eg.v
../../outdir/nv_small/vmod/nvdla/sdp/NV_NVDLA_SDP_RDMA_ig.v
../../outdir/nv_small/vmod/nvdla/sdp/NV_NVDLA_SDP_RDMA_pack.v
../../outdir/nv_small/vmod/nvdla/sdp/NV_NVDLA_SDP_RDMA_REG_dual.v
../../outdir/nv_small/vmod/nvdla/sdp/NV_NVDLA_SDP_RDMA_REG_single.v
../../outdir/nv_small/vmod/nvdla/sdp/NV_NVDLA_SDP_RDMA_reg.v
../../outdir/nv_small/vmod/nvdla/sdp/NV_NVDLA_SDP_RDMA_unpack.v
../../outdir/nv_small/vmod/nvdla/sdp/NV_NVDLA_SDP_rdma.v
../../outdir/nv_small/vmod/nvdla/sdp/NV_NVDLA_SDP_REG_dual.v
../../outdir/nv_small/vmod/nvdla/sdp/NV_NVDLA_SDP_REG_single.v
../../outdir/nv_small/vmod/nvdla/sdp/NV_NVDLA_SDP_reg.v
../../outdir/nv_small/vmod/nvdla/sdp/NV_NVDLA_sdp.v
../../outdir/nv_small/vmod/nvdla/sdp/NV_NVDLA_SDP_WDMA_cmd.v
../../outdir/nv_small/vmod/nvdla/sdp/NV_NVDLA_SDP_WDMA_DAT_in.v
../../outdir/nv_small/vmod/nvdla/sdp/NV_NVDLA_SDP_WDMA_DAT_out.v
../../outdir/nv_small/vmod/nvdla/sdp/NV_NVDLA_SDP_WDMA_dat.v
../../outdir/nv_small/vmod/nvdla/sdp/NV_NVDLA_SDP_WDMA_gate.v
../../outdir/nv_small/vmod/nvdla/sdp/NV_NVDLA_SDP_WDMA_intr.v
../../outdir/nv_small/vmod/nvdla/sdp/NV_NVDLA_SDP_WDMA_unpack.v
../../outdir/nv_small/vmod/nvdla/sdp/NV_NVDLA_SDP_wdma.v
../../outdir/nv_small/vmod/nvdla/top/NV_NVDLA_partition_a.v
../../outdir/nv_small/vmod/nvdla/top/NV_NVDLA_partition_c.v
../../outdir/nv_small/vmod/nvdla/top/NV_NVDLA_partition_m.v
../../outdir/nv_small/vmod/nvdla/top/NV_NVDLA_partition_o.v
../../outdir/nv_small/vmod/nvdla/top/NV_NVDLA_partition_p.v
../../outdir/nv_small/vmod/nvdla/top/NV_nvdla.v
