// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Primary model header
//
// This header should be included by all source files instantiating the design.
// The class here is then constructed to instantiate the design.
// See the Verilator manual for examples.

#ifndef VERILATED_VNV_NVDLA_H_
#define VERILATED_VNV_NVDLA_H_  // guard

#include "verilated.h"

class VNV_nvdla__Syms;
class VNV_nvdla___024root;
class VNV_nvdla_NV_NVDLA_partition_m;
class VNV_nvdla_NV_NVDLA_NOCIF_DRAM_READ_IG_bpt;
class VNV_nvdla_NV_NVDLA_NOCIF_DRAM_READ_EG_lat_fifo;
class VNV_nvdla_NV_NVDLA_NOCIF_DRAM_READ_EG_ro_fifo;
class VNV_nvdla_nv_ram_rwst_256x8;
class VNV_nvdla_ScanShareSel_JTAG_reg_ext_cg__pi7;
class VNV_nvdla_ScanShareSel_JTAG_reg_ext_cg__pi19;
class VNV_nvdla_NV_NVDLA_NOCIF_DRAM_WRITE_IG_bpt;
class VNV_nvdla_NV_NVDLA_CDP_RDMA_ro_fifo;
class VNV_nvdla_nv_ram_rwsp_61x65__Fz2;
class VNV_nvdla_NV_NVDLA_CDP_WDMA_dat_fifo;
class VNV_nvdla_NV_NVDLA_PDP_RDMA_ro_fifo;
class VNV_nvdla_NV_NVDLA_PDP_WDMA_DAT_fifo;
class VNV_nvdla_NV_NVDLA_PDP_CORE_unit1d;
class VNV_nvdla_nv_ram_rws_128x18;
class VNV_nvdla_NV_NVDLA_CDMA_dual_reg;
class VNV_nvdla_ScanShareSel_JTAG_reg_ext_cg__pi22;
class VNV_nvdla_nv_ram_rwsp_128x6__Fz2;
class VNV_nvdla_NV_NVDLA_CDMA_CVT_cell;
class VNV_nvdla_nv_ram_rws_16x64;
class VNV_nvdla_nv_ram_rws_256x64;
class VNV_nvdla_ScanShareSel_JTAG_reg_ext_cg__pi13;
class VNV_nvdla_nv_ram_rwsp_160x16__Fz2;
class VNV_nvdla_NV_NVDLA_SDP_RDMA_EG_ro;
class VNV_nvdla_nv_ram_rwsp_160x65__Fz2;
class VNV_nvdla_NV_NVDLA_SDP_REG_dual;


// This class is the main interface to the Verilated model
class VNV_nvdla VL_NOT_FINAL {
  private:
    // Symbol table holding complete model state (owned by this class)
    VNV_nvdla__Syms* const vlSymsp;

  public:

    // PORTS
    // The application code writes and reads these signals to
    // propagate new values into/out from the Verilated model.
    VL_IN8(&dla_core_clk,0,0);
    VL_IN8(&dla_csb_clk,0,0);
    VL_IN8(&global_clk_ovr_on,0,0);
    VL_IN8(&tmc2slcg_disable_clock_gating,0,0);
    VL_IN8(&dla_reset_rstn,0,0);
    VL_IN8(&direct_reset_,0,0);
    VL_IN8(&test_mode,0,0);
    VL_IN8(&csb2nvdla_valid,0,0);
    VL_OUT8(&csb2nvdla_ready,0,0);
    VL_IN8(&csb2nvdla_write,0,0);
    VL_IN8(&csb2nvdla_nposted,0,0);
    VL_OUT8(&nvdla2csb_valid,0,0);
    VL_OUT8(&nvdla2csb_wr_complete,0,0);
    VL_OUT8(&nvdla_core2dbb_aw_awvalid,0,0);
    VL_IN8(&nvdla_core2dbb_aw_awready,0,0);
    VL_OUT8(&nvdla_core2dbb_aw_awid,7,0);
    VL_OUT8(&nvdla_core2dbb_aw_awlen,3,0);
    VL_OUT8(&nvdla_core2dbb_w_wvalid,0,0);
    VL_IN8(&nvdla_core2dbb_w_wready,0,0);
    VL_OUT8(&nvdla_core2dbb_w_wstrb,7,0);
    VL_OUT8(&nvdla_core2dbb_w_wlast,0,0);
    VL_OUT8(&nvdla_core2dbb_ar_arvalid,0,0);
    VL_IN8(&nvdla_core2dbb_ar_arready,0,0);
    VL_OUT8(&nvdla_core2dbb_ar_arid,7,0);
    VL_OUT8(&nvdla_core2dbb_ar_arlen,3,0);
    VL_IN8(&nvdla_core2dbb_b_bvalid,0,0);
    VL_OUT8(&nvdla_core2dbb_b_bready,0,0);
    VL_IN8(&nvdla_core2dbb_b_bid,7,0);
    VL_IN8(&nvdla_core2dbb_r_rvalid,0,0);
    VL_OUT8(&nvdla_core2dbb_r_rready,0,0);
    VL_IN8(&nvdla_core2dbb_r_rid,7,0);
    VL_IN8(&nvdla_core2dbb_r_rlast,0,0);
    VL_OUT8(&dla_intr,0,0);
    VL_IN16(&csb2nvdla_addr,15,0);
    VL_IN(&csb2nvdla_wdat,31,0);
    VL_OUT(&nvdla2csb_data,31,0);
    VL_OUT(&nvdla_core2dbb_aw_awaddr,31,0);
    VL_OUT(&nvdla_core2dbb_ar_araddr,31,0);
    VL_IN(&nvdla_pwrbus_ram_c_pd,31,0);
    VL_IN(&nvdla_pwrbus_ram_ma_pd,31,0);
    VL_IN(&nvdla_pwrbus_ram_mb_pd,31,0);
    VL_IN(&nvdla_pwrbus_ram_p_pd,31,0);
    VL_IN(&nvdla_pwrbus_ram_o_pd,31,0);
    VL_IN(&nvdla_pwrbus_ram_a_pd,31,0);
    VL_OUT64(&nvdla_core2dbb_w_wdata,63,0);
    VL_IN64(&nvdla_core2dbb_r_rdata,63,0);

    // CELLS
    // Public to allow access to /* verilator public */ items.
    // Otherwise the application code can consider these internals.
    VNV_nvdla_NV_NVDLA_partition_m* const __PVT__NV_nvdla__DOT__u_partition_ma;
    VNV_nvdla_NV_NVDLA_partition_m* const __PVT__NV_nvdla__DOT__u_partition_mb;
    VNV_nvdla_NV_NVDLA_NOCIF_DRAM_READ_IG_bpt* const __PVT__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_mcif__DOT__u_read__DOT__u_ig__DOT__u_bpt0;
    VNV_nvdla_NV_NVDLA_NOCIF_DRAM_READ_IG_bpt* const __PVT__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_mcif__DOT__u_read__DOT__u_ig__DOT__u_bpt1;
    VNV_nvdla_NV_NVDLA_NOCIF_DRAM_READ_IG_bpt* const __PVT__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_mcif__DOT__u_read__DOT__u_ig__DOT__u_bpt2;
    VNV_nvdla_NV_NVDLA_NOCIF_DRAM_READ_IG_bpt* const __PVT__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_mcif__DOT__u_read__DOT__u_ig__DOT__u_bpt3;
    VNV_nvdla_NV_NVDLA_NOCIF_DRAM_READ_IG_bpt* const __PVT__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_mcif__DOT__u_read__DOT__u_ig__DOT__u_bpt4;
    VNV_nvdla_NV_NVDLA_NOCIF_DRAM_READ_IG_bpt* const __PVT__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_mcif__DOT__u_read__DOT__u_ig__DOT__u_bpt5;
    VNV_nvdla_NV_NVDLA_NOCIF_DRAM_READ_IG_bpt* const __PVT__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_mcif__DOT__u_read__DOT__u_ig__DOT__u_bpt6;
    VNV_nvdla_NV_NVDLA_NOCIF_DRAM_READ_EG_lat_fifo* const __PVT__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_mcif__DOT__u_read__DOT__u_eg__DOT__lat_fifo0;
    VNV_nvdla_NV_NVDLA_NOCIF_DRAM_READ_EG_lat_fifo* const __PVT__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_mcif__DOT__u_read__DOT__u_eg__DOT__lat_fifo1;
    VNV_nvdla_NV_NVDLA_NOCIF_DRAM_READ_EG_lat_fifo* const __PVT__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_mcif__DOT__u_read__DOT__u_eg__DOT__lat_fifo2;
    VNV_nvdla_NV_NVDLA_NOCIF_DRAM_READ_EG_lat_fifo* const __PVT__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_mcif__DOT__u_read__DOT__u_eg__DOT__lat_fifo3;
    VNV_nvdla_NV_NVDLA_NOCIF_DRAM_READ_EG_lat_fifo* const __PVT__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_mcif__DOT__u_read__DOT__u_eg__DOT__lat_fifo4;
    VNV_nvdla_NV_NVDLA_NOCIF_DRAM_READ_EG_lat_fifo* const __PVT__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_mcif__DOT__u_read__DOT__u_eg__DOT__lat_fifo5;
    VNV_nvdla_NV_NVDLA_NOCIF_DRAM_READ_EG_lat_fifo* const __PVT__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_mcif__DOT__u_read__DOT__u_eg__DOT__lat_fifo6;
    VNV_nvdla_NV_NVDLA_NOCIF_DRAM_READ_EG_ro_fifo* const __PVT__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_mcif__DOT__u_read__DOT__u_eg__DOT__ro0_fifo0;
    VNV_nvdla_NV_NVDLA_NOCIF_DRAM_READ_EG_ro_fifo* const __PVT__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_mcif__DOT__u_read__DOT__u_eg__DOT__ro0_fifo1;
    VNV_nvdla_NV_NVDLA_NOCIF_DRAM_READ_EG_ro_fifo* const __PVT__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_mcif__DOT__u_read__DOT__u_eg__DOT__ro1_fifo0;
    VNV_nvdla_NV_NVDLA_NOCIF_DRAM_READ_EG_ro_fifo* const __PVT__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_mcif__DOT__u_read__DOT__u_eg__DOT__ro1_fifo1;
    VNV_nvdla_NV_NVDLA_NOCIF_DRAM_READ_EG_ro_fifo* const __PVT__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_mcif__DOT__u_read__DOT__u_eg__DOT__ro2_fifo0;
    VNV_nvdla_NV_NVDLA_NOCIF_DRAM_READ_EG_ro_fifo* const __PVT__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_mcif__DOT__u_read__DOT__u_eg__DOT__ro2_fifo1;
    VNV_nvdla_NV_NVDLA_NOCIF_DRAM_READ_EG_ro_fifo* const __PVT__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_mcif__DOT__u_read__DOT__u_eg__DOT__ro3_fifo0;
    VNV_nvdla_NV_NVDLA_NOCIF_DRAM_READ_EG_ro_fifo* const __PVT__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_mcif__DOT__u_read__DOT__u_eg__DOT__ro3_fifo1;
    VNV_nvdla_NV_NVDLA_NOCIF_DRAM_READ_EG_ro_fifo* const __PVT__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_mcif__DOT__u_read__DOT__u_eg__DOT__ro4_fifo0;
    VNV_nvdla_NV_NVDLA_NOCIF_DRAM_READ_EG_ro_fifo* const __PVT__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_mcif__DOT__u_read__DOT__u_eg__DOT__ro4_fifo1;
    VNV_nvdla_NV_NVDLA_NOCIF_DRAM_READ_EG_ro_fifo* const __PVT__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_mcif__DOT__u_read__DOT__u_eg__DOT__ro5_fifo0;
    VNV_nvdla_NV_NVDLA_NOCIF_DRAM_READ_EG_ro_fifo* const __PVT__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_mcif__DOT__u_read__DOT__u_eg__DOT__ro5_fifo1;
    VNV_nvdla_NV_NVDLA_NOCIF_DRAM_READ_EG_ro_fifo* const __PVT__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_mcif__DOT__u_read__DOT__u_eg__DOT__ro6_fifo0;
    VNV_nvdla_NV_NVDLA_NOCIF_DRAM_READ_EG_ro_fifo* const __PVT__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_mcif__DOT__u_read__DOT__u_eg__DOT__ro6_fifo1;
    VNV_nvdla_nv_ram_rwst_256x8* const __PVT__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_mcif__DOT__u_read__DOT__u_cq__DOT__adr_ram;
    VNV_nvdla_ScanShareSel_JTAG_reg_ext_cg__pi7* const __PVT__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_mcif__DOT__u_read__DOT__u_cq__DOT__ram__DOT__r_nv_ram_rws_256x7__DOT__testInst_Wa_reg_w0;
    VNV_nvdla_ScanShareSel_JTAG_reg_ext_cg__pi7* const __PVT__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_mcif__DOT__u_read__DOT__u_cq__DOT__ram__DOT__r_nv_ram_rws_256x7__DOT__testInst_Ra_reg_r0;
    VNV_nvdla_ScanShareSel_JTAG_reg_ext_cg__pi19* const __PVT__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_mcif__DOT__u_read__DOT__u_cq__DOT__ram__DOT__r_nv_ram_rws_256x7__DOT__testInst_Data_reg_r0;
    VNV_nvdla_NV_NVDLA_NOCIF_DRAM_WRITE_IG_bpt* const __PVT__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_mcif__DOT__u_write__DOT__u_ig__DOT__u_bpt0;
    VNV_nvdla_NV_NVDLA_NOCIF_DRAM_WRITE_IG_bpt* const __PVT__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_mcif__DOT__u_write__DOT__u_ig__DOT__u_bpt1;
    VNV_nvdla_NV_NVDLA_NOCIF_DRAM_WRITE_IG_bpt* const __PVT__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_mcif__DOT__u_write__DOT__u_ig__DOT__u_bpt2;
    VNV_nvdla_nv_ram_rwst_256x8* const __PVT__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_mcif__DOT__u_write__DOT__u_cq__DOT__adr_ram;
    VNV_nvdla_ScanShareSel_JTAG_reg_ext_cg__pi7* const __PVT__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_mcif__DOT__u_write__DOT__u_cq__DOT__ram__DOT__r_nv_ram_rws_256x3__DOT__testInst_Wa_reg_w0;
    VNV_nvdla_ScanShareSel_JTAG_reg_ext_cg__pi7* const __PVT__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_mcif__DOT__u_write__DOT__u_cq__DOT__ram__DOT__r_nv_ram_rws_256x3__DOT__testInst_Ra_reg_r0;
    VNV_nvdla_NV_NVDLA_CDP_RDMA_ro_fifo* const __PVT__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_cdp__DOT__u_rdma__DOT__u_eg__DOT__u_ro0_fifo;
    VNV_nvdla_NV_NVDLA_CDP_RDMA_ro_fifo* const __PVT__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_cdp__DOT__u_rdma__DOT__u_eg__DOT__u_ro1_fifo;
    VNV_nvdla_NV_NVDLA_CDP_RDMA_ro_fifo* const __PVT__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_cdp__DOT__u_rdma__DOT__u_eg__DOT__u_ro2_fifo;
    VNV_nvdla_NV_NVDLA_CDP_RDMA_ro_fifo* const __PVT__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_cdp__DOT__u_rdma__DOT__u_eg__DOT__u_ro3_fifo;
    VNV_nvdla_NV_NVDLA_CDP_RDMA_ro_fifo* const __PVT__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_cdp__DOT__u_rdma__DOT__u_eg__DOT__u_ro4_fifo;
    VNV_nvdla_NV_NVDLA_CDP_RDMA_ro_fifo* const __PVT__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_cdp__DOT__u_rdma__DOT__u_eg__DOT__u_ro5_fifo;
    VNV_nvdla_NV_NVDLA_CDP_RDMA_ro_fifo* const __PVT__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_cdp__DOT__u_rdma__DOT__u_eg__DOT__u_ro6_fifo;
    VNV_nvdla_NV_NVDLA_CDP_RDMA_ro_fifo* const __PVT__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_cdp__DOT__u_rdma__DOT__u_eg__DOT__u_ro7_fifo;
    VNV_nvdla_nv_ram_rwsp_61x65__Fz2* const __PVT__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_cdp__DOT__u_rdma__DOT__u_eg__DOT__u_lat_fifo__DOT__ram;
    VNV_nvdla_NV_NVDLA_CDP_WDMA_dat_fifo* const __PVT__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_cdp__DOT__u_wdma__DOT__u_dat0_fifo0;
    VNV_nvdla_NV_NVDLA_CDP_WDMA_dat_fifo* const __PVT__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_cdp__DOT__u_wdma__DOT__u_dat0_fifo1;
    VNV_nvdla_NV_NVDLA_CDP_WDMA_dat_fifo* const __PVT__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_cdp__DOT__u_wdma__DOT__u_dat0_fifo2;
    VNV_nvdla_NV_NVDLA_CDP_WDMA_dat_fifo* const __PVT__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_cdp__DOT__u_wdma__DOT__u_dat0_fifo3;
    VNV_nvdla_NV_NVDLA_CDP_WDMA_dat_fifo* const __PVT__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_cdp__DOT__u_wdma__DOT__u_dat0_fifo4;
    VNV_nvdla_NV_NVDLA_CDP_WDMA_dat_fifo* const __PVT__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_cdp__DOT__u_wdma__DOT__u_dat0_fifo5;
    VNV_nvdla_NV_NVDLA_CDP_WDMA_dat_fifo* const __PVT__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_cdp__DOT__u_wdma__DOT__u_dat0_fifo6;
    VNV_nvdla_NV_NVDLA_CDP_WDMA_dat_fifo* const __PVT__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_cdp__DOT__u_wdma__DOT__u_dat0_fifo7;
    VNV_nvdla_ScanShareSel_JTAG_reg_ext_cg__pi19* const __PVT__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_cdp__DOT__u_dp__DOT__u_NV_NVDLA_CDP_DP_syncfifo__DOT__u_data_sync_fifo__DOT__ram__DOT__r_nv_ram_rwsthp_80x9__DOT__testInst_Wa_reg_w0;
    VNV_nvdla_ScanShareSel_JTAG_reg_ext_cg__pi19* const __PVT__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_cdp__DOT__u_dp__DOT__u_NV_NVDLA_CDP_DP_syncfifo__DOT__u_data_sync_fifo__DOT__ram__DOT__r_nv_ram_rwsthp_80x9__DOT__testInst_Ra_reg_r0;
    VNV_nvdla_ScanShareSel_JTAG_reg_ext_cg__pi19* const __PVT__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_cdp__DOT__u_dp__DOT__u_NV_NVDLA_CDP_DP_syncfifo__DOT__u_info_sync_fifo__DOT__ram__DOT__r_nv_ram_rwsthp_80x15__DOT__testInst_Wa_reg_w0;
    VNV_nvdla_ScanShareSel_JTAG_reg_ext_cg__pi19* const __PVT__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_cdp__DOT__u_dp__DOT__u_NV_NVDLA_CDP_DP_syncfifo__DOT__u_info_sync_fifo__DOT__ram__DOT__r_nv_ram_rwsthp_80x15__DOT__testInst_Ra_reg_r0;
    VNV_nvdla_NV_NVDLA_PDP_RDMA_ro_fifo* const __PVT__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_pdp__DOT__u_rdma__DOT__u_eg__DOT__u_ro0_fifo;
    VNV_nvdla_NV_NVDLA_PDP_RDMA_ro_fifo* const __PVT__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_pdp__DOT__u_rdma__DOT__u_eg__DOT__u_ro1_fifo;
    VNV_nvdla_NV_NVDLA_PDP_RDMA_ro_fifo* const __PVT__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_pdp__DOT__u_rdma__DOT__u_eg__DOT__u_ro2_fifo;
    VNV_nvdla_NV_NVDLA_PDP_RDMA_ro_fifo* const __PVT__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_pdp__DOT__u_rdma__DOT__u_eg__DOT__u_ro3_fifo;
    VNV_nvdla_NV_NVDLA_PDP_RDMA_ro_fifo* const __PVT__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_pdp__DOT__u_rdma__DOT__u_eg__DOT__u_ro4_fifo;
    VNV_nvdla_NV_NVDLA_PDP_RDMA_ro_fifo* const __PVT__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_pdp__DOT__u_rdma__DOT__u_eg__DOT__u_ro5_fifo;
    VNV_nvdla_NV_NVDLA_PDP_RDMA_ro_fifo* const __PVT__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_pdp__DOT__u_rdma__DOT__u_eg__DOT__u_ro6_fifo;
    VNV_nvdla_NV_NVDLA_PDP_RDMA_ro_fifo* const __PVT__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_pdp__DOT__u_rdma__DOT__u_eg__DOT__u_ro7_fifo;
    VNV_nvdla_nv_ram_rwsp_61x65__Fz2* const __PVT__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_pdp__DOT__u_rdma__DOT__u_eg__DOT__u_lat_fifo__DOT__ram;
    VNV_nvdla_NV_NVDLA_PDP_WDMA_DAT_fifo* const __PVT__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_pdp__DOT__u_wdma__DOT__u_dat__DOT__u_dat0_fifo0;
    VNV_nvdla_NV_NVDLA_PDP_WDMA_DAT_fifo* const __PVT__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_pdp__DOT__u_wdma__DOT__u_dat__DOT__u_dat0_fifo1;
    VNV_nvdla_NV_NVDLA_PDP_WDMA_DAT_fifo* const __PVT__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_pdp__DOT__u_wdma__DOT__u_dat__DOT__u_dat0_fifo2;
    VNV_nvdla_NV_NVDLA_PDP_WDMA_DAT_fifo* const __PVT__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_pdp__DOT__u_wdma__DOT__u_dat__DOT__u_dat0_fifo3;
    VNV_nvdla_NV_NVDLA_PDP_WDMA_DAT_fifo* const __PVT__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_pdp__DOT__u_wdma__DOT__u_dat__DOT__u_dat0_fifo4;
    VNV_nvdla_NV_NVDLA_PDP_WDMA_DAT_fifo* const __PVT__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_pdp__DOT__u_wdma__DOT__u_dat__DOT__u_dat0_fifo5;
    VNV_nvdla_NV_NVDLA_PDP_WDMA_DAT_fifo* const __PVT__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_pdp__DOT__u_wdma__DOT__u_dat__DOT__u_dat0_fifo6;
    VNV_nvdla_NV_NVDLA_PDP_WDMA_DAT_fifo* const __PVT__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_pdp__DOT__u_wdma__DOT__u_dat__DOT__u_dat0_fifo7;
    VNV_nvdla_NV_NVDLA_PDP_CORE_unit1d* const __PVT__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_pdp__DOT__u_core__DOT__u_cal1d__DOT__unit1d_0;
    VNV_nvdla_NV_NVDLA_PDP_CORE_unit1d* const __PVT__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_pdp__DOT__u_core__DOT__u_cal1d__DOT__unit1d_1;
    VNV_nvdla_NV_NVDLA_PDP_CORE_unit1d* const __PVT__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_pdp__DOT__u_core__DOT__u_cal1d__DOT__unit1d_2;
    VNV_nvdla_NV_NVDLA_PDP_CORE_unit1d* const __PVT__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_pdp__DOT__u_core__DOT__u_cal1d__DOT__unit1d_3;
    VNV_nvdla_NV_NVDLA_PDP_CORE_unit1d* const __PVT__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_pdp__DOT__u_core__DOT__u_cal1d__DOT__unit1d_4;
    VNV_nvdla_NV_NVDLA_PDP_CORE_unit1d* const __PVT__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_pdp__DOT__u_core__DOT__u_cal1d__DOT__unit1d_5;
    VNV_nvdla_NV_NVDLA_PDP_CORE_unit1d* const __PVT__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_pdp__DOT__u_core__DOT__u_cal1d__DOT__unit1d_6;
    VNV_nvdla_NV_NVDLA_PDP_CORE_unit1d* const __PVT__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_pdp__DOT__u_core__DOT__u_cal1d__DOT__unit1d_7;
    VNV_nvdla_nv_ram_rws_128x18* const __PVT__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_pdp__DOT__u_core__DOT__u_cal2d__DOT__bank0_uram_0;
    VNV_nvdla_nv_ram_rws_128x18* const __PVT__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_pdp__DOT__u_core__DOT__u_cal2d__DOT__bank1_uram_0;
    VNV_nvdla_nv_ram_rws_128x18* const __PVT__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_pdp__DOT__u_core__DOT__u_cal2d__DOT__bank2_uram_0;
    VNV_nvdla_nv_ram_rws_128x18* const __PVT__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_pdp__DOT__u_core__DOT__u_cal2d__DOT__bank3_uram_0;
    VNV_nvdla_nv_ram_rws_128x18* const __PVT__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_pdp__DOT__u_core__DOT__u_cal2d__DOT__bank4_uram_0;
    VNV_nvdla_nv_ram_rws_128x18* const __PVT__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_pdp__DOT__u_core__DOT__u_cal2d__DOT__bank5_uram_0;
    VNV_nvdla_nv_ram_rws_128x18* const __PVT__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_pdp__DOT__u_core__DOT__u_cal2d__DOT__bank6_uram_0;
    VNV_nvdla_nv_ram_rws_128x18* const __PVT__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_pdp__DOT__u_core__DOT__u_cal2d__DOT__bank7_uram_0;
    VNV_nvdla_NV_NVDLA_CDMA_dual_reg* const __PVT__NV_nvdla__DOT__u_partition_c__DOT__u_NV_NVDLA_cdma__DOT__u_regfile__DOT__u_dual_reg_d0;
    VNV_nvdla_NV_NVDLA_CDMA_dual_reg* const __PVT__NV_nvdla__DOT__u_partition_c__DOT__u_NV_NVDLA_cdma__DOT__u_regfile__DOT__u_dual_reg_d1;
    VNV_nvdla_ScanShareSel_JTAG_reg_ext_cg__pi22* const __PVT__NV_nvdla__DOT__u_partition_c__DOT__u_NV_NVDLA_cdma__DOT__u_wt__DOT__u_8atmm_fifo__DOT__ram__DOT__r_nv_ram_rwsp_8x65__DOT__testInst_Data_reg_r0;
    VNV_nvdla_nv_ram_rwsp_128x6__Fz2* const __PVT__NV_nvdla__DOT__u_partition_c__DOT__u_NV_NVDLA_cdma__DOT__u_wt__DOT__u_fifo__DOT__ram;
    VNV_nvdla_nv_ram_rwsp_128x6__Fz2* const __PVT__NV_nvdla__DOT__u_partition_c__DOT__u_NV_NVDLA_cdma__DOT__u_dc__DOT__u_fifo__DOT__ram;
    VNV_nvdla_ScanShareSel_JTAG_reg_ext_cg__pi19* const __PVT__NV_nvdla__DOT__u_partition_c__DOT__u_NV_NVDLA_cdma__DOT__u_img__DOT__u_sg__DOT__u_NV_NVDLA_CDMA_IMG_fifo__DOT__ram__DOT__r_nv_ram_rwsp_128x11__DOT__testInst_Wa_reg_w0;
    VNV_nvdla_ScanShareSel_JTAG_reg_ext_cg__pi19* const __PVT__NV_nvdla__DOT__u_partition_c__DOT__u_NV_NVDLA_cdma__DOT__u_img__DOT__u_sg__DOT__u_NV_NVDLA_CDMA_IMG_fifo__DOT__ram__DOT__r_nv_ram_rwsp_128x11__DOT__testInst_Ra_reg_r0;
    VNV_nvdla_NV_NVDLA_CDMA_CVT_cell* const __PVT__NV_nvdla__DOT__u_partition_c__DOT__u_NV_NVDLA_cdma__DOT__u_cvt__DOT__u_cell_0;
    VNV_nvdla_NV_NVDLA_CDMA_CVT_cell* const __PVT__NV_nvdla__DOT__u_partition_c__DOT__u_NV_NVDLA_cdma__DOT__u_cvt__DOT__u_cell_1;
    VNV_nvdla_NV_NVDLA_CDMA_CVT_cell* const __PVT__NV_nvdla__DOT__u_partition_c__DOT__u_NV_NVDLA_cdma__DOT__u_cvt__DOT__u_cell_2;
    VNV_nvdla_NV_NVDLA_CDMA_CVT_cell* const __PVT__NV_nvdla__DOT__u_partition_c__DOT__u_NV_NVDLA_cdma__DOT__u_cvt__DOT__u_cell_3;
    VNV_nvdla_NV_NVDLA_CDMA_CVT_cell* const __PVT__NV_nvdla__DOT__u_partition_c__DOT__u_NV_NVDLA_cdma__DOT__u_cvt__DOT__u_cell_4;
    VNV_nvdla_NV_NVDLA_CDMA_CVT_cell* const __PVT__NV_nvdla__DOT__u_partition_c__DOT__u_NV_NVDLA_cdma__DOT__u_cvt__DOT__u_cell_5;
    VNV_nvdla_NV_NVDLA_CDMA_CVT_cell* const __PVT__NV_nvdla__DOT__u_partition_c__DOT__u_NV_NVDLA_cdma__DOT__u_cvt__DOT__u_cell_6;
    VNV_nvdla_NV_NVDLA_CDMA_CVT_cell* const __PVT__NV_nvdla__DOT__u_partition_c__DOT__u_NV_NVDLA_cdma__DOT__u_cvt__DOT__u_cell_7;
    VNV_nvdla_nv_ram_rws_16x64* const __PVT__NV_nvdla__DOT__u_partition_c__DOT__u_NV_NVDLA_cdma__DOT__u_shared_buffer__DOT__u_shared_buffer_00;
    VNV_nvdla_nv_ram_rws_16x64* const __PVT__NV_nvdla__DOT__u_partition_c__DOT__u_NV_NVDLA_cdma__DOT__u_shared_buffer__DOT__u_shared_buffer_01;
    VNV_nvdla_nv_ram_rws_16x64* const __PVT__NV_nvdla__DOT__u_partition_c__DOT__u_NV_NVDLA_cdma__DOT__u_shared_buffer__DOT__u_shared_buffer_02;
    VNV_nvdla_nv_ram_rws_16x64* const __PVT__NV_nvdla__DOT__u_partition_c__DOT__u_NV_NVDLA_cdma__DOT__u_shared_buffer__DOT__u_shared_buffer_03;
    VNV_nvdla_nv_ram_rws_16x64* const __PVT__NV_nvdla__DOT__u_partition_c__DOT__u_NV_NVDLA_cdma__DOT__u_shared_buffer__DOT__u_shared_buffer_04;
    VNV_nvdla_nv_ram_rws_16x64* const __PVT__NV_nvdla__DOT__u_partition_c__DOT__u_NV_NVDLA_cdma__DOT__u_shared_buffer__DOT__u_shared_buffer_05;
    VNV_nvdla_nv_ram_rws_16x64* const __PVT__NV_nvdla__DOT__u_partition_c__DOT__u_NV_NVDLA_cdma__DOT__u_shared_buffer__DOT__u_shared_buffer_06;
    VNV_nvdla_nv_ram_rws_16x64* const __PVT__NV_nvdla__DOT__u_partition_c__DOT__u_NV_NVDLA_cdma__DOT__u_shared_buffer__DOT__u_shared_buffer_07;
    VNV_nvdla_nv_ram_rws_16x64* const __PVT__NV_nvdla__DOT__u_partition_c__DOT__u_NV_NVDLA_cdma__DOT__u_shared_buffer__DOT__u_shared_buffer_08;
    VNV_nvdla_nv_ram_rws_16x64* const __PVT__NV_nvdla__DOT__u_partition_c__DOT__u_NV_NVDLA_cdma__DOT__u_shared_buffer__DOT__u_shared_buffer_09;
    VNV_nvdla_nv_ram_rws_16x64* const __PVT__NV_nvdla__DOT__u_partition_c__DOT__u_NV_NVDLA_cdma__DOT__u_shared_buffer__DOT__u_shared_buffer_10;
    VNV_nvdla_nv_ram_rws_16x64* const __PVT__NV_nvdla__DOT__u_partition_c__DOT__u_NV_NVDLA_cdma__DOT__u_shared_buffer__DOT__u_shared_buffer_11;
    VNV_nvdla_nv_ram_rws_16x64* const __PVT__NV_nvdla__DOT__u_partition_c__DOT__u_NV_NVDLA_cdma__DOT__u_shared_buffer__DOT__u_shared_buffer_12;
    VNV_nvdla_nv_ram_rws_16x64* const __PVT__NV_nvdla__DOT__u_partition_c__DOT__u_NV_NVDLA_cdma__DOT__u_shared_buffer__DOT__u_shared_buffer_13;
    VNV_nvdla_nv_ram_rws_16x64* const __PVT__NV_nvdla__DOT__u_partition_c__DOT__u_NV_NVDLA_cdma__DOT__u_shared_buffer__DOT__u_shared_buffer_14;
    VNV_nvdla_nv_ram_rws_16x64* const __PVT__NV_nvdla__DOT__u_partition_c__DOT__u_NV_NVDLA_cdma__DOT__u_shared_buffer__DOT__u_shared_buffer_15;
    VNV_nvdla_nv_ram_rws_256x64* const __PVT__NV_nvdla__DOT__u_partition_c__DOT__u_NV_NVDLA_cbuf__DOT__u_cbuf_ram_bank0_ram0;
    VNV_nvdla_nv_ram_rws_256x64* const __PVT__NV_nvdla__DOT__u_partition_c__DOT__u_NV_NVDLA_cbuf__DOT__u_cbuf_ram_bank0_ram1;
    VNV_nvdla_nv_ram_rws_256x64* const __PVT__NV_nvdla__DOT__u_partition_c__DOT__u_NV_NVDLA_cbuf__DOT__u_cbuf_ram_bank1_ram0;
    VNV_nvdla_nv_ram_rws_256x64* const __PVT__NV_nvdla__DOT__u_partition_c__DOT__u_NV_NVDLA_cbuf__DOT__u_cbuf_ram_bank1_ram1;
    VNV_nvdla_nv_ram_rws_256x64* const __PVT__NV_nvdla__DOT__u_partition_c__DOT__u_NV_NVDLA_cbuf__DOT__u_cbuf_ram_bank2_ram0;
    VNV_nvdla_nv_ram_rws_256x64* const __PVT__NV_nvdla__DOT__u_partition_c__DOT__u_NV_NVDLA_cbuf__DOT__u_cbuf_ram_bank2_ram1;
    VNV_nvdla_nv_ram_rws_256x64* const __PVT__NV_nvdla__DOT__u_partition_c__DOT__u_NV_NVDLA_cbuf__DOT__u_cbuf_ram_bank3_ram0;
    VNV_nvdla_nv_ram_rws_256x64* const __PVT__NV_nvdla__DOT__u_partition_c__DOT__u_NV_NVDLA_cbuf__DOT__u_cbuf_ram_bank3_ram1;
    VNV_nvdla_nv_ram_rws_256x64* const __PVT__NV_nvdla__DOT__u_partition_c__DOT__u_NV_NVDLA_cbuf__DOT__u_cbuf_ram_bank4_ram0;
    VNV_nvdla_nv_ram_rws_256x64* const __PVT__NV_nvdla__DOT__u_partition_c__DOT__u_NV_NVDLA_cbuf__DOT__u_cbuf_ram_bank4_ram1;
    VNV_nvdla_nv_ram_rws_256x64* const __PVT__NV_nvdla__DOT__u_partition_c__DOT__u_NV_NVDLA_cbuf__DOT__u_cbuf_ram_bank5_ram0;
    VNV_nvdla_nv_ram_rws_256x64* const __PVT__NV_nvdla__DOT__u_partition_c__DOT__u_NV_NVDLA_cbuf__DOT__u_cbuf_ram_bank5_ram1;
    VNV_nvdla_nv_ram_rws_256x64* const __PVT__NV_nvdla__DOT__u_partition_c__DOT__u_NV_NVDLA_cbuf__DOT__u_cbuf_ram_bank6_ram0;
    VNV_nvdla_nv_ram_rws_256x64* const __PVT__NV_nvdla__DOT__u_partition_c__DOT__u_NV_NVDLA_cbuf__DOT__u_cbuf_ram_bank6_ram1;
    VNV_nvdla_nv_ram_rws_256x64* const __PVT__NV_nvdla__DOT__u_partition_c__DOT__u_NV_NVDLA_cbuf__DOT__u_cbuf_ram_bank7_ram0;
    VNV_nvdla_nv_ram_rws_256x64* const __PVT__NV_nvdla__DOT__u_partition_c__DOT__u_NV_NVDLA_cbuf__DOT__u_cbuf_ram_bank7_ram1;
    VNV_nvdla_nv_ram_rws_256x64* const __PVT__NV_nvdla__DOT__u_partition_c__DOT__u_NV_NVDLA_cbuf__DOT__u_cbuf_ram_bank8_ram0;
    VNV_nvdla_nv_ram_rws_256x64* const __PVT__NV_nvdla__DOT__u_partition_c__DOT__u_NV_NVDLA_cbuf__DOT__u_cbuf_ram_bank8_ram1;
    VNV_nvdla_nv_ram_rws_256x64* const __PVT__NV_nvdla__DOT__u_partition_c__DOT__u_NV_NVDLA_cbuf__DOT__u_cbuf_ram_bank9_ram0;
    VNV_nvdla_nv_ram_rws_256x64* const __PVT__NV_nvdla__DOT__u_partition_c__DOT__u_NV_NVDLA_cbuf__DOT__u_cbuf_ram_bank9_ram1;
    VNV_nvdla_nv_ram_rws_256x64* const __PVT__NV_nvdla__DOT__u_partition_c__DOT__u_NV_NVDLA_cbuf__DOT__u_cbuf_ram_bank10_ram0;
    VNV_nvdla_nv_ram_rws_256x64* const __PVT__NV_nvdla__DOT__u_partition_c__DOT__u_NV_NVDLA_cbuf__DOT__u_cbuf_ram_bank10_ram1;
    VNV_nvdla_nv_ram_rws_256x64* const __PVT__NV_nvdla__DOT__u_partition_c__DOT__u_NV_NVDLA_cbuf__DOT__u_cbuf_ram_bank11_ram0;
    VNV_nvdla_nv_ram_rws_256x64* const __PVT__NV_nvdla__DOT__u_partition_c__DOT__u_NV_NVDLA_cbuf__DOT__u_cbuf_ram_bank11_ram1;
    VNV_nvdla_nv_ram_rws_256x64* const __PVT__NV_nvdla__DOT__u_partition_c__DOT__u_NV_NVDLA_cbuf__DOT__u_cbuf_ram_bank12_ram0;
    VNV_nvdla_nv_ram_rws_256x64* const __PVT__NV_nvdla__DOT__u_partition_c__DOT__u_NV_NVDLA_cbuf__DOT__u_cbuf_ram_bank12_ram1;
    VNV_nvdla_nv_ram_rws_256x64* const __PVT__NV_nvdla__DOT__u_partition_c__DOT__u_NV_NVDLA_cbuf__DOT__u_cbuf_ram_bank13_ram0;
    VNV_nvdla_nv_ram_rws_256x64* const __PVT__NV_nvdla__DOT__u_partition_c__DOT__u_NV_NVDLA_cbuf__DOT__u_cbuf_ram_bank13_ram1;
    VNV_nvdla_nv_ram_rws_256x64* const __PVT__NV_nvdla__DOT__u_partition_c__DOT__u_NV_NVDLA_cbuf__DOT__u_cbuf_ram_bank14_ram0;
    VNV_nvdla_nv_ram_rws_256x64* const __PVT__NV_nvdla__DOT__u_partition_c__DOT__u_NV_NVDLA_cbuf__DOT__u_cbuf_ram_bank14_ram1;
    VNV_nvdla_nv_ram_rws_256x64* const __PVT__NV_nvdla__DOT__u_partition_c__DOT__u_NV_NVDLA_cbuf__DOT__u_cbuf_ram_bank15_ram0;
    VNV_nvdla_nv_ram_rws_256x64* const __PVT__NV_nvdla__DOT__u_partition_c__DOT__u_NV_NVDLA_cbuf__DOT__u_cbuf_ram_bank15_ram1;
    VNV_nvdla_nv_ram_rws_256x64* const __PVT__NV_nvdla__DOT__u_partition_c__DOT__u_NV_NVDLA_cbuf__DOT__u_cbuf_ram_bank16_ram0;
    VNV_nvdla_nv_ram_rws_256x64* const __PVT__NV_nvdla__DOT__u_partition_c__DOT__u_NV_NVDLA_cbuf__DOT__u_cbuf_ram_bank16_ram1;
    VNV_nvdla_nv_ram_rws_256x64* const __PVT__NV_nvdla__DOT__u_partition_c__DOT__u_NV_NVDLA_cbuf__DOT__u_cbuf_ram_bank17_ram0;
    VNV_nvdla_nv_ram_rws_256x64* const __PVT__NV_nvdla__DOT__u_partition_c__DOT__u_NV_NVDLA_cbuf__DOT__u_cbuf_ram_bank17_ram1;
    VNV_nvdla_nv_ram_rws_256x64* const __PVT__NV_nvdla__DOT__u_partition_c__DOT__u_NV_NVDLA_cbuf__DOT__u_cbuf_ram_bank18_ram0;
    VNV_nvdla_nv_ram_rws_256x64* const __PVT__NV_nvdla__DOT__u_partition_c__DOT__u_NV_NVDLA_cbuf__DOT__u_cbuf_ram_bank18_ram1;
    VNV_nvdla_nv_ram_rws_256x64* const __PVT__NV_nvdla__DOT__u_partition_c__DOT__u_NV_NVDLA_cbuf__DOT__u_cbuf_ram_bank19_ram0;
    VNV_nvdla_nv_ram_rws_256x64* const __PVT__NV_nvdla__DOT__u_partition_c__DOT__u_NV_NVDLA_cbuf__DOT__u_cbuf_ram_bank19_ram1;
    VNV_nvdla_nv_ram_rws_256x64* const __PVT__NV_nvdla__DOT__u_partition_c__DOT__u_NV_NVDLA_cbuf__DOT__u_cbuf_ram_bank20_ram0;
    VNV_nvdla_nv_ram_rws_256x64* const __PVT__NV_nvdla__DOT__u_partition_c__DOT__u_NV_NVDLA_cbuf__DOT__u_cbuf_ram_bank20_ram1;
    VNV_nvdla_nv_ram_rws_256x64* const __PVT__NV_nvdla__DOT__u_partition_c__DOT__u_NV_NVDLA_cbuf__DOT__u_cbuf_ram_bank21_ram0;
    VNV_nvdla_nv_ram_rws_256x64* const __PVT__NV_nvdla__DOT__u_partition_c__DOT__u_NV_NVDLA_cbuf__DOT__u_cbuf_ram_bank21_ram1;
    VNV_nvdla_nv_ram_rws_256x64* const __PVT__NV_nvdla__DOT__u_partition_c__DOT__u_NV_NVDLA_cbuf__DOT__u_cbuf_ram_bank22_ram0;
    VNV_nvdla_nv_ram_rws_256x64* const __PVT__NV_nvdla__DOT__u_partition_c__DOT__u_NV_NVDLA_cbuf__DOT__u_cbuf_ram_bank22_ram1;
    VNV_nvdla_nv_ram_rws_256x64* const __PVT__NV_nvdla__DOT__u_partition_c__DOT__u_NV_NVDLA_cbuf__DOT__u_cbuf_ram_bank23_ram0;
    VNV_nvdla_nv_ram_rws_256x64* const __PVT__NV_nvdla__DOT__u_partition_c__DOT__u_NV_NVDLA_cbuf__DOT__u_cbuf_ram_bank23_ram1;
    VNV_nvdla_nv_ram_rws_256x64* const __PVT__NV_nvdla__DOT__u_partition_c__DOT__u_NV_NVDLA_cbuf__DOT__u_cbuf_ram_bank24_ram0;
    VNV_nvdla_nv_ram_rws_256x64* const __PVT__NV_nvdla__DOT__u_partition_c__DOT__u_NV_NVDLA_cbuf__DOT__u_cbuf_ram_bank24_ram1;
    VNV_nvdla_nv_ram_rws_256x64* const __PVT__NV_nvdla__DOT__u_partition_c__DOT__u_NV_NVDLA_cbuf__DOT__u_cbuf_ram_bank25_ram0;
    VNV_nvdla_nv_ram_rws_256x64* const __PVT__NV_nvdla__DOT__u_partition_c__DOT__u_NV_NVDLA_cbuf__DOT__u_cbuf_ram_bank25_ram1;
    VNV_nvdla_nv_ram_rws_256x64* const __PVT__NV_nvdla__DOT__u_partition_c__DOT__u_NV_NVDLA_cbuf__DOT__u_cbuf_ram_bank26_ram0;
    VNV_nvdla_nv_ram_rws_256x64* const __PVT__NV_nvdla__DOT__u_partition_c__DOT__u_NV_NVDLA_cbuf__DOT__u_cbuf_ram_bank26_ram1;
    VNV_nvdla_nv_ram_rws_256x64* const __PVT__NV_nvdla__DOT__u_partition_c__DOT__u_NV_NVDLA_cbuf__DOT__u_cbuf_ram_bank27_ram0;
    VNV_nvdla_nv_ram_rws_256x64* const __PVT__NV_nvdla__DOT__u_partition_c__DOT__u_NV_NVDLA_cbuf__DOT__u_cbuf_ram_bank27_ram1;
    VNV_nvdla_nv_ram_rws_256x64* const __PVT__NV_nvdla__DOT__u_partition_c__DOT__u_NV_NVDLA_cbuf__DOT__u_cbuf_ram_bank28_ram0;
    VNV_nvdla_nv_ram_rws_256x64* const __PVT__NV_nvdla__DOT__u_partition_c__DOT__u_NV_NVDLA_cbuf__DOT__u_cbuf_ram_bank28_ram1;
    VNV_nvdla_nv_ram_rws_256x64* const __PVT__NV_nvdla__DOT__u_partition_c__DOT__u_NV_NVDLA_cbuf__DOT__u_cbuf_ram_bank29_ram0;
    VNV_nvdla_nv_ram_rws_256x64* const __PVT__NV_nvdla__DOT__u_partition_c__DOT__u_NV_NVDLA_cbuf__DOT__u_cbuf_ram_bank29_ram1;
    VNV_nvdla_nv_ram_rws_256x64* const __PVT__NV_nvdla__DOT__u_partition_c__DOT__u_NV_NVDLA_cbuf__DOT__u_cbuf_ram_bank30_ram0;
    VNV_nvdla_nv_ram_rws_256x64* const __PVT__NV_nvdla__DOT__u_partition_c__DOT__u_NV_NVDLA_cbuf__DOT__u_cbuf_ram_bank30_ram1;
    VNV_nvdla_nv_ram_rws_256x64* const __PVT__NV_nvdla__DOT__u_partition_c__DOT__u_NV_NVDLA_cbuf__DOT__u_cbuf_ram_bank31_ram0;
    VNV_nvdla_nv_ram_rws_256x64* const __PVT__NV_nvdla__DOT__u_partition_c__DOT__u_NV_NVDLA_cbuf__DOT__u_cbuf_ram_bank31_ram1;
    VNV_nvdla_ScanShareSel_JTAG_reg_ext_cg__pi13* const __PVT__NV_nvdla__DOT__u_partition_a__DOT__u_NV_NVDLA_cacc__DOT__u_assembly_buffer__DOT__u_accu_abuf_0__DOT__r_nv_ram_rws_16x272__DOT__testInst_Data_reg_r0_271_16;
    VNV_nvdla_ScanShareSel_JTAG_reg_ext_cg__pi13* const __PVT__NV_nvdla__DOT__u_partition_a__DOT__u_NV_NVDLA_cacc__DOT__u_delivery_buffer__DOT__u_accu_dbuf__DOT__r_nv_ram_rws_16x256__DOT__testInst_Data_reg_r0;
    VNV_nvdla_ScanShareSel_JTAG_reg_ext_cg__pi19* const __PVT__NV_nvdla__DOT__u_partition_p__DOT__u_NV_NVDLA_sdp__DOT__u_rdma__DOT__u_mrdma__DOT__u_cq__DOT__ram__DOT__r_nv_ram_rwsp_80x14__DOT__testInst_Wa_reg_w0;
    VNV_nvdla_ScanShareSel_JTAG_reg_ext_cg__pi19* const __PVT__NV_nvdla__DOT__u_partition_p__DOT__u_NV_NVDLA_sdp__DOT__u_rdma__DOT__u_mrdma__DOT__u_cq__DOT__ram__DOT__r_nv_ram_rwsp_80x14__DOT__testInst_Ra_reg_r0;
    VNV_nvdla_ScanShareSel_JTAG_reg_ext_cg__pi19* const __PVT__NV_nvdla__DOT__u_partition_p__DOT__u_NV_NVDLA_sdp__DOT__u_rdma__DOT__u_mrdma__DOT__u_eg__DOT__u_din__DOT__u_lat_fifo__DOT__ram__DOT__r_nv_ram_rwsp_80x65__DOT__testInst_Wa_reg_w0;
    VNV_nvdla_ScanShareSel_JTAG_reg_ext_cg__pi19* const __PVT__NV_nvdla__DOT__u_partition_p__DOT__u_NV_NVDLA_sdp__DOT__u_rdma__DOT__u_mrdma__DOT__u_eg__DOT__u_din__DOT__u_lat_fifo__DOT__ram__DOT__r_nv_ram_rwsp_80x65__DOT__testInst_Ra_reg_r0;
    VNV_nvdla_ScanShareSel_JTAG_reg_ext_cg__pi22* const __PVT__NV_nvdla__DOT__u_partition_p__DOT__u_NV_NVDLA_sdp__DOT__u_rdma__DOT__u_mrdma__DOT__u_eg__DOT__u_din__DOT__u_lat_fifo__DOT__ram__DOT__r_nv_ram_rwsp_80x65__DOT__testInst_Data_reg_r0;
    VNV_nvdla_nv_ram_rwsp_160x16__Fz2* const __PVT__NV_nvdla__DOT__u_partition_p__DOT__u_NV_NVDLA_sdp__DOT__u_rdma__DOT__u_brdma__DOT__u_cq__DOT__ram;
    VNV_nvdla_NV_NVDLA_SDP_RDMA_EG_ro* const __PVT__NV_nvdla__DOT__u_partition_p__DOT__u_NV_NVDLA_sdp__DOT__u_rdma__DOT__u_brdma__DOT__u_eg__DOT__u_alu;
    VNV_nvdla_NV_NVDLA_SDP_RDMA_EG_ro* const __PVT__NV_nvdla__DOT__u_partition_p__DOT__u_NV_NVDLA_sdp__DOT__u_rdma__DOT__u_brdma__DOT__u_eg__DOT__u_mul;
    VNV_nvdla_nv_ram_rwsp_160x65__Fz2* const __PVT__NV_nvdla__DOT__u_partition_p__DOT__u_NV_NVDLA_sdp__DOT__u_rdma__DOT__u_brdma__DOT__u_lat_fifo__DOT__ram;
    VNV_nvdla_nv_ram_rwsp_160x16__Fz2* const __PVT__NV_nvdla__DOT__u_partition_p__DOT__u_NV_NVDLA_sdp__DOT__u_rdma__DOT__u_nrdma__DOT__u_cq__DOT__ram;
    VNV_nvdla_NV_NVDLA_SDP_RDMA_EG_ro* const __PVT__NV_nvdla__DOT__u_partition_p__DOT__u_NV_NVDLA_sdp__DOT__u_rdma__DOT__u_nrdma__DOT__u_eg__DOT__u_alu;
    VNV_nvdla_NV_NVDLA_SDP_RDMA_EG_ro* const __PVT__NV_nvdla__DOT__u_partition_p__DOT__u_NV_NVDLA_sdp__DOT__u_rdma__DOT__u_nrdma__DOT__u_eg__DOT__u_mul;
    VNV_nvdla_nv_ram_rwsp_160x65__Fz2* const __PVT__NV_nvdla__DOT__u_partition_p__DOT__u_NV_NVDLA_sdp__DOT__u_rdma__DOT__u_nrdma__DOT__u_lat_fifo__DOT__ram;
    VNV_nvdla_NV_NVDLA_SDP_REG_dual* const __PVT__NV_nvdla__DOT__u_partition_p__DOT__u_NV_NVDLA_sdp__DOT__u_reg__DOT__u_dual_reg_d0;
    VNV_nvdla_NV_NVDLA_SDP_REG_dual* const __PVT__NV_nvdla__DOT__u_partition_p__DOT__u_NV_NVDLA_sdp__DOT__u_reg__DOT__u_dual_reg_d1;

    // Root instance pointer to allow access to model internals,
    // including inlined /* verilator public_flat_* */ items.
    VNV_nvdla___024root* const rootp;

    // CONSTRUCTORS
    /// Construct the model; called by application code
    /// If contextp is null, then the model will use the default global context
    /// If name is "", then makes a wrapper with a
    /// single model invisible with respect to DPI scope names.
    explicit VNV_nvdla(VerilatedContext* contextp, const char* name = "TOP");
    explicit VNV_nvdla(const char* name = "TOP");
    /// Destroy the model; called (often implicitly) by application code
    virtual ~VNV_nvdla();
  private:
    VL_UNCOPYABLE(VNV_nvdla);  ///< Copying not allowed

  public:
    // API METHODS
    /// Evaluate the model.  Application must call when inputs change.
    void eval() { eval_step(); }
    /// Evaluate when calling multiple units/models per time step.
    void eval_step();
    /// Evaluate at end of a timestep for tracing, when using eval_step().
    /// Application must call after all eval() and before time changes.
    void eval_end_step() {}
    /// Simulation complete, run final blocks.  Application must call on completion.
    void final();
    /// Return current simulation context for this model.
    /// Used to get to e.g. simulation time via contextp()->time()
    VerilatedContext* contextp() const;
    /// Retrieve name of this model instance (as passed to constructor).
    const char* name() const;
} VL_ATTR_ALIGNED(VL_CACHE_LINE_BYTES);

#endif  // guard
