#Auto generated by Edalize

TOP_MODULE        := aes_tb
VC_FILE           := lowrisc_dv_verilator_aes_tb_0.vc
VERILATOR_OPTIONS := -LDFLAGS "-pthread -lcrypto" -DDISABLE_PRIM_CDC_RAND_DELAY -DREQUESTS_FILE=\"gcm_k128_a20_d60.svh\" --trace --trace-fst --trace-structs --trace-params --trace-max-array 1024 -CFLAGS "-std=c++11 -Wall -DVM_TRACE_FMT_FST -DTOPLEVEL_NAME=aes_tb -g -O0" -LDFLAGS "-pthread -lutil -lelf" -Wall -Wno-fatal
MAKE_OPTIONS      := 
