// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vaes_tb.h for the primary calling header

#ifndef VERILATED_VAES_TB_AES_SBOX__S4_H_
#define VERILATED_VAES_TB_AES_SBOX__S4_H_  // guard

#include "verilated.h"

class Vaes_tb__Syms;
VL_MODULE(Vaes_tb_aes_sbox__S4) {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(clk_i,0,0);
        VL_IN8(rst_ni,0,0);
        VL_IN8(en_i,0,0);
        VL_OUT8(out_req_o,0,0);
        VL_IN8(out_ack_i,0,0);
        VL_IN8(op_i,1,0);
        VL_IN8(data_i,7,0);
        VL_IN8(mask_i,7,0);
        VL_OUT8(data_o,7,0);
        VL_OUT8(mask_o,7,0);
        CData/*7:0*/ __PVT__gen_sbox_masked__DOT__gen_sbox_dom__DOT__u_aes_sbox__DOT__in_data_basis_x;
        CData/*7:0*/ __PVT__gen_sbox_masked__DOT__gen_sbox_dom__DOT__u_aes_sbox__DOT__out_data_basis_x;
        CData/*7:0*/ __PVT__gen_sbox_masked__DOT__gen_sbox_dom__DOT__u_aes_sbox__DOT__in_mask_basis_x;
        CData/*7:0*/ __PVT__gen_sbox_masked__DOT__gen_sbox_dom__DOT__u_aes_sbox__DOT__out_mask_basis_x;
        CData/*3:0*/ __PVT__gen_sbox_masked__DOT__gen_sbox_dom__DOT__u_aes_sbox__DOT__we;
        CData/*2:0*/ __PVT__gen_sbox_masked__DOT__gen_sbox_dom__DOT__u_aes_sbox__DOT__count_d;
        CData/*2:0*/ __PVT__gen_sbox_masked__DOT__gen_sbox_dom__DOT__u_aes_sbox__DOT__count_q;
        CData/*3:0*/ __PVT__gen_sbox_masked__DOT__gen_sbox_dom__DOT__u_aes_sbox__DOT__u_aes_dom_inverse_gf2p8__DOT__a_y_ss_d;
        CData/*3:0*/ __PVT__gen_sbox_masked__DOT__gen_sbox_dom__DOT__u_aes_sbox__DOT__u_aes_dom_inverse_gf2p8__DOT__b_y_ss_d;
        CData/*7:0*/ gen_sbox_masked__DOT__gen_sbox_dom__DOT__u_aes_sbox__DOT__u_aes_dom_inverse_gf2p8__DOT____Vcellout__u_prim_flop_ab_y_ss__q_o;
        CData/*7:0*/ gen_sbox_masked__DOT__gen_sbox_dom__DOT__u_aes_sbox__DOT__u_aes_dom_inverse_gf2p8__DOT____Vcellinp__u_prim_buf_ab_gamma__in_i;
        CData/*3:0*/ __PVT__gen_sbox_masked__DOT__gen_sbox_dom__DOT__u_aes_sbox__DOT__u_aes_dom_inverse_gf2p8__DOT__a_theta;
        CData/*3:0*/ __PVT__gen_sbox_masked__DOT__gen_sbox_dom__DOT__u_aes_sbox__DOT__u_aes_dom_inverse_gf2p8__DOT__b_theta;
        CData/*7:0*/ gen_sbox_masked__DOT__gen_sbox_dom__DOT__u_aes_sbox__DOT__u_aes_dom_inverse_gf2p8__DOT__u_aes_dom_mul_y1_y0__DOT____Vcellout__u_prim_flop_ab_yz0__q_o;
        CData/*3:0*/ __PVT__gen_sbox_masked__DOT__gen_sbox_dom__DOT__u_aes_sbox__DOT__u_aes_dom_inverse_gf2p8__DOT__u_aes_dom_mul_y1_y0__DOT__mul_ax_z0;
        CData/*3:0*/ __PVT__gen_sbox_masked__DOT__gen_sbox_dom__DOT__u_aes_sbox__DOT__u_aes_dom_inverse_gf2p8__DOT__u_aes_dom_mul_y1_y0__DOT__mul_bx_z0;
        CData/*7:0*/ gen_sbox_masked__DOT__gen_sbox_dom__DOT__u_aes_sbox__DOT__u_aes_dom_inverse_gf2p8__DOT__u_aes_dom_mul_y1_y0__DOT____Vcellinp__u_prim_buf_mul_abx_z0__in_i;
        CData/*7:0*/ gen_sbox_masked__DOT__gen_sbox_dom__DOT__u_aes_sbox__DOT__u_aes_dom_inverse_gf2p8__DOT__u_aes_dom_mul_y1_y0__DOT____Vcellout__u_prim_flop_abxz0_z1__q_o;
        CData/*7:0*/ gen_sbox_masked__DOT__gen_sbox_dom__DOT__u_aes_sbox__DOT__u_aes_dom_inverse_gf2p8__DOT__u_aes_dom_mul_y1_y0__DOT____Vcellinp__gen_not_pre_dom_indep__DOT__u_prim_buf_ab_b__in_i;
        CData/*3:0*/ __PVT__gen_sbox_masked__DOT__gen_sbox_dom__DOT__u_aes_sbox__DOT__u_aes_dom_inverse_gf2p8__DOT__u_aes_dom_mul_y1_y0__DOT__gen_not_pre_dom_indep__DOT__a_mul_ax_b;
        CData/*3:0*/ __PVT__gen_sbox_masked__DOT__gen_sbox_dom__DOT__u_aes_sbox__DOT__u_aes_dom_inverse_gf2p8__DOT__u_aes_dom_mul_y1_y0__DOT__gen_not_pre_dom_indep__DOT__b_mul_bx_b;
        CData/*7:0*/ gen_sbox_masked__DOT__gen_sbox_dom__DOT__u_aes_sbox__DOT__u_aes_dom_inverse_gf2p8__DOT__u_aes_dom_mul_y1_y0__DOT____Vcellinp__gen_not_pre_dom_indep__DOT__u_prim_buf_ab_mul_abx_b__in_i;
        CData/*1:0*/ __PVT__gen_sbox_masked__DOT__gen_sbox_dom__DOT__u_aes_sbox__DOT__u_aes_dom_inverse_gf2p8__DOT__u_aes_dom_inverse_gf2p4__DOT__a_gamma_ss_d;
        CData/*1:0*/ __PVT__gen_sbox_masked__DOT__gen_sbox_dom__DOT__u_aes_sbox__DOT__u_aes_dom_inverse_gf2p8__DOT__u_aes_dom_inverse_gf2p4__DOT__b_gamma_ss_d;
        CData/*3:0*/ gen_sbox_masked__DOT__gen_sbox_dom__DOT__u_aes_sbox__DOT__u_aes_dom_inverse_gf2p8__DOT__u_aes_dom_inverse_gf2p4__DOT____Vcellout__u_prim_flop_ab_gamma_ss__q_o;
        CData/*7:0*/ gen_sbox_masked__DOT__gen_sbox_dom__DOT__u_aes_sbox__DOT__u_aes_dom_inverse_gf2p8__DOT__u_aes_dom_inverse_gf2p4__DOT____Vcellout__u_prim_flop_ab_gamma10__q_o;
        CData/*3:0*/ __PVT__gen_sbox_masked__DOT__gen_sbox_dom__DOT__u_aes_sbox__DOT__u_aes_dom_inverse_gf2p8__DOT__u_aes_dom_inverse_gf2p4__DOT__b_gamma10_prd2;
        CData/*1:0*/ __PVT__gen_sbox_masked__DOT__gen_sbox_dom__DOT__u_aes_sbox__DOT__u_aes_dom_inverse_gf2p8__DOT__u_aes_dom_inverse_gf2p4__DOT__a_omega;
        CData/*1:0*/ __PVT__gen_sbox_masked__DOT__gen_sbox_dom__DOT__u_aes_sbox__DOT__u_aes_dom_inverse_gf2p8__DOT__u_aes_dom_inverse_gf2p4__DOT__b_omega;
        CData/*3:0*/ gen_sbox_masked__DOT__gen_sbox_dom__DOT__u_aes_sbox__DOT__u_aes_dom_inverse_gf2p8__DOT__u_aes_dom_inverse_gf2p4__DOT____Vcellinp__u_prim_buf_ab_omega__in_i;
        CData/*7:0*/ gen_sbox_masked__DOT__gen_sbox_dom__DOT__u_aes_sbox__DOT__u_aes_dom_inverse_gf2p8__DOT__u_aes_dom_inverse_gf2p4__DOT____Vcellout__gen_prim_flop_omega_gamma10__DOT__u_prim_flop_ab_gamma10_q__q_o;
        CData/*3:0*/ gen_sbox_masked__DOT__gen_sbox_dom__DOT__u_aes_sbox__DOT__u_aes_dom_inverse_gf2p8__DOT__u_aes_dom_inverse_gf2p4__DOT____Vcellout__gen_prim_flop_omega_gamma10__DOT__u_prim_flop_ab_omega_buf__q_o;
        CData/*3:0*/ gen_sbox_masked__DOT__gen_sbox_dom__DOT__u_aes_sbox__DOT__u_aes_dom_inverse_gf2p8__DOT__u_aes_dom_inverse_gf2p4__DOT__u_aes_dom_mul_gamma1_gamma0__DOT____Vcellout__u_prim_flop_ab_yz0__q_o;
        CData/*1:0*/ __PVT__gen_sbox_masked__DOT__gen_sbox_dom__DOT__u_aes_sbox__DOT__u_aes_dom_inverse_gf2p8__DOT__u_aes_dom_inverse_gf2p4__DOT__u_aes_dom_mul_gamma1_gamma0__DOT__mul_ax_z0;
        CData/*1:0*/ __PVT__gen_sbox_masked__DOT__gen_sbox_dom__DOT__u_aes_sbox__DOT__u_aes_dom_inverse_gf2p8__DOT__u_aes_dom_inverse_gf2p4__DOT__u_aes_dom_mul_gamma1_gamma0__DOT__mul_bx_z0;
        CData/*3:0*/ gen_sbox_masked__DOT__gen_sbox_dom__DOT__u_aes_sbox__DOT__u_aes_dom_inverse_gf2p8__DOT__u_aes_dom_inverse_gf2p4__DOT__u_aes_dom_mul_gamma1_gamma0__DOT____Vcellinp__u_prim_buf_mul_abx_z0__in_i;
        CData/*3:0*/ gen_sbox_masked__DOT__gen_sbox_dom__DOT__u_aes_sbox__DOT__u_aes_dom_inverse_gf2p8__DOT__u_aes_dom_inverse_gf2p4__DOT__u_aes_dom_mul_gamma1_gamma0__DOT____Vcellout__u_prim_flop_abxz0_z1__q_o;
        CData/*3:0*/ gen_sbox_masked__DOT__gen_sbox_dom__DOT__u_aes_sbox__DOT__u_aes_dom_inverse_gf2p8__DOT__u_aes_dom_inverse_gf2p4__DOT__u_aes_dom_mul_gamma1_gamma0__DOT____Vcellinp__gen_not_pre_dom_indep__DOT__u_prim_buf_ab_b__in_i;
        CData/*1:0*/ __PVT__gen_sbox_masked__DOT__gen_sbox_dom__DOT__u_aes_sbox__DOT__u_aes_dom_inverse_gf2p8__DOT__u_aes_dom_inverse_gf2p4__DOT__u_aes_dom_mul_gamma1_gamma0__DOT__gen_not_pre_dom_indep__DOT__a_mul_ax_b;
        CData/*1:0*/ __PVT__gen_sbox_masked__DOT__gen_sbox_dom__DOT__u_aes_sbox__DOT__u_aes_dom_inverse_gf2p8__DOT__u_aes_dom_inverse_gf2p4__DOT__u_aes_dom_mul_gamma1_gamma0__DOT__gen_not_pre_dom_indep__DOT__b_mul_bx_b;
        CData/*3:0*/ gen_sbox_masked__DOT__gen_sbox_dom__DOT__u_aes_sbox__DOT__u_aes_dom_inverse_gf2p8__DOT__u_aes_dom_inverse_gf2p4__DOT__u_aes_dom_mul_gamma1_gamma0__DOT____Vcellinp__gen_not_pre_dom_indep__DOT__u_prim_buf_ab_mul_abx_b__in_i;
        CData/*3:0*/ gen_sbox_masked__DOT__gen_sbox_dom__DOT__u_aes_sbox__DOT__u_aes_dom_inverse_gf2p8__DOT__u_aes_dom_inverse_gf2p4__DOT__u_aes_dom_mul_omega_gamma1__DOT____Vcellout__u_prim_flop_ab_yz0__q_o;
        CData/*1:0*/ __PVT__gen_sbox_masked__DOT__gen_sbox_dom__DOT__u_aes_sbox__DOT__u_aes_dom_inverse_gf2p8__DOT__u_aes_dom_inverse_gf2p4__DOT__u_aes_dom_mul_omega_gamma1__DOT__mul_ax_z0;
        CData/*1:0*/ __PVT__gen_sbox_masked__DOT__gen_sbox_dom__DOT__u_aes_sbox__DOT__u_aes_dom_inverse_gf2p8__DOT__u_aes_dom_inverse_gf2p4__DOT__u_aes_dom_mul_omega_gamma1__DOT__mul_bx_z0;
        CData/*3:0*/ gen_sbox_masked__DOT__gen_sbox_dom__DOT__u_aes_sbox__DOT__u_aes_dom_inverse_gf2p8__DOT__u_aes_dom_inverse_gf2p4__DOT__u_aes_dom_mul_omega_gamma1__DOT____Vcellinp__u_prim_buf_mul_abx_z0__in_i;
        CData/*3:0*/ gen_sbox_masked__DOT__gen_sbox_dom__DOT__u_aes_sbox__DOT__u_aes_dom_inverse_gf2p8__DOT__u_aes_dom_inverse_gf2p4__DOT__u_aes_dom_mul_omega_gamma1__DOT____Vcellout__u_prim_flop_abxz0_z1__q_o;
        CData/*3:0*/ gen_sbox_masked__DOT__gen_sbox_dom__DOT__u_aes_sbox__DOT__u_aes_dom_inverse_gf2p8__DOT__u_aes_dom_inverse_gf2p4__DOT__u_aes_dom_mul_omega_gamma1__DOT____Vcellinp__gen_not_pre_dom_indep__DOT__u_prim_buf_ab_b__in_i;
        CData/*1:0*/ __PVT__gen_sbox_masked__DOT__gen_sbox_dom__DOT__u_aes_sbox__DOT__u_aes_dom_inverse_gf2p8__DOT__u_aes_dom_inverse_gf2p4__DOT__u_aes_dom_mul_omega_gamma1__DOT__gen_not_pre_dom_indep__DOT__a_mul_ax_b;
        CData/*1:0*/ __PVT__gen_sbox_masked__DOT__gen_sbox_dom__DOT__u_aes_sbox__DOT__u_aes_dom_inverse_gf2p8__DOT__u_aes_dom_inverse_gf2p4__DOT__u_aes_dom_mul_omega_gamma1__DOT__gen_not_pre_dom_indep__DOT__b_mul_bx_b;
        CData/*3:0*/ gen_sbox_masked__DOT__gen_sbox_dom__DOT__u_aes_sbox__DOT__u_aes_dom_inverse_gf2p8__DOT__u_aes_dom_inverse_gf2p4__DOT__u_aes_dom_mul_omega_gamma1__DOT____Vcellinp__gen_not_pre_dom_indep__DOT__u_prim_buf_ab_mul_abx_b__in_i;
        CData/*3:0*/ gen_sbox_masked__DOT__gen_sbox_dom__DOT__u_aes_sbox__DOT__u_aes_dom_inverse_gf2p8__DOT__u_aes_dom_inverse_gf2p4__DOT__u_aes_dom_mul_omega_gamma0__DOT____Vcellout__u_prim_flop_ab_yz0__q_o;
        CData/*1:0*/ __PVT__gen_sbox_masked__DOT__gen_sbox_dom__DOT__u_aes_sbox__DOT__u_aes_dom_inverse_gf2p8__DOT__u_aes_dom_inverse_gf2p4__DOT__u_aes_dom_mul_omega_gamma0__DOT__mul_ax_z0;
        CData/*1:0*/ __PVT__gen_sbox_masked__DOT__gen_sbox_dom__DOT__u_aes_sbox__DOT__u_aes_dom_inverse_gf2p8__DOT__u_aes_dom_inverse_gf2p4__DOT__u_aes_dom_mul_omega_gamma0__DOT__mul_bx_z0;
        CData/*3:0*/ gen_sbox_masked__DOT__gen_sbox_dom__DOT__u_aes_sbox__DOT__u_aes_dom_inverse_gf2p8__DOT__u_aes_dom_inverse_gf2p4__DOT__u_aes_dom_mul_omega_gamma0__DOT____Vcellinp__u_prim_buf_mul_abx_z0__in_i;
    };
    struct {
        CData/*3:0*/ gen_sbox_masked__DOT__gen_sbox_dom__DOT__u_aes_sbox__DOT__u_aes_dom_inverse_gf2p8__DOT__u_aes_dom_inverse_gf2p4__DOT__u_aes_dom_mul_omega_gamma0__DOT____Vcellout__u_prim_flop_abxz0_z1__q_o;
        CData/*3:0*/ gen_sbox_masked__DOT__gen_sbox_dom__DOT__u_aes_sbox__DOT__u_aes_dom_inverse_gf2p8__DOT__u_aes_dom_inverse_gf2p4__DOT__u_aes_dom_mul_omega_gamma0__DOT____Vcellinp__gen_not_pre_dom_indep__DOT__u_prim_buf_ab_b__in_i;
        CData/*1:0*/ __PVT__gen_sbox_masked__DOT__gen_sbox_dom__DOT__u_aes_sbox__DOT__u_aes_dom_inverse_gf2p8__DOT__u_aes_dom_inverse_gf2p4__DOT__u_aes_dom_mul_omega_gamma0__DOT__gen_not_pre_dom_indep__DOT__a_mul_ax_b;
        CData/*1:0*/ __PVT__gen_sbox_masked__DOT__gen_sbox_dom__DOT__u_aes_sbox__DOT__u_aes_dom_inverse_gf2p8__DOT__u_aes_dom_inverse_gf2p4__DOT__u_aes_dom_mul_omega_gamma0__DOT__gen_not_pre_dom_indep__DOT__b_mul_bx_b;
        CData/*3:0*/ gen_sbox_masked__DOT__gen_sbox_dom__DOT__u_aes_sbox__DOT__u_aes_dom_inverse_gf2p8__DOT__u_aes_dom_inverse_gf2p4__DOT__u_aes_dom_mul_omega_gamma0__DOT____Vcellinp__gen_not_pre_dom_indep__DOT__u_prim_buf_ab_mul_abx_b__in_i;
        CData/*3:0*/ __PVT__gen_sbox_masked__DOT__gen_sbox_dom__DOT__u_aes_sbox__DOT__u_aes_dom_inverse_gf2p8__DOT__u_aes_dom_mul_theta_y1__DOT__mul_ax_ay_d;
        CData/*3:0*/ __PVT__gen_sbox_masked__DOT__gen_sbox_dom__DOT__u_aes_sbox__DOT__u_aes_dom_inverse_gf2p8__DOT__u_aes_dom_mul_theta_y1__DOT__mul_bx_by_d;
        CData/*3:0*/ __PVT__gen_sbox_masked__DOT__gen_sbox_dom__DOT__u_aes_sbox__DOT__u_aes_dom_inverse_gf2p8__DOT__u_aes_dom_mul_theta_y1__DOT__mul_ax_by;
        CData/*3:0*/ __PVT__gen_sbox_masked__DOT__gen_sbox_dom__DOT__u_aes_sbox__DOT__u_aes_dom_inverse_gf2p8__DOT__u_aes_dom_mul_theta_y1__DOT__mul_ay_bx;
        CData/*7:0*/ gen_sbox_masked__DOT__gen_sbox_dom__DOT__u_aes_sbox__DOT__u_aes_dom_inverse_gf2p8__DOT__u_aes_dom_mul_theta_y1__DOT____Vcellout__u_prim_flop_abq_z0__q_o;
        CData/*7:0*/ gen_sbox_masked__DOT__gen_sbox_dom__DOT__u_aes_sbox__DOT__u_aes_dom_inverse_gf2p8__DOT__u_aes_dom_mul_theta_y1__DOT____Vcellout__gen_pipeline__DOT__u_prim_flop_mul_abx_aby__q_o;
        CData/*3:0*/ __PVT__gen_sbox_masked__DOT__gen_sbox_dom__DOT__u_aes_sbox__DOT__u_aes_dom_inverse_gf2p8__DOT__u_aes_dom_mul_theta_y0__DOT__mul_ax_ay_d;
        CData/*3:0*/ __PVT__gen_sbox_masked__DOT__gen_sbox_dom__DOT__u_aes_sbox__DOT__u_aes_dom_inverse_gf2p8__DOT__u_aes_dom_mul_theta_y0__DOT__mul_bx_by_d;
        CData/*3:0*/ __PVT__gen_sbox_masked__DOT__gen_sbox_dom__DOT__u_aes_sbox__DOT__u_aes_dom_inverse_gf2p8__DOT__u_aes_dom_mul_theta_y0__DOT__mul_ax_by;
        CData/*3:0*/ __PVT__gen_sbox_masked__DOT__gen_sbox_dom__DOT__u_aes_sbox__DOT__u_aes_dom_inverse_gf2p8__DOT__u_aes_dom_mul_theta_y0__DOT__mul_ay_bx;
        CData/*7:0*/ gen_sbox_masked__DOT__gen_sbox_dom__DOT__u_aes_sbox__DOT__u_aes_dom_inverse_gf2p8__DOT__u_aes_dom_mul_theta_y0__DOT____Vcellout__u_prim_flop_abq_z0__q_o;
        CData/*7:0*/ gen_sbox_masked__DOT__gen_sbox_dom__DOT__u_aes_sbox__DOT__u_aes_dom_inverse_gf2p8__DOT__u_aes_dom_mul_theta_y0__DOT____Vcellout__gen_pipeline__DOT__u_prim_flop_mul_abx_aby__q_o;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__20__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__26__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__32__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__38__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__62__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__68__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__74__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__80__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__86__theta;
        CData/*1:0*/ __Vfunc_aes_mul_gf2p4__86__a;
        CData/*1:0*/ __Vfunc_aes_mul_gf2p4__86__b;
        CData/*1:0*/ __Vfunc_aes_mul_gf2p4__86__c;
        CData/*1:0*/ __Vfunc_aes_scale_omega2_gf2p2__90__d;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__92__theta;
        CData/*1:0*/ __Vfunc_aes_mul_gf2p4__92__a;
        CData/*1:0*/ __Vfunc_aes_mul_gf2p4__92__b;
        CData/*0:0*/ __Vfunc_aes_mul_gf2p2__95__a;
        CData/*0:0*/ __Vfunc_aes_mul_gf2p2__95__b;
        CData/*0:0*/ __Vfunc_aes_mul_gf2p2__95__c;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__98__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__104__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__130__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__136__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__142__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__148__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__172__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__178__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__184__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__190__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__196__theta;
        CData/*1:0*/ __Vfunc_aes_mul_gf2p4__196__a;
        CData/*1:0*/ __Vfunc_aes_mul_gf2p4__196__b;
        CData/*1:0*/ __Vfunc_aes_mul_gf2p4__196__c;
        CData/*1:0*/ __Vfunc_aes_scale_omega2_gf2p2__200__d;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__202__theta;
        CData/*1:0*/ __Vfunc_aes_mul_gf2p4__202__a;
        CData/*1:0*/ __Vfunc_aes_mul_gf2p4__202__b;
        CData/*0:0*/ __Vfunc_aes_mul_gf2p2__205__a;
        CData/*0:0*/ __Vfunc_aes_mul_gf2p2__205__b;
        CData/*0:0*/ __Vfunc_aes_mul_gf2p2__205__c;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__208__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__214__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__240__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__246__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__252__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__258__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__282__theta;
    };
    struct {
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__288__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__294__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__300__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__306__theta;
        CData/*1:0*/ __Vfunc_aes_mul_gf2p4__306__a;
        CData/*1:0*/ __Vfunc_aes_mul_gf2p4__306__b;
        CData/*1:0*/ __Vfunc_aes_mul_gf2p4__306__c;
        CData/*1:0*/ __Vfunc_aes_scale_omega2_gf2p2__310__d;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__312__theta;
        CData/*1:0*/ __Vfunc_aes_mul_gf2p4__312__a;
        CData/*1:0*/ __Vfunc_aes_mul_gf2p4__312__b;
        CData/*0:0*/ __Vfunc_aes_mul_gf2p2__315__a;
        CData/*0:0*/ __Vfunc_aes_mul_gf2p2__315__b;
        CData/*0:0*/ __Vfunc_aes_mul_gf2p2__315__c;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__318__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__324__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__350__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__356__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__362__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__368__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__392__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__398__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__404__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__410__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__416__theta;
        CData/*1:0*/ __Vfunc_aes_mul_gf2p4__416__a;
        CData/*1:0*/ __Vfunc_aes_mul_gf2p4__416__b;
        CData/*1:0*/ __Vfunc_aes_mul_gf2p4__416__c;
        CData/*1:0*/ __Vfunc_aes_scale_omega2_gf2p2__420__d;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__422__theta;
        CData/*1:0*/ __Vfunc_aes_mul_gf2p4__422__a;
        CData/*1:0*/ __Vfunc_aes_mul_gf2p4__422__b;
        CData/*0:0*/ __Vfunc_aes_mul_gf2p2__425__a;
        CData/*0:0*/ __Vfunc_aes_mul_gf2p2__425__b;
        CData/*0:0*/ __Vfunc_aes_mul_gf2p2__425__c;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__428__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__434__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__460__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__466__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__472__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__478__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__502__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__508__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__514__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__520__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__526__theta;
        CData/*1:0*/ __Vfunc_aes_mul_gf2p4__526__a;
        CData/*1:0*/ __Vfunc_aes_mul_gf2p4__526__b;
        CData/*1:0*/ __Vfunc_aes_mul_gf2p4__526__c;
        CData/*1:0*/ __Vfunc_aes_scale_omega2_gf2p2__530__d;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__532__theta;
        CData/*1:0*/ __Vfunc_aes_mul_gf2p4__532__a;
        CData/*1:0*/ __Vfunc_aes_mul_gf2p4__532__b;
        CData/*0:0*/ __Vfunc_aes_mul_gf2p2__535__a;
        CData/*0:0*/ __Vfunc_aes_mul_gf2p2__535__b;
        CData/*0:0*/ __Vfunc_aes_mul_gf2p2__535__c;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__538__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__544__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__570__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__576__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__582__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__588__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__612__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__618__theta;
    };
    struct {
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__624__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__630__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__636__theta;
        CData/*1:0*/ __Vfunc_aes_mul_gf2p4__636__a;
        CData/*1:0*/ __Vfunc_aes_mul_gf2p4__636__b;
        CData/*1:0*/ __Vfunc_aes_mul_gf2p4__636__c;
        CData/*1:0*/ __Vfunc_aes_scale_omega2_gf2p2__640__d;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__642__theta;
        CData/*1:0*/ __Vfunc_aes_mul_gf2p4__642__a;
        CData/*1:0*/ __Vfunc_aes_mul_gf2p4__642__b;
        CData/*0:0*/ __Vfunc_aes_mul_gf2p2__645__a;
        CData/*0:0*/ __Vfunc_aes_mul_gf2p2__645__b;
        CData/*0:0*/ __Vfunc_aes_mul_gf2p2__645__c;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__648__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__654__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__680__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__686__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__692__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__698__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__722__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__728__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__734__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__740__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__746__theta;
        CData/*1:0*/ __Vfunc_aes_mul_gf2p4__746__a;
        CData/*1:0*/ __Vfunc_aes_mul_gf2p4__746__b;
        CData/*1:0*/ __Vfunc_aes_mul_gf2p4__746__c;
        CData/*1:0*/ __Vfunc_aes_scale_omega2_gf2p2__750__d;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__752__theta;
        CData/*1:0*/ __Vfunc_aes_mul_gf2p4__752__a;
        CData/*1:0*/ __Vfunc_aes_mul_gf2p4__752__b;
        CData/*0:0*/ __Vfunc_aes_mul_gf2p2__755__a;
        CData/*0:0*/ __Vfunc_aes_mul_gf2p2__755__b;
        CData/*0:0*/ __Vfunc_aes_mul_gf2p2__755__c;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__758__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__764__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__790__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__796__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__802__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__808__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__832__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__838__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__844__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__850__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__856__theta;
        CData/*1:0*/ __Vfunc_aes_mul_gf2p4__856__a;
        CData/*1:0*/ __Vfunc_aes_mul_gf2p4__856__b;
        CData/*1:0*/ __Vfunc_aes_mul_gf2p4__856__c;
        CData/*1:0*/ __Vfunc_aes_scale_omega2_gf2p2__860__d;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__862__theta;
        CData/*1:0*/ __Vfunc_aes_mul_gf2p4__862__a;
        CData/*1:0*/ __Vfunc_aes_mul_gf2p4__862__b;
        CData/*0:0*/ __Vfunc_aes_mul_gf2p2__865__a;
        CData/*0:0*/ __Vfunc_aes_mul_gf2p2__865__b;
        CData/*0:0*/ __Vfunc_aes_mul_gf2p2__865__c;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__868__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__874__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__900__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__906__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__912__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__918__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__942__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__948__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__954__theta;
    };
    struct {
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__960__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__966__theta;
        CData/*1:0*/ __Vfunc_aes_mul_gf2p4__966__a;
        CData/*1:0*/ __Vfunc_aes_mul_gf2p4__966__b;
        CData/*1:0*/ __Vfunc_aes_mul_gf2p4__966__c;
        CData/*1:0*/ __Vfunc_aes_scale_omega2_gf2p2__970__d;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__972__theta;
        CData/*1:0*/ __Vfunc_aes_mul_gf2p4__972__a;
        CData/*1:0*/ __Vfunc_aes_mul_gf2p4__972__b;
        CData/*0:0*/ __Vfunc_aes_mul_gf2p2__975__a;
        CData/*0:0*/ __Vfunc_aes_mul_gf2p2__975__b;
        CData/*0:0*/ __Vfunc_aes_mul_gf2p2__975__c;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__978__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__984__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__1010__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__1016__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__1022__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__1028__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__1052__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__1058__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__1064__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__1070__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__1076__theta;
        CData/*1:0*/ __Vfunc_aes_mul_gf2p4__1076__a;
        CData/*1:0*/ __Vfunc_aes_mul_gf2p4__1076__b;
        CData/*1:0*/ __Vfunc_aes_mul_gf2p4__1076__c;
        CData/*1:0*/ __Vfunc_aes_scale_omega2_gf2p2__1080__d;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__1082__theta;
        CData/*1:0*/ __Vfunc_aes_mul_gf2p4__1082__a;
        CData/*1:0*/ __Vfunc_aes_mul_gf2p4__1082__b;
        CData/*0:0*/ __Vfunc_aes_mul_gf2p2__1085__a;
        CData/*0:0*/ __Vfunc_aes_mul_gf2p2__1085__b;
        CData/*0:0*/ __Vfunc_aes_mul_gf2p2__1085__c;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__1088__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__1094__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__1120__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__1126__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__1132__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__1138__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__1162__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__1168__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__1174__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__1180__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__1186__theta;
        CData/*1:0*/ __Vfunc_aes_mul_gf2p4__1186__a;
        CData/*1:0*/ __Vfunc_aes_mul_gf2p4__1186__b;
        CData/*1:0*/ __Vfunc_aes_mul_gf2p4__1186__c;
        CData/*1:0*/ __Vfunc_aes_scale_omega2_gf2p2__1190__d;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__1192__theta;
        CData/*1:0*/ __Vfunc_aes_mul_gf2p4__1192__a;
        CData/*1:0*/ __Vfunc_aes_mul_gf2p4__1192__b;
        CData/*0:0*/ __Vfunc_aes_mul_gf2p2__1195__a;
        CData/*0:0*/ __Vfunc_aes_mul_gf2p2__1195__b;
        CData/*0:0*/ __Vfunc_aes_mul_gf2p2__1195__c;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__1198__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__1204__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__1230__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__1236__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__1242__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__1248__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__1272__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__1278__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__1284__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__1290__theta;
    };
    struct {
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__1296__theta;
        CData/*1:0*/ __Vfunc_aes_mul_gf2p4__1296__a;
        CData/*1:0*/ __Vfunc_aes_mul_gf2p4__1296__b;
        CData/*1:0*/ __Vfunc_aes_mul_gf2p4__1296__c;
        CData/*1:0*/ __Vfunc_aes_scale_omega2_gf2p2__1300__d;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__1302__theta;
        CData/*1:0*/ __Vfunc_aes_mul_gf2p4__1302__a;
        CData/*1:0*/ __Vfunc_aes_mul_gf2p4__1302__b;
        CData/*0:0*/ __Vfunc_aes_mul_gf2p2__1305__a;
        CData/*0:0*/ __Vfunc_aes_mul_gf2p2__1305__b;
        CData/*0:0*/ __Vfunc_aes_mul_gf2p2__1305__c;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__1308__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__1314__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__1340__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__1346__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__1352__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__1358__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__1382__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__1388__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__1394__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__1400__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__1406__theta;
        CData/*1:0*/ __Vfunc_aes_mul_gf2p4__1406__a;
        CData/*1:0*/ __Vfunc_aes_mul_gf2p4__1406__b;
        CData/*1:0*/ __Vfunc_aes_mul_gf2p4__1406__c;
        CData/*1:0*/ __Vfunc_aes_scale_omega2_gf2p2__1410__d;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__1412__theta;
        CData/*1:0*/ __Vfunc_aes_mul_gf2p4__1412__a;
        CData/*1:0*/ __Vfunc_aes_mul_gf2p4__1412__b;
        CData/*0:0*/ __Vfunc_aes_mul_gf2p2__1415__a;
        CData/*0:0*/ __Vfunc_aes_mul_gf2p2__1415__b;
        CData/*0:0*/ __Vfunc_aes_mul_gf2p2__1415__c;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__1418__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__1424__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__1450__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__1456__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__1462__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__1468__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__1492__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__1498__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__1504__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__1510__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__1516__theta;
        CData/*1:0*/ __Vfunc_aes_mul_gf2p4__1516__a;
        CData/*1:0*/ __Vfunc_aes_mul_gf2p4__1516__b;
        CData/*1:0*/ __Vfunc_aes_mul_gf2p4__1516__c;
        CData/*1:0*/ __Vfunc_aes_scale_omega2_gf2p2__1520__d;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__1522__theta;
        CData/*1:0*/ __Vfunc_aes_mul_gf2p4__1522__a;
        CData/*1:0*/ __Vfunc_aes_mul_gf2p4__1522__b;
        CData/*0:0*/ __Vfunc_aes_mul_gf2p2__1525__a;
        CData/*0:0*/ __Vfunc_aes_mul_gf2p2__1525__b;
        CData/*0:0*/ __Vfunc_aes_mul_gf2p2__1525__c;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__1528__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__1534__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__1560__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__1566__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__1572__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__1578__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__1602__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__1608__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__1614__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__1620__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__1626__theta;
    };
    struct {
        CData/*1:0*/ __Vfunc_aes_mul_gf2p4__1626__a;
        CData/*1:0*/ __Vfunc_aes_mul_gf2p4__1626__b;
        CData/*1:0*/ __Vfunc_aes_mul_gf2p4__1626__c;
        CData/*1:0*/ __Vfunc_aes_scale_omega2_gf2p2__1630__d;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__1632__theta;
        CData/*1:0*/ __Vfunc_aes_mul_gf2p4__1632__a;
        CData/*1:0*/ __Vfunc_aes_mul_gf2p4__1632__b;
        CData/*0:0*/ __Vfunc_aes_mul_gf2p2__1635__a;
        CData/*0:0*/ __Vfunc_aes_mul_gf2p2__1635__b;
        CData/*0:0*/ __Vfunc_aes_mul_gf2p2__1635__c;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__1638__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__1644__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__1670__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__1676__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__1682__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__1688__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__1712__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__1718__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__1724__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__1730__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__1736__theta;
        CData/*1:0*/ __Vfunc_aes_mul_gf2p4__1736__a;
        CData/*1:0*/ __Vfunc_aes_mul_gf2p4__1736__b;
        CData/*1:0*/ __Vfunc_aes_mul_gf2p4__1736__c;
        CData/*1:0*/ __Vfunc_aes_scale_omega2_gf2p2__1740__d;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__1742__theta;
        CData/*1:0*/ __Vfunc_aes_mul_gf2p4__1742__a;
        CData/*1:0*/ __Vfunc_aes_mul_gf2p4__1742__b;
        CData/*0:0*/ __Vfunc_aes_mul_gf2p2__1745__a;
        CData/*0:0*/ __Vfunc_aes_mul_gf2p2__1745__b;
        CData/*0:0*/ __Vfunc_aes_mul_gf2p2__1745__c;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__1748__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__1754__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__1780__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__1786__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__1792__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__1798__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__1822__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__1828__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__1834__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__1840__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__1846__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__1852__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__1858__gamma;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__1858__delta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__1858__theta;
        CData/*1:0*/ __Vfunc_aes_mul_gf2p2__1859__g;
        CData/*1:0*/ __Vfunc_aes_mul_gf2p2__1859__d;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__1864__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__1890__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__1896__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__1902__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__1908__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__1932__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__1938__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__1944__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__1950__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__1956__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__1962__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__1968__gamma;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__1968__delta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__1968__theta;
        CData/*1:0*/ __Vfunc_aes_mul_gf2p2__1969__g;
        CData/*1:0*/ __Vfunc_aes_mul_gf2p2__1969__d;
    };
    struct {
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__1974__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__2000__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__2006__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__2012__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__2018__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__2042__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__2048__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__2054__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__2060__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__2066__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__2072__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__2078__gamma;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__2078__delta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__2078__theta;
        CData/*1:0*/ __Vfunc_aes_mul_gf2p2__2079__g;
        CData/*1:0*/ __Vfunc_aes_mul_gf2p2__2079__d;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__2084__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__2110__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__2116__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__2122__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__2128__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__2152__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__2158__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__2164__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__2170__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__2176__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__2182__theta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__2188__gamma;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__2188__delta;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__2188__theta;
        CData/*1:0*/ __Vfunc_aes_mul_gf2p2__2189__g;
        CData/*1:0*/ __Vfunc_aes_mul_gf2p2__2189__d;
        CData/*3:0*/ __Vfunc_aes_mul_gf2p4__2194__theta;
        SData/*15:0*/ gen_sbox_masked__DOT__gen_sbox_dom__DOT__u_aes_sbox__DOT__u_aes_dom_inverse_gf2p8__DOT____Vcellout__u_prim_flop_ab_y10_qqq__q_o;
        SData/*15:0*/ gen_sbox_masked__DOT__gen_sbox_dom__DOT__u_aes_sbox__DOT__u_aes_dom_inverse_gf2p8__DOT____Vcellout__gen_prim_flop_ab_y10__DOT__u_prim_flop_ab_y10__q_o;
        VL_IN(prd_i,27,0);
        VL_OUT(prd_o,19,0);
        IData/*27:0*/ __PVT__gen_sbox_masked__DOT__gen_sbox_dom__DOT__u_aes_sbox__DOT__in_prd;
        IData/*19:0*/ __PVT__gen_sbox_masked__DOT__gen_sbox_dom__DOT__u_aes_sbox__DOT__out_prd;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__0__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__1__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__2__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__3__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__4__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__5__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__6__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__7__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__8__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__9__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__10__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__11__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__110__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__111__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__112__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__113__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__114__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__115__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__116__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__117__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__118__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__119__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__120__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__121__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__220__mat_a;
    };
    struct {
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__221__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__222__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__223__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__224__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__225__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__226__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__227__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__228__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__229__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__230__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__231__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__330__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__331__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__332__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__333__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__334__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__335__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__336__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__337__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__338__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__339__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__340__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__341__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__440__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__441__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__442__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__443__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__444__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__445__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__446__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__447__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__448__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__449__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__450__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__451__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__550__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__551__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__552__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__553__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__554__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__555__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__556__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__557__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__558__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__559__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__560__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__561__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__660__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__661__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__662__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__663__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__664__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__665__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__666__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__667__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__668__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__669__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__670__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__671__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__770__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__771__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__772__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__773__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__774__mat_a;
    };
    struct {
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__775__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__776__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__777__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__778__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__779__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__780__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__781__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__880__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__881__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__882__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__883__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__884__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__885__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__886__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__887__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__888__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__889__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__890__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__891__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__990__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__991__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__992__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__993__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__994__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__995__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__996__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__997__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__998__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__999__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__1000__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__1001__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__1100__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__1101__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__1102__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__1103__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__1104__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__1105__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__1106__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__1107__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__1108__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__1109__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__1110__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__1111__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__1210__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__1211__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__1212__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__1213__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__1214__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__1215__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__1216__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__1217__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__1218__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__1219__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__1220__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__1221__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__1320__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__1321__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__1322__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__1323__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__1324__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__1325__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__1326__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__1327__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__1328__mat_a;
    };
    struct {
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__1329__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__1330__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__1331__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__1430__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__1431__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__1432__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__1433__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__1434__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__1435__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__1436__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__1437__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__1438__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__1439__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__1440__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__1441__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__1540__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__1541__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__1542__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__1543__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__1544__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__1545__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__1546__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__1547__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__1548__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__1549__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__1550__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__1551__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__1650__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__1651__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__1652__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__1653__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__1654__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__1655__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__1656__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__1657__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__1658__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__1659__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__1660__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__1661__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__1760__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__1761__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__1762__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__1763__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__1764__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__1765__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__1766__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__1767__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__1768__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__1769__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__1770__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__1771__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__1870__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__1871__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__1872__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__1873__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__1874__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__1875__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__1876__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__1877__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__1878__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__1879__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__1880__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__1881__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__1980__mat_a;
    };
    struct {
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__1981__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__1982__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__1983__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__1984__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__1985__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__1986__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__1987__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__1988__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__1989__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__1990__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__1991__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__2090__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__2091__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__2092__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__2093__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__2094__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__2095__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__2096__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__2097__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__2098__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__2099__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__2100__mat_a;
        VlUnpacked<CData/*7:0*/, 8> __Vfunc_aes_mvm__2101__mat_a;
    };

    // INTERNAL VARIABLES
    Vaes_tb__Syms* vlSymsp;  // Symbol table

    // CONSTRUCTORS
    Vaes_tb_aes_sbox__S4(const char* name);
    ~Vaes_tb_aes_sbox__S4();
    VL_UNCOPYABLE(Vaes_tb_aes_sbox__S4);

    // INTERNAL METHODS
    void __Vconfigure(Vaes_tb__Syms* symsp, bool first);
} VL_ATTR_ALIGNED(VL_CACHE_LINE_BYTES);


#endif  // guard
