#Auto generated by Edalize

TOP_MODULE        := ascon_sim
VC_FILE           := lowrisc_dv_verilator_ascon_sim_0.1.vc
VERILATOR_OPTIONS := -DDISABLE_PRIM_CDC_RAND_DELAY --trace --trace-fst --trace-structs --trace-params --trace-max-array 1024 -CFLAGS "-std=c++17 -Wall -DVM_TRACE_FMT_FST -DTOPLEVEL_NAME=ascon_sim -g -O0" -LDFLAGS "-pthread -lutil -lelf" -Wall -Wno-PINCONNECTEMPTY -Wno-fatal
MAKE_OPTIONS      := 
