// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design implementation internals
// See Vascon_sim.h for the primary calling header

#include "verilated.h"
#include "verilated_dpi.h"

#include "Vascon_sim___024root.h"

VL_ATTR_COLD void Vascon_sim___024root___initial__TOP__6(Vascon_sim___024root* vlSelf);

VL_ATTR_COLD void Vascon_sim___024root___eval_initial(Vascon_sim___024root* vlSelf) {
    if (false && vlSelf) {}  // Prevent unused
    Vascon_sim__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vascon_sim___024root___eval_initial\n"); );
    // Body
    vlSelf->__Vclklast__TOP__clk_i = vlSelf->clk_i;
    vlSelf->__Vclklast__TOP__rst_ni = vlSelf->rst_ni;
    Vascon_sim___024root___initial__TOP__6(vlSelf);
    vlSelf->__Vm_traceActivity[1U] = 1U;
    vlSelf->__Vm_traceActivity[0U] = 1U;
}

VL_ATTR_COLD void Vascon_sim___024root___settle__TOP__4(Vascon_sim___024root* vlSelf);
VL_ATTR_COLD void Vascon_sim___024root___settle__TOP__5(Vascon_sim___024root* vlSelf);
VL_ATTR_COLD void Vascon_sim___024root___settle__TOP__7(Vascon_sim___024root* vlSelf);

VL_ATTR_COLD void Vascon_sim___024root___eval_settle(Vascon_sim___024root* vlSelf) {
    if (false && vlSelf) {}  // Prevent unused
    Vascon_sim__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vascon_sim___024root___eval_settle\n"); );
    // Body
    Vascon_sim___024root___settle__TOP__4(vlSelf);
    vlSelf->__Vm_traceActivity[1U] = 1U;
    vlSelf->__Vm_traceActivity[0U] = 1U;
    Vascon_sim___024root___settle__TOP__5(vlSelf);
    Vascon_sim___024root___settle__TOP__7(vlSelf);
}

VL_ATTR_COLD void Vascon_sim___024root___final(Vascon_sim___024root* vlSelf) {
    if (false && vlSelf) {}  // Prevent unused
    Vascon_sim__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vascon_sim___024root___final\n"); );
}

VL_ATTR_COLD void Vascon_sim___024root___ctor_var_reset(Vascon_sim___024root* vlSelf) {
    if (false && vlSelf) {}  // Prevent unused
    Vascon_sim__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vascon_sim___024root___ctor_var_reset\n"); );
    // Body
    vlSelf->clk_i = VL_RAND_RESET_I(1);
    vlSelf->rst_ni = VL_RAND_RESET_I(1);
    vlSelf->test_done_o = VL_RAND_RESET_I(1);
    vlSelf->test_passed_o = VL_RAND_RESET_I(1);
    VL_RAND_RESET_W(109, vlSelf->ascon_sim__DOT__tl_i);
    VL_RAND_RESET_W(66, vlSelf->ascon_sim__DOT__tl_o);
    vlSelf->ascon_sim__DOT__pop_response = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__delay_counter = 0;
    vlSelf->ascon_sim__DOT__test_passed_q = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__entropy_q = VL_RAND_RESET_I(32);
    vlSelf->ascon_sim__DOT____Vcellout__u_ascon__alert_tx_o = VL_RAND_RESET_I(4);
    vlSelf->ascon_sim__DOT____Vcellinp__u_ascon__edn_i = VL_RAND_RESET_Q(34);
    for (int __Vi0=0; __Vi0<10; ++__Vi0) {
        vlSelf->ascon_sim__DOT__gen_delay_logic__DOT__delay_done_q[__Vi0] = VL_RAND_RESET_I(1);
    }
    for (int __Vi0=0; __Vi0<61; ++__Vi0) {
        VL_RAND_RESET_W(109, vlSelf->ascon_sim__DOT__g_ascon_tl_ul_stim__DOT__stimulus[__Vi0]);
    }
    VL_RAND_RESET_W(109, vlSelf->ascon_sim__DOT__g_ascon_tl_ul_stim__DOT__stimulus_selected);
    VL_RAND_RESET_W(109, vlSelf->ascon_sim__DOT__g_ascon_tl_ul_stim__DOT__stimulus_data_intg);
    for (int __Vi0=0; __Vi0<12; ++__Vi0) {
        VL_RAND_RESET_W(66, vlSelf->ascon_sim__DOT__g_ascon_tl_ul_stim__DOT__response[__Vi0]);
    }
    vlSelf->ascon_sim__DOT__g_ascon_tl_ul_stim__DOT__stimulus_counter = 0;
    vlSelf->ascon_sim__DOT__g_ascon_tl_ul_stim__DOT__response_counter = 0;
    vlSelf->ascon_sim__DOT__g_ascon_tl_ul_stim__DOT__data_39_32_enc = VL_RAND_RESET_Q(39);
    vlSelf->ascon_sim__DOT__g_ascon_tl_ul_stim__DOT__u_tlul_cmd_intg_gen__DOT__cmd = VL_RAND_RESET_Q(43);
    vlSelf->ascon_sim__DOT__g_ascon_tl_ul_stim__DOT__u_tlul_cmd_intg_gen__DOT____Vcellout__u_cmd_gen__data_o = VL_RAND_RESET_Q(64);
    vlSelf->ascon_sim__DOT__g_ascon_tl_ul_stim__DOT__u_tlul_cmd_intg_gen__DOT____Vcellout__gen_data_intg__DOT__u_data_gen__data_o = VL_RAND_RESET_Q(39);
    VL_RAND_RESET_W(1274, vlSelf->ascon_sim__DOT__u_ascon__DOT__reg2hw);
    VL_RAND_RESET_W(1087, vlSelf->ascon_sim__DOT__u_ascon__DOT__hw2reg);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__edn_ack = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__alert = VL_RAND_RESET_I(2);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__shadowed_update_err = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT____Vcellout__u_prim_sync_reqack_data__dst_req_o = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__alert_test = VL_RAND_RESET_I(2);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__reg_we = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__reg_re = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__reg_error = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__addrmiss = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__wr_err = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__reg_rdata_next = VL_RAND_RESET_I(32);
    VL_RAND_RESET_W(66, vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__tl_reg_d2h);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__intg_err = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__reg_we_err = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__reg_we_check = VL_RAND_RESET_Q(47);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__err_q = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__alert_test_we = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__key_share0_0_we = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__key_share0_1_we = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__key_share0_2_we = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__key_share0_3_we = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__key_share1_0_we = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__key_share1_1_we = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__key_share1_2_we = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__key_share1_3_we = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__nonce_share0_0_we = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__nonce_share0_1_we = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__nonce_share0_2_we = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__nonce_share0_3_we = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__nonce_share1_0_we = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__nonce_share1_1_we = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__nonce_share1_2_we = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__nonce_share1_3_we = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__data_in_share0_0_we = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__data_in_share0_1_we = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__data_in_share0_2_we = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__data_in_share0_3_we = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__data_in_share1_0_we = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__data_in_share1_1_we = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__data_in_share1_2_we = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__data_in_share1_3_we = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__tag_in_0_we = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__tag_in_1_we = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__tag_in_2_we = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__tag_in_3_we = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__ctrl_shadowed_re = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__ctrl_shadowed_we = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__ctrl_shadowed_operation_storage_err = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__ctrl_shadowed_operation_update_err = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__ctrl_shadowed_ascon_variant_storage_err = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__ctrl_shadowed_ascon_variant_update_err = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__ctrl_shadowed_sideload_key_storage_err = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__ctrl_shadowed_sideload_key_update_err = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__ctrl_shadowed_masked_ad_input_storage_err = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__ctrl_shadowed_masked_ad_input_update_err = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__ctrl_shadowed_masked_msg_input_storage_err = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__ctrl_shadowed_masked_msg_input_update_err = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__ctrl_shadowed_no_msg_storage_err = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__ctrl_shadowed_no_msg_update_err = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__ctrl_shadowed_no_ad_storage_err = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__ctrl_shadowed_no_ad_update_err = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__ctrl_aux_shadowed_re = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__ctrl_aux_shadowed_manual_start_trigger_storage_err = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__ctrl_aux_shadowed_manual_start_trigger_update_err = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__ctrl_aux_shadowed_force_data_overwrite_storage_err = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__ctrl_aux_shadowed_force_data_overwrite_update_err = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__ctrl_aux_regwen_we = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__block_ctrl_shadowed_re = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__block_ctrl_shadowed_we = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__block_ctrl_shadowed_data_type_start_storage_err = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__block_ctrl_shadowed_data_type_start_update_err = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__block_ctrl_shadowed_data_type_last_storage_err = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__block_ctrl_shadowed_data_type_last_update_err = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__block_ctrl_shadowed_valid_bytes_storage_err = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__block_ctrl_shadowed_valid_bytes_update_err = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__trigger_we = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__fsm_state_regren_we = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__alert_test_flds_we = VL_RAND_RESET_I(2);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__tag_in_0_qe = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT____Vcellout__u_tag_in_0__q = VL_RAND_RESET_I(32);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__tag_in_1_qe = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT____Vcellout__u_tag_in_1__q = VL_RAND_RESET_I(32);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__tag_in_2_qe = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT____Vcellout__u_tag_in_2__q = VL_RAND_RESET_I(32);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__tag_in_3_qe = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT____Vcellout__u_tag_in_3__q = VL_RAND_RESET_I(32);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__ctrl_aux_shadowed_gated_we = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT____Vcellout__u_trigger_start__q = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT____Vcellout__u_trigger_wipe__q = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__addr_hit = VL_RAND_RESET_Q(47);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__rst_done = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_chk__DOT__err = VL_RAND_RESET_I(2);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_chk__DOT__cmd = VL_RAND_RESET_Q(43);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_chk__DOT____Vcellinp__u_chk__data_i = VL_RAND_RESET_Q(64);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_chk__DOT____Vcellinp__u_tlul_data_integ_dec__data_intg_i = VL_RAND_RESET_Q(39);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_chk__DOT__u_chk__DOT__data_o = VL_RAND_RESET_Q(57);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_chk__DOT__u_chk__DOT__syndrome_o = VL_RAND_RESET_I(7);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_chk__DOT__u_tlul_data_integ_dec__DOT__data_err = VL_RAND_RESET_I(2);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_chk__DOT__u_tlul_data_integ_dec__DOT__u_data_chk__DOT__data_o = VL_RAND_RESET_I(32);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_chk__DOT__u_tlul_data_integ_dec__DOT__u_data_chk__DOT__syndrome_o = VL_RAND_RESET_I(7);
    VL_RAND_RESET_W(127, vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_prim_reg_we_check__DOT__u_prim_onehot_check__DOT__or_tree);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_prim_reg_we_check__DOT__u_prim_onehot_check__DOT__or_tree__BRA__53__KET__ = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_prim_reg_we_check__DOT__u_prim_onehot_check__DOT__or_tree__BRA__52__KET__ = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_prim_reg_we_check__DOT__u_prim_onehot_check__DOT__or_tree__BRA__51__KET__ = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_prim_reg_we_check__DOT__u_prim_onehot_check__DOT__or_tree__BRA__50__KET__ = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_prim_reg_we_check__DOT__u_prim_onehot_check__DOT__or_tree__BRA__49__KET__ = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_prim_reg_we_check__DOT__u_prim_onehot_check__DOT__or_tree__BRA__48__KET__ = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_prim_reg_we_check__DOT__u_prim_onehot_check__DOT__or_tree__BRA__47__KET__ = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_prim_reg_we_check__DOT__u_prim_onehot_check__DOT__or_tree__BRA__46__KET__ = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_prim_reg_we_check__DOT__u_prim_onehot_check__DOT__or_tree__BRA__45__KET__ = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_prim_reg_we_check__DOT__u_prim_onehot_check__DOT__or_tree__BRA__44__KET__ = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_prim_reg_we_check__DOT__u_prim_onehot_check__DOT__or_tree__BRA__43__KET__ = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_prim_reg_we_check__DOT__u_prim_onehot_check__DOT__or_tree__BRA__42__KET__ = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_prim_reg_we_check__DOT__u_prim_onehot_check__DOT__or_tree__BRA__41__KET__ = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_prim_reg_we_check__DOT__u_prim_onehot_check__DOT__or_tree__BRA__40__KET__ = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_prim_reg_we_check__DOT__u_prim_onehot_check__DOT__or_tree__BRA__39__KET__ = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_prim_reg_we_check__DOT__u_prim_onehot_check__DOT__or_tree__BRA__38__KET__ = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_prim_reg_we_check__DOT__u_prim_onehot_check__DOT__or_tree__BRA__37__KET__ = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_prim_reg_we_check__DOT__u_prim_onehot_check__DOT__or_tree__BRA__36__KET__ = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_prim_reg_we_check__DOT__u_prim_onehot_check__DOT__or_tree__BRA__35__KET__ = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_prim_reg_we_check__DOT__u_prim_onehot_check__DOT__or_tree__BRA__34__KET__ = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_prim_reg_we_check__DOT__u_prim_onehot_check__DOT__or_tree__BRA__33__KET__ = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_prim_reg_we_check__DOT__u_prim_onehot_check__DOT__or_tree__BRA__32__KET__ = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_prim_reg_we_check__DOT__u_prim_onehot_check__DOT__or_tree__BRA__31__KET__ = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_prim_reg_we_check__DOT__u_prim_onehot_check__DOT__or_tree__BRA__0__KET__ = VL_RAND_RESET_I(1);
    VL_RAND_RESET_W(127, vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_prim_reg_we_check__DOT__u_prim_onehot_check__DOT__and_tree);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_prim_reg_we_check__DOT__u_prim_onehot_check__DOT__err_tree__BRA__53__KET__ = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_prim_reg_we_check__DOT__u_prim_onehot_check__DOT__err_tree__BRA__52__KET__ = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_prim_reg_we_check__DOT__u_prim_onehot_check__DOT__err_tree__BRA__51__KET__ = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_prim_reg_we_check__DOT__u_prim_onehot_check__DOT__err_tree__BRA__50__KET__ = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_prim_reg_we_check__DOT__u_prim_onehot_check__DOT__err_tree__BRA__49__KET__ = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_prim_reg_we_check__DOT__u_prim_onehot_check__DOT__err_tree__BRA__48__KET__ = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_prim_reg_we_check__DOT__u_prim_onehot_check__DOT__err_tree__BRA__47__KET__ = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_prim_reg_we_check__DOT__u_prim_onehot_check__DOT__err_tree__BRA__46__KET__ = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_prim_reg_we_check__DOT__u_prim_onehot_check__DOT__err_tree__BRA__45__KET__ = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_prim_reg_we_check__DOT__u_prim_onehot_check__DOT__err_tree__BRA__44__KET__ = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_prim_reg_we_check__DOT__u_prim_onehot_check__DOT__err_tree__BRA__43__KET__ = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_prim_reg_we_check__DOT__u_prim_onehot_check__DOT__err_tree__BRA__42__KET__ = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_prim_reg_we_check__DOT__u_prim_onehot_check__DOT__err_tree__BRA__41__KET__ = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_prim_reg_we_check__DOT__u_prim_onehot_check__DOT__err_tree__BRA__40__KET__ = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_prim_reg_we_check__DOT__u_prim_onehot_check__DOT__err_tree__BRA__39__KET__ = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_prim_reg_we_check__DOT__u_prim_onehot_check__DOT__err_tree__BRA__38__KET__ = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_prim_reg_we_check__DOT__u_prim_onehot_check__DOT__err_tree__BRA__37__KET__ = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_prim_reg_we_check__DOT__u_prim_onehot_check__DOT__err_tree__BRA__36__KET__ = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_prim_reg_we_check__DOT__u_prim_onehot_check__DOT__err_tree__BRA__35__KET__ = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_prim_reg_we_check__DOT__u_prim_onehot_check__DOT__err_tree__BRA__34__KET__ = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_prim_reg_we_check__DOT__u_prim_onehot_check__DOT__err_tree__BRA__33__KET__ = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_prim_reg_we_check__DOT__u_prim_onehot_check__DOT__err_tree__BRA__32__KET__ = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_prim_reg_we_check__DOT__u_prim_onehot_check__DOT__err_tree__BRA__31__KET__ = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_prim_reg_we_check__DOT__u_prim_onehot_check__DOT__err_tree__BRA__26__KET__ = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_prim_reg_we_check__DOT__u_prim_onehot_check__DOT__err_tree__BRA__25__KET__ = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_prim_reg_we_check__DOT__u_prim_onehot_check__DOT__err_tree__BRA__24__KET__ = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_prim_reg_we_check__DOT__u_prim_onehot_check__DOT__err_tree__BRA__23__KET__ = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_prim_reg_we_check__DOT__u_prim_onehot_check__DOT__err_tree__BRA__22__KET__ = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_prim_reg_we_check__DOT__u_prim_onehot_check__DOT__err_tree__BRA__21__KET__ = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_prim_reg_we_check__DOT__u_prim_onehot_check__DOT__err_tree__BRA__20__KET__ = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_prim_reg_we_check__DOT__u_prim_onehot_check__DOT__err_tree__BRA__19__KET__ = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_prim_reg_we_check__DOT__u_prim_onehot_check__DOT__err_tree__BRA__18__KET__ = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_prim_reg_we_check__DOT__u_prim_onehot_check__DOT__err_tree__BRA__17__KET__ = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_prim_reg_we_check__DOT__u_prim_onehot_check__DOT__err_tree__BRA__16__KET__ = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_prim_reg_we_check__DOT__u_prim_onehot_check__DOT__err_tree__BRA__15__KET__ = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_prim_reg_we_check__DOT__u_prim_onehot_check__DOT__err_tree__BRA__12__KET__ = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_prim_reg_we_check__DOT__u_prim_onehot_check__DOT__err_tree__BRA__11__KET__ = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_prim_reg_we_check__DOT__u_prim_onehot_check__DOT__err_tree__BRA__10__KET__ = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_prim_reg_we_check__DOT__u_prim_onehot_check__DOT__err_tree__BRA__9__KET__ = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_prim_reg_we_check__DOT__u_prim_onehot_check__DOT__err_tree__BRA__8__KET__ = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_prim_reg_we_check__DOT__u_prim_onehot_check__DOT__err_tree__BRA__7__KET__ = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_prim_reg_we_check__DOT__u_prim_onehot_check__DOT__err_tree__BRA__5__KET__ = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_prim_reg_we_check__DOT__u_prim_onehot_check__DOT__err_tree__BRA__4__KET__ = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_prim_reg_we_check__DOT__u_prim_onehot_check__DOT__err_tree__BRA__3__KET__ = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_prim_reg_we_check__DOT__u_prim_onehot_check__DOT__err_tree__BRA__1__KET__ = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_prim_reg_we_check__DOT__u_prim_onehot_check__DOT__err_tree__BRA__0__KET__ = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_prim_reg_we_check__DOT__u_prim_onehot_check__DOT__gen_no_addr_check_strict__DOT__unused_and_tree = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_rsp_intg_gen__DOT__gen_rsp_intg__DOT__rsp = VL_RAND_RESET_I(6);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_rsp_intg_gen__DOT____Vcellout__gen_rsp_intg__DOT__u_rsp_gen__data_o = VL_RAND_RESET_Q(64);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_rsp_intg_gen__DOT____Vcellout__gen_data_intg__DOT__u_tlul_data_integ_enc__data_intg_o = VL_RAND_RESET_Q(39);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_reg_if__DOT__outstanding_q = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_reg_if__DOT__a_ack = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_reg_if__DOT__rdata_q = VL_RAND_RESET_I(32);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_reg_if__DOT__error_q = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_reg_if__DOT__err_internal = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_reg_if__DOT__instr_error = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_reg_if__DOT__reqid_q = VL_RAND_RESET_I(8);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_reg_if__DOT__reqsz_q = VL_RAND_RESET_I(2);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_reg_if__DOT__rspop_q = VL_RAND_RESET_I(3);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_reg_if__DOT__rd_req = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_reg_if__DOT__wr_req = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_reg_if__DOT__u_err__DOT__instr_wr_err = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_reg_if__DOT__u_err__DOT__instr_type_err = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_reg_if__DOT__u_err__DOT__addr_sz_chk = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_reg_if__DOT__u_err__DOT__mask_chk = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_reg_if__DOT__u_err__DOT__fulldata_chk = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_tag_in_0__DOT__wr_data = VL_RAND_RESET_I(32);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_tag_in_1__DOT__wr_data = VL_RAND_RESET_I(32);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_tag_in_2__DOT__wr_data = VL_RAND_RESET_I(32);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_tag_in_3__DOT__wr_data = VL_RAND_RESET_I(32);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_ctrl_shadowed_operation__DOT__phase_q = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_ctrl_shadowed_operation__DOT__shadow_we = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_ctrl_shadowed_operation__DOT__committed_we = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_ctrl_shadowed_operation__DOT__shadow_wd = VL_RAND_RESET_I(3);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_ctrl_shadowed_operation__DOT__shadow_q = VL_RAND_RESET_I(3);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_ctrl_shadowed_operation__DOT__committed_q = VL_RAND_RESET_I(3);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_ctrl_shadowed_operation__DOT__wr_data = VL_RAND_RESET_I(3);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_ctrl_shadowed_operation__DOT__gen_shadow_reg_std__DOT__shadow_wr_data = VL_RAND_RESET_I(3);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_ctrl_shadowed_ascon_variant__DOT__phase_q = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_ctrl_shadowed_ascon_variant__DOT__shadow_we = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_ctrl_shadowed_ascon_variant__DOT__committed_we = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_ctrl_shadowed_ascon_variant__DOT__shadow_wd = VL_RAND_RESET_I(2);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_ctrl_shadowed_ascon_variant__DOT__shadow_q = VL_RAND_RESET_I(2);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_ctrl_shadowed_ascon_variant__DOT__committed_q = VL_RAND_RESET_I(2);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_ctrl_shadowed_ascon_variant__DOT__wr_data = VL_RAND_RESET_I(2);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_ctrl_shadowed_ascon_variant__DOT__gen_shadow_reg_std__DOT__shadow_wr_data = VL_RAND_RESET_I(2);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_ctrl_shadowed_sideload_key__DOT__phase_q = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_ctrl_shadowed_sideload_key__DOT__shadow_we = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_ctrl_shadowed_sideload_key__DOT__committed_we = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_ctrl_shadowed_sideload_key__DOT__shadow_wd = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_ctrl_shadowed_sideload_key__DOT__shadow_q = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_ctrl_shadowed_sideload_key__DOT__committed_q = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_ctrl_shadowed_sideload_key__DOT__wr_data = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_ctrl_shadowed_sideload_key__DOT__gen_shadow_reg_std__DOT__shadow_wr_data = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_ctrl_shadowed_masked_ad_input__DOT__phase_q = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_ctrl_shadowed_masked_ad_input__DOT__shadow_we = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_ctrl_shadowed_masked_ad_input__DOT__committed_we = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_ctrl_shadowed_masked_ad_input__DOT__shadow_wd = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_ctrl_shadowed_masked_ad_input__DOT__shadow_q = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_ctrl_shadowed_masked_ad_input__DOT__committed_q = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_ctrl_shadowed_masked_ad_input__DOT__wr_data = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_ctrl_shadowed_masked_ad_input__DOT__gen_shadow_reg_std__DOT__shadow_wr_data = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_ctrl_shadowed_masked_msg_input__DOT__phase_q = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_ctrl_shadowed_masked_msg_input__DOT__shadow_we = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_ctrl_shadowed_masked_msg_input__DOT__committed_we = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_ctrl_shadowed_masked_msg_input__DOT__shadow_wd = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_ctrl_shadowed_masked_msg_input__DOT__shadow_q = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_ctrl_shadowed_masked_msg_input__DOT__committed_q = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_ctrl_shadowed_masked_msg_input__DOT__wr_data = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_ctrl_shadowed_masked_msg_input__DOT__gen_shadow_reg_std__DOT__shadow_wr_data = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_ctrl_shadowed_no_msg__DOT__phase_q = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_ctrl_shadowed_no_msg__DOT__shadow_we = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_ctrl_shadowed_no_msg__DOT__committed_we = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_ctrl_shadowed_no_msg__DOT__shadow_wd = VL_RAND_RESET_I(4);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_ctrl_shadowed_no_msg__DOT__shadow_q = VL_RAND_RESET_I(4);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_ctrl_shadowed_no_msg__DOT__committed_q = VL_RAND_RESET_I(4);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_ctrl_shadowed_no_msg__DOT__wr_data = VL_RAND_RESET_I(4);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_ctrl_shadowed_no_msg__DOT__gen_shadow_reg_std__DOT__shadow_wr_data = VL_RAND_RESET_I(4);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_ctrl_shadowed_no_ad__DOT__phase_q = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_ctrl_shadowed_no_ad__DOT__shadow_we = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_ctrl_shadowed_no_ad__DOT__committed_we = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_ctrl_shadowed_no_ad__DOT__shadow_wd = VL_RAND_RESET_I(4);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_ctrl_shadowed_no_ad__DOT__shadow_q = VL_RAND_RESET_I(4);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_ctrl_shadowed_no_ad__DOT__committed_q = VL_RAND_RESET_I(4);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_ctrl_shadowed_no_ad__DOT__wr_data = VL_RAND_RESET_I(4);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_ctrl_shadowed_no_ad__DOT__gen_shadow_reg_std__DOT__shadow_wr_data = VL_RAND_RESET_I(4);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_ctrl_aux_shadowed_manual_start_trigger__DOT__phase_q = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_ctrl_aux_shadowed_manual_start_trigger__DOT__shadow_we = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_ctrl_aux_shadowed_manual_start_trigger__DOT__committed_we = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_ctrl_aux_shadowed_manual_start_trigger__DOT__shadow_wd = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_ctrl_aux_shadowed_manual_start_trigger__DOT__shadow_q = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_ctrl_aux_shadowed_manual_start_trigger__DOT__committed_q = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_ctrl_aux_shadowed_manual_start_trigger__DOT__wr_data = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_ctrl_aux_shadowed_manual_start_trigger__DOT__gen_shadow_reg_std__DOT__shadow_wr_data = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_ctrl_aux_shadowed_force_data_overwrite__DOT__phase_q = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_ctrl_aux_shadowed_force_data_overwrite__DOT__shadow_we = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_ctrl_aux_shadowed_force_data_overwrite__DOT__committed_we = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_ctrl_aux_shadowed_force_data_overwrite__DOT__shadow_wd = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_ctrl_aux_shadowed_force_data_overwrite__DOT__shadow_q = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_ctrl_aux_shadowed_force_data_overwrite__DOT__committed_q = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_ctrl_aux_shadowed_force_data_overwrite__DOT__wr_data = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_ctrl_aux_shadowed_force_data_overwrite__DOT__gen_shadow_reg_std__DOT__shadow_wr_data = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_ctrl_aux_regwen__DOT__q = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_ctrl_aux_regwen__DOT__wr_data = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_block_ctrl_shadowed_data_type_start__DOT__phase_q = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_block_ctrl_shadowed_data_type_start__DOT__shadow_we = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_block_ctrl_shadowed_data_type_start__DOT__committed_we = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_block_ctrl_shadowed_data_type_start__DOT__shadow_wd = VL_RAND_RESET_I(12);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_block_ctrl_shadowed_data_type_start__DOT__shadow_q = VL_RAND_RESET_I(12);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_block_ctrl_shadowed_data_type_start__DOT__committed_q = VL_RAND_RESET_I(12);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_block_ctrl_shadowed_data_type_start__DOT__wr_data = VL_RAND_RESET_I(12);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_block_ctrl_shadowed_data_type_start__DOT__gen_shadow_reg_std__DOT__shadow_wr_data = VL_RAND_RESET_I(12);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_block_ctrl_shadowed_data_type_last__DOT__phase_q = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_block_ctrl_shadowed_data_type_last__DOT__shadow_we = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_block_ctrl_shadowed_data_type_last__DOT__committed_we = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_block_ctrl_shadowed_data_type_last__DOT__shadow_wd = VL_RAND_RESET_I(12);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_block_ctrl_shadowed_data_type_last__DOT__shadow_q = VL_RAND_RESET_I(12);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_block_ctrl_shadowed_data_type_last__DOT__committed_q = VL_RAND_RESET_I(12);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_block_ctrl_shadowed_data_type_last__DOT__wr_data = VL_RAND_RESET_I(12);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_block_ctrl_shadowed_data_type_last__DOT__gen_shadow_reg_std__DOT__shadow_wr_data = VL_RAND_RESET_I(12);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_block_ctrl_shadowed_valid_bytes__DOT__phase_q = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_block_ctrl_shadowed_valid_bytes__DOT__shadow_we = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_block_ctrl_shadowed_valid_bytes__DOT__committed_we = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_block_ctrl_shadowed_valid_bytes__DOT__shadow_wd = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_block_ctrl_shadowed_valid_bytes__DOT__shadow_q = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_block_ctrl_shadowed_valid_bytes__DOT__committed_q = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_block_ctrl_shadowed_valid_bytes__DOT__wr_data = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_block_ctrl_shadowed_valid_bytes__DOT__gen_shadow_reg_std__DOT__shadow_wr_data = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_trigger_start__DOT__wr_en = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_trigger_start__DOT__wr_data = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_trigger_wipe__DOT__wr_en = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_trigger_wipe__DOT__wr_data = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_status_idle__DOT__q = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_status_stall__DOT__q = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_status_wait_edn__DOT__q = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_status_ascon_error__DOT__q = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_status_alert_recov_ctrl_update_err__DOT__q = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_status_alert_fatal_fault__DOT__q = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_output_valid_msg_valid__DOT__q = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_output_valid_tag_valid__DOT__q = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_output_valid_tag_comparison_valid__DOT__q = VL_RAND_RESET_I(2);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_fsm_state_regren__DOT__q = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_fsm_state_regren__DOT__wr_data = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_error_no_key__DOT__q = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_error_no_nonce__DOT__q = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_error_wrong_order__DOT__q = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_reg__DOT__u_error_flag_input_missmatch__DOT__q = VL_RAND_RESET_I(1);
    VL_RAND_RESET_W(128, vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__data_share0_in_d);
    VL_RAND_RESET_W(128, vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__data_share0_in_q);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__data_share0_in_new_d = VL_RAND_RESET_I(4);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__data_share0_in_new_q = VL_RAND_RESET_I(4);
    VL_RAND_RESET_W(128, vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__data_share1_in_d);
    VL_RAND_RESET_W(128, vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__data_share1_in_q);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__data_share1_in_new_d = VL_RAND_RESET_I(4);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__data_share1_in_new_q = VL_RAND_RESET_I(4);
    VL_RAND_RESET_W(128, vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__tag_in_q);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__tag_in_new_d = VL_RAND_RESET_I(4);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__tag_in_new_q = VL_RAND_RESET_I(4);
    VL_RAND_RESET_W(128, vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__nonce_share0_in_d);
    VL_RAND_RESET_W(128, vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__nonce_share0_in_q);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__nonce_share0_in_new_d = VL_RAND_RESET_I(4);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__nonce_share0_in_new_q = VL_RAND_RESET_I(4);
    VL_RAND_RESET_W(128, vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__nonce_share1_in_d);
    VL_RAND_RESET_W(128, vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__nonce_share1_in_q);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__nonce_share1_in_new_d = VL_RAND_RESET_I(4);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__nonce_share1_in_new_q = VL_RAND_RESET_I(4);
    VL_RAND_RESET_W(128, vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__key_share0_in_d);
    VL_RAND_RESET_W(128, vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__key_share0_in_q);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__key_share0_in_new_d = VL_RAND_RESET_I(4);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__key_share0_in_new_q = VL_RAND_RESET_I(4);
    VL_RAND_RESET_W(128, vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__key_share1_in_d);
    VL_RAND_RESET_W(128, vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__key_share1_in_q);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__key_share1_in_new_d = VL_RAND_RESET_I(4);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__key_share1_in_new_q = VL_RAND_RESET_I(4);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__start_ok = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__no_ad = VL_RAND_RESET_I(4);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__no_msg = VL_RAND_RESET_I(4);
    VL_RAND_RESET_W(128, vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__msg_out_d);
    VL_RAND_RESET_W(128, vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__msg_out_q);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__msg_out_valid = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__msg_out_we = VL_RAND_RESET_I(1);
    VL_RAND_RESET_W(128, vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__unused_msg_out_q);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__msg_out_read_d = VL_RAND_RESET_I(4);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__msg_out_read_q = VL_RAND_RESET_I(4);
    VL_RAND_RESET_W(128, vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__tag_out_d);
    VL_RAND_RESET_W(128, vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__tag_out_q);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__tag_out_valid = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__tag_out_we = VL_RAND_RESET_I(1);
    VL_RAND_RESET_W(128, vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__unused_tag_out_q);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__tag_out_read_d = VL_RAND_RESET_I(4);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__tag_out_read_q = VL_RAND_RESET_I(4);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__tag_out_ready = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__duplex_idle = VL_RAND_RESET_I(4);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__duplex_done = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__no_msg_mubi4invalid = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__no_ad_mubi4invalid = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__data_in_valid = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__data_in_ready = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__data_in_read = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__msg_out_reg_valid = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__tag_out_reg_valid = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__no_new_key = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__no_new_nonce = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__flag_error = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__order_error = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__msg_received_q = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__track_reset_msg_q = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__track_reset_tag_q = VL_RAND_RESET_I(1);
    VL_RAND_RESET_W(128, vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__key_in);
    VL_RAND_RESET_W(128, vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__data_in);
    VL_RAND_RESET_W(128, vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__nonce_in);
    VL_RAND_RESET_W(128, vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT____Vcellinp__ascon_duplex__data_in_i);
    VL_RAND_RESET_W(128, vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT____Vcellinp__ascon_duplex__nonce_i);
    VL_RAND_RESET_W(128, vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT____Vcellinp__ascon_duplex__key_i);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__sparse_fsm_error = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__set_round_counter = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__inc_round_counter = VL_RAND_RESET_I(1);
    VL_RAND_RESET_W(320, vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__ascon_state_q);
    VL_RAND_RESET_W(320, vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__ascon_state_d);
    VL_RAND_RESET_W(320, vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__state_from_round);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__fsm_state_d = VL_RAND_RESET_I(10);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__perm_offset = VL_RAND_RESET_I(4);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__complete_block = VL_RAND_RESET_I(4);
    VL_RAND_RESET_W(128, vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__valid_bytes_bit_mask);
    VL_RAND_RESET_W(128, vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__padding_byte_bit_mask);
    VL_RAND_RESET_W(128, vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__data_in_valid_bytes);
    VL_RAND_RESET_W(128, vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__data_out);
    VL_RAND_RESET_W(128, vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__data_in_padded);
    VL_RAND_RESET_W(128, vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__data_out_padded);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__sel_padding = VL_RAND_RESET_I(2);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__sel_mux_word0 = VL_RAND_RESET_I(2);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__sel_mux_word1 = VL_RAND_RESET_I(2);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__sel_mux_word2 = VL_RAND_RESET_I(2);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__sel_mux_word3 = VL_RAND_RESET_I(2);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__sel_mux_word4 = VL_RAND_RESET_I(2);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__sel_mux_key_word1 = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__sel_mux_key_word2 = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__sel_mux_key_word3 = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__sel_round_input = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__set_dom_sep = VL_RAND_RESET_I(1);
    VL_RAND_RESET_W(320, vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__xor_with_state);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__word4_dom_sep = VL_RAND_RESET_Q(64);
    VL_RAND_RESET_W(128, vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__data_to_duplex);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__mubi_error = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT____Vcellinp__u_prim_ascon_round__rcon_i = VL_RAND_RESET_I(8);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_round_counter__DOT__cnt_d = VL_RAND_RESET_I(8);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_round_counter__DOT__cnt_d_committed = VL_RAND_RESET_I(8);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_round_counter__DOT__cnt_q = VL_RAND_RESET_I(8);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_round_counter__DOT__err_q = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_round_counter__DOT__gen_cnts__BRA__0__KET____DOT__ext_cnt = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_round_counter__DOT__gen_cnts__BRA__0__KET____DOT__cnt_unforced_q = VL_RAND_RESET_I(4);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_round_counter__DOT__gen_cnts__BRA__1__KET____DOT__ext_cnt = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_round_counter__DOT__gen_cnts__BRA__1__KET____DOT__cnt_unforced_q = VL_RAND_RESET_I(4);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_state_regs__DOT__state_raw = VL_RAND_RESET_I(10);
    VL_RAND_RESET_W(320, vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__ark_w);
    VL_RAND_RESET_W(320, vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__sbox_w);
    for (int __Vi0=0; __Vi0<5; ++__Vi0) {
        vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__x_w[__Vi0] = VL_RAND_RESET_Q(64);
    }
    for (int __Vi0=0; __Vi0<64; ++__Vi0) {
        vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__xtranspose_w[__Vi0] = VL_RAND_RESET_I(5);
    }
    for (int __Vi0=0; __Vi0<64; ++__Vi0) {
        vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__ytranspose_w[__Vi0] = VL_RAND_RESET_I(5);
    }
    for (int __Vi0=0; __Vi0<5; ++__Vi0) {
        vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__y_w[__Vi0] = VL_RAND_RESET_Q(64);
    }
    for (int __Vi0=0; __Vi0<5; ++__Vi0) {
        vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__xl_w[__Vi0] = VL_RAND_RESET_Q(64);
    }
    for (int __Vi0=0; __Vi0<5; ++__Vi0) {
        vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__yl_w[__Vi0] = VL_RAND_RESET_Q(64);
    }
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__gen_sbox_transpose__BRA__0__KET____DOT__u_sbox__DOT__temp_w__0281__029 = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__gen_sbox_transpose__BRA__0__KET____DOT__u_sbox__DOT__temp_w__0282__029 = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__gen_sbox_transpose__BRA__1__KET____DOT__u_sbox__DOT__temp_w__0281__029 = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__gen_sbox_transpose__BRA__1__KET____DOT__u_sbox__DOT__temp_w__0282__029 = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__gen_sbox_transpose__BRA__2__KET____DOT__u_sbox__DOT__temp_w__0281__029 = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__gen_sbox_transpose__BRA__2__KET____DOT__u_sbox__DOT__temp_w__0282__029 = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__gen_sbox_transpose__BRA__3__KET____DOT__u_sbox__DOT__temp_w__0281__029 = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__gen_sbox_transpose__BRA__3__KET____DOT__u_sbox__DOT__temp_w__0282__029 = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__gen_sbox_transpose__BRA__4__KET____DOT__u_sbox__DOT__temp_w__0281__029 = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__gen_sbox_transpose__BRA__4__KET____DOT__u_sbox__DOT__temp_w__0282__029 = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__gen_sbox_transpose__BRA__5__KET____DOT__u_sbox__DOT__temp_w__0281__029 = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__gen_sbox_transpose__BRA__5__KET____DOT__u_sbox__DOT__temp_w__0282__029 = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__gen_sbox_transpose__BRA__6__KET____DOT__u_sbox__DOT__temp_w__0281__029 = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__gen_sbox_transpose__BRA__6__KET____DOT__u_sbox__DOT__temp_w__0282__029 = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__gen_sbox_transpose__BRA__7__KET____DOT__u_sbox__DOT__temp_w__0281__029 = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__gen_sbox_transpose__BRA__7__KET____DOT__u_sbox__DOT__temp_w__0282__029 = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__gen_sbox_transpose__BRA__8__KET____DOT__u_sbox__DOT__temp_w__0281__029 = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__gen_sbox_transpose__BRA__8__KET____DOT__u_sbox__DOT__temp_w__0282__029 = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__gen_sbox_transpose__BRA__9__KET____DOT__u_sbox__DOT__temp_w__0281__029 = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__gen_sbox_transpose__BRA__9__KET____DOT__u_sbox__DOT__temp_w__0282__029 = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__gen_sbox_transpose__BRA__10__KET____DOT__u_sbox__DOT__temp_w__0281__029 = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__gen_sbox_transpose__BRA__10__KET____DOT__u_sbox__DOT__temp_w__0282__029 = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__gen_sbox_transpose__BRA__11__KET____DOT__u_sbox__DOT__temp_w__0281__029 = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__gen_sbox_transpose__BRA__11__KET____DOT__u_sbox__DOT__temp_w__0282__029 = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__gen_sbox_transpose__BRA__12__KET____DOT__u_sbox__DOT__temp_w__0281__029 = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__gen_sbox_transpose__BRA__12__KET____DOT__u_sbox__DOT__temp_w__0282__029 = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__gen_sbox_transpose__BRA__13__KET____DOT__u_sbox__DOT__temp_w__0281__029 = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__gen_sbox_transpose__BRA__13__KET____DOT__u_sbox__DOT__temp_w__0282__029 = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__gen_sbox_transpose__BRA__14__KET____DOT__u_sbox__DOT__temp_w__0281__029 = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__gen_sbox_transpose__BRA__14__KET____DOT__u_sbox__DOT__temp_w__0282__029 = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__gen_sbox_transpose__BRA__15__KET____DOT__u_sbox__DOT__temp_w__0281__029 = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__gen_sbox_transpose__BRA__15__KET____DOT__u_sbox__DOT__temp_w__0282__029 = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__gen_sbox_transpose__BRA__16__KET____DOT__u_sbox__DOT__temp_w__0281__029 = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__gen_sbox_transpose__BRA__16__KET____DOT__u_sbox__DOT__temp_w__0282__029 = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__gen_sbox_transpose__BRA__17__KET____DOT__u_sbox__DOT__temp_w__0281__029 = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__gen_sbox_transpose__BRA__17__KET____DOT__u_sbox__DOT__temp_w__0282__029 = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__gen_sbox_transpose__BRA__18__KET____DOT__u_sbox__DOT__temp_w__0281__029 = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__gen_sbox_transpose__BRA__18__KET____DOT__u_sbox__DOT__temp_w__0282__029 = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__gen_sbox_transpose__BRA__19__KET____DOT__u_sbox__DOT__temp_w__0281__029 = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__gen_sbox_transpose__BRA__19__KET____DOT__u_sbox__DOT__temp_w__0282__029 = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__gen_sbox_transpose__BRA__20__KET____DOT__u_sbox__DOT__temp_w__0281__029 = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__gen_sbox_transpose__BRA__20__KET____DOT__u_sbox__DOT__temp_w__0282__029 = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__gen_sbox_transpose__BRA__21__KET____DOT__u_sbox__DOT__temp_w__0281__029 = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__gen_sbox_transpose__BRA__21__KET____DOT__u_sbox__DOT__temp_w__0282__029 = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__gen_sbox_transpose__BRA__22__KET____DOT__u_sbox__DOT__temp_w__0281__029 = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__gen_sbox_transpose__BRA__22__KET____DOT__u_sbox__DOT__temp_w__0282__029 = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__gen_sbox_transpose__BRA__23__KET____DOT__u_sbox__DOT__temp_w__0281__029 = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__gen_sbox_transpose__BRA__23__KET____DOT__u_sbox__DOT__temp_w__0282__029 = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__gen_sbox_transpose__BRA__24__KET____DOT__u_sbox__DOT__temp_w__0281__029 = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__gen_sbox_transpose__BRA__24__KET____DOT__u_sbox__DOT__temp_w__0282__029 = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__gen_sbox_transpose__BRA__25__KET____DOT__u_sbox__DOT__temp_w__0281__029 = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__gen_sbox_transpose__BRA__25__KET____DOT__u_sbox__DOT__temp_w__0282__029 = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__gen_sbox_transpose__BRA__26__KET____DOT__u_sbox__DOT__temp_w__0281__029 = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__gen_sbox_transpose__BRA__26__KET____DOT__u_sbox__DOT__temp_w__0282__029 = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__gen_sbox_transpose__BRA__27__KET____DOT__u_sbox__DOT__temp_w__0281__029 = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__gen_sbox_transpose__BRA__27__KET____DOT__u_sbox__DOT__temp_w__0282__029 = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__gen_sbox_transpose__BRA__28__KET____DOT__u_sbox__DOT__temp_w__0281__029 = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__gen_sbox_transpose__BRA__28__KET____DOT__u_sbox__DOT__temp_w__0282__029 = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__gen_sbox_transpose__BRA__29__KET____DOT__u_sbox__DOT__temp_w__0281__029 = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__gen_sbox_transpose__BRA__29__KET____DOT__u_sbox__DOT__temp_w__0282__029 = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__gen_sbox_transpose__BRA__30__KET____DOT__u_sbox__DOT__temp_w__0281__029 = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__gen_sbox_transpose__BRA__30__KET____DOT__u_sbox__DOT__temp_w__0282__029 = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__gen_sbox_transpose__BRA__31__KET____DOT__u_sbox__DOT__temp_w__0281__029 = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__gen_sbox_transpose__BRA__31__KET____DOT__u_sbox__DOT__temp_w__0282__029 = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__gen_sbox_transpose__BRA__32__KET____DOT__u_sbox__DOT__temp_w__0281__029 = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__gen_sbox_transpose__BRA__32__KET____DOT__u_sbox__DOT__temp_w__0282__029 = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__gen_sbox_transpose__BRA__33__KET____DOT__u_sbox__DOT__temp_w__0281__029 = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__gen_sbox_transpose__BRA__33__KET____DOT__u_sbox__DOT__temp_w__0282__029 = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__gen_sbox_transpose__BRA__34__KET____DOT__u_sbox__DOT__temp_w__0281__029 = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__gen_sbox_transpose__BRA__34__KET____DOT__u_sbox__DOT__temp_w__0282__029 = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__gen_sbox_transpose__BRA__35__KET____DOT__u_sbox__DOT__temp_w__0281__029 = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__gen_sbox_transpose__BRA__35__KET____DOT__u_sbox__DOT__temp_w__0282__029 = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__gen_sbox_transpose__BRA__36__KET____DOT__u_sbox__DOT__temp_w__0281__029 = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__gen_sbox_transpose__BRA__36__KET____DOT__u_sbox__DOT__temp_w__0282__029 = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__gen_sbox_transpose__BRA__37__KET____DOT__u_sbox__DOT__temp_w__0281__029 = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__gen_sbox_transpose__BRA__37__KET____DOT__u_sbox__DOT__temp_w__0282__029 = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__gen_sbox_transpose__BRA__38__KET____DOT__u_sbox__DOT__temp_w__0281__029 = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__gen_sbox_transpose__BRA__38__KET____DOT__u_sbox__DOT__temp_w__0282__029 = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__gen_sbox_transpose__BRA__39__KET____DOT__u_sbox__DOT__temp_w__0281__029 = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__gen_sbox_transpose__BRA__39__KET____DOT__u_sbox__DOT__temp_w__0282__029 = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__gen_sbox_transpose__BRA__40__KET____DOT__u_sbox__DOT__temp_w__0281__029 = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__gen_sbox_transpose__BRA__40__KET____DOT__u_sbox__DOT__temp_w__0282__029 = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__gen_sbox_transpose__BRA__41__KET____DOT__u_sbox__DOT__temp_w__0281__029 = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__gen_sbox_transpose__BRA__41__KET____DOT__u_sbox__DOT__temp_w__0282__029 = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__gen_sbox_transpose__BRA__42__KET____DOT__u_sbox__DOT__temp_w__0281__029 = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__gen_sbox_transpose__BRA__42__KET____DOT__u_sbox__DOT__temp_w__0282__029 = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__gen_sbox_transpose__BRA__43__KET____DOT__u_sbox__DOT__temp_w__0281__029 = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__gen_sbox_transpose__BRA__43__KET____DOT__u_sbox__DOT__temp_w__0282__029 = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__gen_sbox_transpose__BRA__44__KET____DOT__u_sbox__DOT__temp_w__0281__029 = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__gen_sbox_transpose__BRA__44__KET____DOT__u_sbox__DOT__temp_w__0282__029 = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__gen_sbox_transpose__BRA__45__KET____DOT__u_sbox__DOT__temp_w__0281__029 = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__gen_sbox_transpose__BRA__45__KET____DOT__u_sbox__DOT__temp_w__0282__029 = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__gen_sbox_transpose__BRA__46__KET____DOT__u_sbox__DOT__temp_w__0281__029 = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__gen_sbox_transpose__BRA__46__KET____DOT__u_sbox__DOT__temp_w__0282__029 = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__gen_sbox_transpose__BRA__47__KET____DOT__u_sbox__DOT__temp_w__0281__029 = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__gen_sbox_transpose__BRA__47__KET____DOT__u_sbox__DOT__temp_w__0282__029 = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__gen_sbox_transpose__BRA__48__KET____DOT__u_sbox__DOT__temp_w__0281__029 = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__gen_sbox_transpose__BRA__48__KET____DOT__u_sbox__DOT__temp_w__0282__029 = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__gen_sbox_transpose__BRA__49__KET____DOT__u_sbox__DOT__temp_w__0281__029 = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__gen_sbox_transpose__BRA__49__KET____DOT__u_sbox__DOT__temp_w__0282__029 = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__gen_sbox_transpose__BRA__50__KET____DOT__u_sbox__DOT__temp_w__0281__029 = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__gen_sbox_transpose__BRA__50__KET____DOT__u_sbox__DOT__temp_w__0282__029 = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__gen_sbox_transpose__BRA__51__KET____DOT__u_sbox__DOT__temp_w__0281__029 = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__gen_sbox_transpose__BRA__51__KET____DOT__u_sbox__DOT__temp_w__0282__029 = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__gen_sbox_transpose__BRA__52__KET____DOT__u_sbox__DOT__temp_w__0281__029 = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__gen_sbox_transpose__BRA__52__KET____DOT__u_sbox__DOT__temp_w__0282__029 = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__gen_sbox_transpose__BRA__53__KET____DOT__u_sbox__DOT__temp_w__0281__029 = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__gen_sbox_transpose__BRA__53__KET____DOT__u_sbox__DOT__temp_w__0282__029 = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__gen_sbox_transpose__BRA__54__KET____DOT__u_sbox__DOT__temp_w__0281__029 = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__gen_sbox_transpose__BRA__54__KET____DOT__u_sbox__DOT__temp_w__0282__029 = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__gen_sbox_transpose__BRA__55__KET____DOT__u_sbox__DOT__temp_w__0281__029 = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__gen_sbox_transpose__BRA__55__KET____DOT__u_sbox__DOT__temp_w__0282__029 = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__gen_sbox_transpose__BRA__56__KET____DOT__u_sbox__DOT__temp_w__0281__029 = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__gen_sbox_transpose__BRA__56__KET____DOT__u_sbox__DOT__temp_w__0282__029 = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__gen_sbox_transpose__BRA__57__KET____DOT__u_sbox__DOT__temp_w__0281__029 = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__gen_sbox_transpose__BRA__57__KET____DOT__u_sbox__DOT__temp_w__0282__029 = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__gen_sbox_transpose__BRA__58__KET____DOT__u_sbox__DOT__temp_w__0281__029 = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__gen_sbox_transpose__BRA__58__KET____DOT__u_sbox__DOT__temp_w__0282__029 = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__gen_sbox_transpose__BRA__59__KET____DOT__u_sbox__DOT__temp_w__0281__029 = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__gen_sbox_transpose__BRA__59__KET____DOT__u_sbox__DOT__temp_w__0282__029 = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__gen_sbox_transpose__BRA__60__KET____DOT__u_sbox__DOT__temp_w__0281__029 = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__gen_sbox_transpose__BRA__60__KET____DOT__u_sbox__DOT__temp_w__0282__029 = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__gen_sbox_transpose__BRA__61__KET____DOT__u_sbox__DOT__temp_w__0281__029 = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__gen_sbox_transpose__BRA__61__KET____DOT__u_sbox__DOT__temp_w__0282__029 = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__gen_sbox_transpose__BRA__62__KET____DOT__u_sbox__DOT__temp_w__0281__029 = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__gen_sbox_transpose__BRA__62__KET____DOT__u_sbox__DOT__temp_w__0282__029 = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__gen_sbox_transpose__BRA__63__KET____DOT__u_sbox__DOT__temp_w__0281__029 = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__ascon_core__DOT__ascon_duplex__DOT__u_prim_ascon_round__DOT__gen_sbox_transpose__BRA__63__KET____DOT__u_sbox__DOT__temp_w__0282__029 = VL_RAND_RESET_I(5);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_prim_sync_reqack_data__DOT__u_prim_sync_reqack__DOT__gen_nrz_hs_protocol__DOT__src_fsm_ns = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_prim_sync_reqack_data__DOT__u_prim_sync_reqack__DOT__gen_nrz_hs_protocol__DOT__src_fsm_cs = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_prim_sync_reqack_data__DOT__u_prim_sync_reqack__DOT__gen_nrz_hs_protocol__DOT__dst_fsm_ns = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_prim_sync_reqack_data__DOT__u_prim_sync_reqack__DOT__gen_nrz_hs_protocol__DOT__dst_fsm_cs = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_prim_sync_reqack_data__DOT__u_prim_sync_reqack__DOT__gen_nrz_hs_protocol__DOT__src_req_d = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_prim_sync_reqack_data__DOT__u_prim_sync_reqack__DOT__gen_nrz_hs_protocol__DOT__src_req_q = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_prim_sync_reqack_data__DOT__u_prim_sync_reqack__DOT__gen_nrz_hs_protocol__DOT__src_ack = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_prim_sync_reqack_data__DOT__u_prim_sync_reqack__DOT__gen_nrz_hs_protocol__DOT__dst_ack_d = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_prim_sync_reqack_data__DOT__u_prim_sync_reqack__DOT__gen_nrz_hs_protocol__DOT__dst_ack_q = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_prim_sync_reqack_data__DOT__u_prim_sync_reqack__DOT__gen_nrz_hs_protocol__DOT__dst_req = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_prim_sync_reqack_data__DOT__u_prim_sync_reqack__DOT__gen_nrz_hs_protocol__DOT__dst_handshake = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_prim_sync_reqack_data__DOT__u_prim_sync_reqack__DOT__gen_nrz_hs_protocol__DOT__req_sync__DOT__intq = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__u_prim_sync_reqack_data__DOT__u_prim_sync_reqack__DOT__gen_nrz_hs_protocol__DOT__ack_sync__DOT__intq = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__gen_alert_tx__BRA__0__KET____DOT__u_prim_alert_sender__DOT__ping_sigint = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__gen_alert_tx__BRA__0__KET____DOT__u_prim_alert_sender__DOT__ack_sigint = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__gen_alert_tx__BRA__0__KET____DOT__u_prim_alert_sender__DOT__state_d = VL_RAND_RESET_I(3);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__gen_alert_tx__BRA__0__KET____DOT__u_prim_alert_sender__DOT__state_q = VL_RAND_RESET_I(3);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__gen_alert_tx__BRA__0__KET____DOT__u_prim_alert_sender__DOT__alert_pd = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__gen_alert_tx__BRA__0__KET____DOT__u_prim_alert_sender__DOT__alert_nd = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__gen_alert_tx__BRA__0__KET____DOT__u_prim_alert_sender__DOT__alert_set_q = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__gen_alert_tx__BRA__0__KET____DOT__u_prim_alert_sender__DOT__alert_clr = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__gen_alert_tx__BRA__0__KET____DOT__u_prim_alert_sender__DOT__alert_test_set_q = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__gen_alert_tx__BRA__0__KET____DOT__u_prim_alert_sender__DOT__ping_set_q = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__gen_alert_tx__BRA__0__KET____DOT__u_prim_alert_sender__DOT__ping_clr = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__gen_alert_tx__BRA__0__KET____DOT__u_prim_alert_sender__DOT__alert_req_trigger = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__gen_alert_tx__BRA__0__KET____DOT__u_prim_alert_sender__DOT__alert_test_trigger = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__gen_alert_tx__BRA__0__KET____DOT__u_prim_alert_sender__DOT__ping_trigger = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__gen_alert_tx__BRA__0__KET____DOT__u_prim_alert_sender__DOT____Vcellout__u_prim_flop_alert__q_o = VL_RAND_RESET_I(2);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__gen_alert_tx__BRA__0__KET____DOT__u_prim_alert_sender__DOT__u_decode_ping__DOT__rise_o = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__gen_alert_tx__BRA__0__KET____DOT__u_prim_alert_sender__DOT__u_decode_ping__DOT__fall_o = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__gen_alert_tx__BRA__0__KET____DOT__u_prim_alert_sender__DOT__u_decode_ping__DOT__level_d = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__gen_alert_tx__BRA__0__KET____DOT__u_prim_alert_sender__DOT__u_decode_ping__DOT__level_q = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__gen_alert_tx__BRA__0__KET____DOT__u_prim_alert_sender__DOT__u_decode_ping__DOT__gen_async__DOT__state_d = VL_RAND_RESET_I(2);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__gen_alert_tx__BRA__0__KET____DOT__u_prim_alert_sender__DOT__u_decode_ping__DOT__gen_async__DOT__state_q = VL_RAND_RESET_I(2);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__gen_alert_tx__BRA__0__KET____DOT__u_prim_alert_sender__DOT__u_decode_ping__DOT__gen_async__DOT__diff_p_edge = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__gen_alert_tx__BRA__0__KET____DOT__u_prim_alert_sender__DOT__u_decode_ping__DOT__gen_async__DOT__diff_n_edge = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__gen_alert_tx__BRA__0__KET____DOT__u_prim_alert_sender__DOT__u_decode_ping__DOT__gen_async__DOT__diff_check_ok = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__gen_alert_tx__BRA__0__KET____DOT__u_prim_alert_sender__DOT__u_decode_ping__DOT__gen_async__DOT__diff_pq = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__gen_alert_tx__BRA__0__KET____DOT__u_prim_alert_sender__DOT__u_decode_ping__DOT__gen_async__DOT__diff_nq = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__gen_alert_tx__BRA__0__KET____DOT__u_prim_alert_sender__DOT__u_decode_ping__DOT__gen_async__DOT__diff_pd = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__gen_alert_tx__BRA__0__KET____DOT__u_prim_alert_sender__DOT__u_decode_ping__DOT__gen_async__DOT__diff_nd = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__gen_alert_tx__BRA__0__KET____DOT__u_prim_alert_sender__DOT__u_decode_ping__DOT__gen_async__DOT__skew_cnt_d = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__gen_alert_tx__BRA__0__KET____DOT__u_prim_alert_sender__DOT__u_decode_ping__DOT__gen_async__DOT__skew_cnt_q = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__gen_alert_tx__BRA__0__KET____DOT__u_prim_alert_sender__DOT__u_decode_ping__DOT__gen_async__DOT__i_sync_p__DOT__intq = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__gen_alert_tx__BRA__0__KET____DOT__u_prim_alert_sender__DOT__u_decode_ping__DOT__gen_async__DOT__i_sync_n__DOT__intq = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__gen_alert_tx__BRA__0__KET____DOT__u_prim_alert_sender__DOT__u_decode_ack__DOT__rise_o = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__gen_alert_tx__BRA__0__KET____DOT__u_prim_alert_sender__DOT__u_decode_ack__DOT__fall_o = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__gen_alert_tx__BRA__0__KET____DOT__u_prim_alert_sender__DOT__u_decode_ack__DOT__level_d = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__gen_alert_tx__BRA__0__KET____DOT__u_prim_alert_sender__DOT__u_decode_ack__DOT__level_q = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__gen_alert_tx__BRA__0__KET____DOT__u_prim_alert_sender__DOT__u_decode_ack__DOT__gen_async__DOT__state_d = VL_RAND_RESET_I(2);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__gen_alert_tx__BRA__0__KET____DOT__u_prim_alert_sender__DOT__u_decode_ack__DOT__gen_async__DOT__state_q = VL_RAND_RESET_I(2);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__gen_alert_tx__BRA__0__KET____DOT__u_prim_alert_sender__DOT__u_decode_ack__DOT__gen_async__DOT__diff_p_edge = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__gen_alert_tx__BRA__0__KET____DOT__u_prim_alert_sender__DOT__u_decode_ack__DOT__gen_async__DOT__diff_n_edge = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__gen_alert_tx__BRA__0__KET____DOT__u_prim_alert_sender__DOT__u_decode_ack__DOT__gen_async__DOT__diff_check_ok = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__gen_alert_tx__BRA__0__KET____DOT__u_prim_alert_sender__DOT__u_decode_ack__DOT__gen_async__DOT__diff_pq = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__gen_alert_tx__BRA__0__KET____DOT__u_prim_alert_sender__DOT__u_decode_ack__DOT__gen_async__DOT__diff_nq = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__gen_alert_tx__BRA__0__KET____DOT__u_prim_alert_sender__DOT__u_decode_ack__DOT__gen_async__DOT__diff_pd = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__gen_alert_tx__BRA__0__KET____DOT__u_prim_alert_sender__DOT__u_decode_ack__DOT__gen_async__DOT__diff_nd = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__gen_alert_tx__BRA__0__KET____DOT__u_prim_alert_sender__DOT__u_decode_ack__DOT__gen_async__DOT__skew_cnt_d = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__gen_alert_tx__BRA__0__KET____DOT__u_prim_alert_sender__DOT__u_decode_ack__DOT__gen_async__DOT__skew_cnt_q = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__gen_alert_tx__BRA__0__KET____DOT__u_prim_alert_sender__DOT__u_decode_ack__DOT__gen_async__DOT__i_sync_p__DOT__intq = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__gen_alert_tx__BRA__0__KET____DOT__u_prim_alert_sender__DOT__u_decode_ack__DOT__gen_async__DOT__i_sync_n__DOT__intq = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__gen_alert_tx__BRA__1__KET____DOT__u_prim_alert_sender__DOT__ping_sigint = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__gen_alert_tx__BRA__1__KET____DOT__u_prim_alert_sender__DOT__ack_sigint = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__gen_alert_tx__BRA__1__KET____DOT__u_prim_alert_sender__DOT__state_d = VL_RAND_RESET_I(3);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__gen_alert_tx__BRA__1__KET____DOT__u_prim_alert_sender__DOT__state_q = VL_RAND_RESET_I(3);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__gen_alert_tx__BRA__1__KET____DOT__u_prim_alert_sender__DOT__alert_pd = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__gen_alert_tx__BRA__1__KET____DOT__u_prim_alert_sender__DOT__alert_nd = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__gen_alert_tx__BRA__1__KET____DOT__u_prim_alert_sender__DOT__alert_set_q = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__gen_alert_tx__BRA__1__KET____DOT__u_prim_alert_sender__DOT__alert_clr = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__gen_alert_tx__BRA__1__KET____DOT__u_prim_alert_sender__DOT__alert_test_set_q = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__gen_alert_tx__BRA__1__KET____DOT__u_prim_alert_sender__DOT__ping_set_q = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__gen_alert_tx__BRA__1__KET____DOT__u_prim_alert_sender__DOT__ping_clr = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__gen_alert_tx__BRA__1__KET____DOT__u_prim_alert_sender__DOT__alert_req_trigger = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__gen_alert_tx__BRA__1__KET____DOT__u_prim_alert_sender__DOT__alert_test_trigger = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__gen_alert_tx__BRA__1__KET____DOT__u_prim_alert_sender__DOT__ping_trigger = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__gen_alert_tx__BRA__1__KET____DOT__u_prim_alert_sender__DOT____Vcellout__u_prim_flop_alert__q_o = VL_RAND_RESET_I(2);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__gen_alert_tx__BRA__1__KET____DOT__u_prim_alert_sender__DOT__u_decode_ping__DOT__rise_o = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__gen_alert_tx__BRA__1__KET____DOT__u_prim_alert_sender__DOT__u_decode_ping__DOT__fall_o = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__gen_alert_tx__BRA__1__KET____DOT__u_prim_alert_sender__DOT__u_decode_ping__DOT__level_d = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__gen_alert_tx__BRA__1__KET____DOT__u_prim_alert_sender__DOT__u_decode_ping__DOT__level_q = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__gen_alert_tx__BRA__1__KET____DOT__u_prim_alert_sender__DOT__u_decode_ping__DOT__gen_async__DOT__state_d = VL_RAND_RESET_I(2);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__gen_alert_tx__BRA__1__KET____DOT__u_prim_alert_sender__DOT__u_decode_ping__DOT__gen_async__DOT__state_q = VL_RAND_RESET_I(2);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__gen_alert_tx__BRA__1__KET____DOT__u_prim_alert_sender__DOT__u_decode_ping__DOT__gen_async__DOT__diff_p_edge = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__gen_alert_tx__BRA__1__KET____DOT__u_prim_alert_sender__DOT__u_decode_ping__DOT__gen_async__DOT__diff_n_edge = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__gen_alert_tx__BRA__1__KET____DOT__u_prim_alert_sender__DOT__u_decode_ping__DOT__gen_async__DOT__diff_check_ok = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__gen_alert_tx__BRA__1__KET____DOT__u_prim_alert_sender__DOT__u_decode_ping__DOT__gen_async__DOT__diff_pq = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__gen_alert_tx__BRA__1__KET____DOT__u_prim_alert_sender__DOT__u_decode_ping__DOT__gen_async__DOT__diff_nq = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__gen_alert_tx__BRA__1__KET____DOT__u_prim_alert_sender__DOT__u_decode_ping__DOT__gen_async__DOT__diff_pd = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__gen_alert_tx__BRA__1__KET____DOT__u_prim_alert_sender__DOT__u_decode_ping__DOT__gen_async__DOT__diff_nd = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__gen_alert_tx__BRA__1__KET____DOT__u_prim_alert_sender__DOT__u_decode_ping__DOT__gen_async__DOT__skew_cnt_d = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__gen_alert_tx__BRA__1__KET____DOT__u_prim_alert_sender__DOT__u_decode_ping__DOT__gen_async__DOT__skew_cnt_q = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__gen_alert_tx__BRA__1__KET____DOT__u_prim_alert_sender__DOT__u_decode_ping__DOT__gen_async__DOT__i_sync_p__DOT__intq = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__gen_alert_tx__BRA__1__KET____DOT__u_prim_alert_sender__DOT__u_decode_ping__DOT__gen_async__DOT__i_sync_n__DOT__intq = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__gen_alert_tx__BRA__1__KET____DOT__u_prim_alert_sender__DOT__u_decode_ack__DOT__rise_o = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__gen_alert_tx__BRA__1__KET____DOT__u_prim_alert_sender__DOT__u_decode_ack__DOT__fall_o = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__gen_alert_tx__BRA__1__KET____DOT__u_prim_alert_sender__DOT__u_decode_ack__DOT__level_d = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__gen_alert_tx__BRA__1__KET____DOT__u_prim_alert_sender__DOT__u_decode_ack__DOT__level_q = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__gen_alert_tx__BRA__1__KET____DOT__u_prim_alert_sender__DOT__u_decode_ack__DOT__gen_async__DOT__state_d = VL_RAND_RESET_I(2);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__gen_alert_tx__BRA__1__KET____DOT__u_prim_alert_sender__DOT__u_decode_ack__DOT__gen_async__DOT__state_q = VL_RAND_RESET_I(2);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__gen_alert_tx__BRA__1__KET____DOT__u_prim_alert_sender__DOT__u_decode_ack__DOT__gen_async__DOT__diff_p_edge = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__gen_alert_tx__BRA__1__KET____DOT__u_prim_alert_sender__DOT__u_decode_ack__DOT__gen_async__DOT__diff_n_edge = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__gen_alert_tx__BRA__1__KET____DOT__u_prim_alert_sender__DOT__u_decode_ack__DOT__gen_async__DOT__diff_check_ok = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__gen_alert_tx__BRA__1__KET____DOT__u_prim_alert_sender__DOT__u_decode_ack__DOT__gen_async__DOT__diff_pq = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__gen_alert_tx__BRA__1__KET____DOT__u_prim_alert_sender__DOT__u_decode_ack__DOT__gen_async__DOT__diff_nq = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__gen_alert_tx__BRA__1__KET____DOT__u_prim_alert_sender__DOT__u_decode_ack__DOT__gen_async__DOT__diff_pd = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__gen_alert_tx__BRA__1__KET____DOT__u_prim_alert_sender__DOT__u_decode_ack__DOT__gen_async__DOT__diff_nd = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__gen_alert_tx__BRA__1__KET____DOT__u_prim_alert_sender__DOT__u_decode_ack__DOT__gen_async__DOT__skew_cnt_d = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__gen_alert_tx__BRA__1__KET____DOT__u_prim_alert_sender__DOT__u_decode_ack__DOT__gen_async__DOT__skew_cnt_q = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__gen_alert_tx__BRA__1__KET____DOT__u_prim_alert_sender__DOT__u_decode_ack__DOT__gen_async__DOT__i_sync_p__DOT__intq = VL_RAND_RESET_I(1);
    vlSelf->ascon_sim__DOT__u_ascon__DOT__gen_alert_tx__BRA__1__KET____DOT__u_prim_alert_sender__DOT__u_decode_ack__DOT__gen_async__DOT__i_sync_n__DOT__intq = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_extract_h2d_cmd_intg__73__payload = VL_RAND_RESET_Q(43);
    vlSelf->__Vfunc_extract_h2d_cmd_intg__74__payload = VL_RAND_RESET_Q(43);
    VL_RAND_RESET_W(128, vlSelf->__Vfunc_swap_endianess_byte__89__vector_out);
    VL_RAND_RESET_W(128, vlSelf->__Vfunc_swap_endianess_byte__90__vector_out);
    VL_RAND_RESET_W(128, vlSelf->__Vfunc_swap_endianess_byte__91__vector_out);
    VL_RAND_RESET_W(128, vlSelf->__Vfunc_swap_endianess_byte__92__vector_out);
    VL_RAND_RESET_W(128, vlSelf->__Vfunc_swap_endianess_byte__93__vector_out);
    vlSelf->__Vfunc_mubi4_test_true_strict__98__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_mubi4_test_true_strict__98__val = VL_RAND_RESET_I(4);
    vlSelf->__Vfunc_mubi4_test_true_strict__99__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_mubi4_test_true_strict__99__val = VL_RAND_RESET_I(4);
    vlSelf->__Vfunc_mubi4_test_true_strict__100__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_mubi4_test_true_strict__100__val = VL_RAND_RESET_I(4);
    vlSelf->__Vfunc_mubi4_test_true_strict__101__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_mubi4_test_true_strict__101__val = VL_RAND_RESET_I(4);
    vlSelf->__Vfunc_mubi4_test_true_strict__102__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_mubi4_test_true_strict__102__val = VL_RAND_RESET_I(4);
    vlSelf->__Vfunc_mubi4_test_true_strict__103__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_mubi4_test_true_strict__103__val = VL_RAND_RESET_I(4);
    for (int __Vi0=0; __Vi0<2; ++__Vi0) {
        vlSelf->__Vm_traceActivity[__Vi0] = VL_RAND_RESET_I(1);
    }
}
